### ISSUE TITLE
Vehicle registration certificate (CZ)

### ISSUE THREAD

**Issue by psiotwo** [SEMICeu/SDG-sandbox#100]
Vehicle registration certificate issues
1. The data for consideration as concerns the registration document and the vehicle are entered in the Czech Register of Road Vehicles (RSV), as well as the data concerning the owners and the vehicle operator, based on the Council Directive 1999/37/EC in the prescribed structure. However, the Legal User is not registered in the RVS, because such a person is allowed to drive the vehicle on a basis other than the ownership of said vehicle. Thus, for the exchange of data in the SDG project, we recommend using the basis of the aforementioned Directive, including its terminology, types, sizes or formats of data fields and harmonization codes.
2. Some of the additional data proposed for transmission may be contained within the RVS (for example – Agent, Person/Organization, Public Organization, Location/Address), but are obtained from the basic registers of the Czech Republic. Because the description of these items is not very clear from the received attachments, we cannot confirm whether they correspond to the data currently stored within the RVS and whether they will be suitable for this project. 
3. To clarify the issue, the RVS contains data on owners and operators as follows
**a.** name or names and surnames (as relevant), address of permanent residence, long-term residence, temporary residence of at least 6 months or other authorized residence and birth number, if assigned, or date of birth
**b.** business name or first name (s) and surname (s), permanent residence, long-term residence, temporary residence of at least 6 months or other authorized stay, registered office address, and identification number of the person, if assigned, if the concerned is a natural person,
**c.** business name, address of the registered office or location of the brand and the identification number of the person, if assigned, if the concerned is a legal entity or one of its branches.

**Comment by cbahim** [comment]
@psiotwo thanks for your comments. 

> The data for consideration as concerns the registration document and the vehicle are entered in the Czech Register of Road Vehicles (RSV), as well as the data concerning the owners and the vehicle operator, based on the Council Directive 1999/37/EC in the prescribed structure. However, the Legal User is not registered in the RVS, because such a person is allowed to drive the vehicle on a basis other than the ownership of said vehicle. Thus, for the exchange of data in the SDG project, we recommend using the basis of the aforementioned Directive, including its terminology, types, sizes or formats of data fields and harmonization codes.

The legal user is optional in our model. Besides, the deloitte study as well as the Council Directive 1999/37/EC have been used as a basis to create the model. 

> To clarify the issue, the RVS contains data on owners and operators as follows
a. name or names and surnames (as relevant), address of permanent residence, long-term residence, temporary residence of at least 6 months or other authorized residence and birth number, if assigned, or date of birth
b. business name or first name (s) and surname (s), permanent residence, long-term residence, temporary residence of at least 6 months or other authorized stay, registered office address, and identification number of the person, if assigned, if the concerned is a natural person,
c. business name, address of the registered office or location of the brand and the identification number of the person, if assigned, if the concerned is a legal entity or one of its branches.

In correlation with other issues, we have added the place and date of birth for the Person entity. The Address - for both persons and organisations - is already part of the model.
