### ISSUE TITLE
Certificate of completion of secondary education (CZ)

### ISSUE THREAD

**Issue by psiotwo** [SEMICeu/SDG-sandbox#101]
Certificate of completion of secondary education
1. There is not a register in place in the Czech Republic which would collect information about the completion of secondary education per se. This information may be found in the archives of individual schools.
2. The Czech Republic keeps a record of the results registered for the graduation exams (Maturita). In order to identify a pupil, the register includes the pupil’s birth number (if it has not been assigned then the name and surname of the pupil and the date and place of birth). This however concerns only Maturita exams and it has only been functioning since 2011. 
3. The inclusion of secondary schools within the SDG, even simply for the purpose of verifying graduation certificates in order to apply to universities, appears very unrealistic as concerns the Czech Republic.
4. As concerns the use of secondary school certificates in university applications we offer the following:
**a.** when submitting university applications, there is no need to present a secondary school graduation certificate as in many cases this concerns secondary school students who have not yet acquired their graduation degree. It is documented only when enrolling at a university, or earlier during the admission procedure (i.e. in both cases outside the definition of the given procedure in the SDG regulation).
**b.** The university does not communicate directly with the issuer of the graduation certificate – students from the Czech Republic issue an officially certified copy of the certificate to the university (the university then keeps this document), the authenticity of the document is officially confirmed, foreign students must have a nostrified equivalent of this.

**Comment by cbahim** [comment]
@psiotwo thanks for your feedback and apologies for the late answer. I believe you had answers to your comments by now. If not, I'd advise you to have a look a the following [report](https://ec.europa.eu/cefdigital/wiki/x/twLvEg), which has been drafted following the first formal SDG review cycle. Do you still have semantical issues with the [completion of secondary education evidence model](https://github.com/SEMICeu/SDG-sandbox/tree/master/evidences/certificate_of_completion_of_secondary_education/data_model)?
