### ISSUE TITLE
Income tax declaration certificate (CZ)

### ISSUE THREAD

**Issue by psiotwo** [SEMICeu/SDG-sandbox#102]
Income tax declaration certificate issues
1. We record most of the data items listed in the provided documents with the exception of some items (such as ‘gender’), as these are not necessary for tax assessment as determined by law.
2. Some of the data items listed are not part of the electronic income tax declaration certification, as its functionality is set in the current information system.
3. At the same time, we would like to point out that for some of the listed items required for "exchange", there is already a system in place for provision between EU states has already been set up (for information purposes we have highlighted these items in green in the attached document). Will this the new system for providing/exchanging information cancel/supplement/modernize the existing ones?

**Comment by cbahim** [comment]
Thanks @psiotwo for your comments. 

> We record most of the data items listed in the provided documents with the exception of some items (such as ‘gender’), as these are not necessary for tax assessment as determined by law.

`Gender` is not part of the Income tax declaration evidence, so there is no problem. 

> Some of the data items listed are not part of the electronic income tax declaration certification, as its functionality is set in the current information system.

Which data are your referring to? 

> At the same time, we would like to point out that for some of the listed items required for "exchange", there is already a system in place for provision between EU states has already been set up (for information purposes we have highlighted these items in green in the attached document). Will this the new system for providing/exchanging information cancel/supplement/modernize the existing ones?

@psiotwo unfortunately, I don't see any document attached, can you share it with us?

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
