### ISSUE TITLE
seconday educational evidence model - IssuingAuthority and OrganiSation missing attributes and text data type

### ISSUE THREAD

**Issue by SebastianSklarss** [SEMICeu/SDG-sandbox#104]
Having the current model as basis I suggest the following improvements to be made:

1. The address of the issuing organiSation (with "s" is British English) should be added using Core Location, especially Core Location adminLevel2 (State/Bundesland) is vital for secondary education in Germany

2. The type of the issuing authority should be added using a codelist "type of education instititution".
Then the formal ISCED-2011 should be added  ranging from ISCED-2011-Level 0 to ISCED-2011-Level 8 and saying whether the issuing organisation is a school or high school etc. as stated here:  https://github.com/SEMICeu/SDG-sandbox/issues/95

3. Name (of Organisation) should be text data type not strings, allowing for multiple language variants tagged via xml:lang , as you can see for instance here https://github.com/european-commission-europass/Europass-Learning-Model/blob/master/XML%20Examples/Ildiko%20Mazar_Certificate%20of%20Excellence.xml

allowing for:

```
<altLabel lang="en">Catholic University of Leuven</altLabel>
<altLabel lang="de">Katholische Universität Löwen</altLabel>
<altLabel lang="nl">Katholieke Universiteit te Leuven</altLabel>
```

**Comment by cbahim** [comment]
@SebastianSklarss thanks for the comments. 

1. This typo was corrected in all the models. Additionally, we will add Location adminLevel2
2. I suggest to discuss this issue in issue #95 
3. Strings have been changed to text to the extent possible to allow multiple languages variant.
