### ISSUE TITLE
Secondary Education - Core Person data diagram should show GenderCode and BirthName too

### ISSUE THREAD

**Issue by SebastianSklarss** [SEMICeu/SDG-sandbox#105]
Some attributes on the person are missing in the diagram (but not in the Core person model) that will be needed for identifying a person (e.g. having gained learning achievements abroad and then coming back to Germany handing in the foreign educational evidence for recognition in a new higher education institution):

Detail:
In Germany in absence (still) of a person idenitifier we need the following data to identify a person in a residence register if the current adress is not known: (source: http://www.osci.de/xmeld242/2019-01-31_OSCI-XMeld_242_Spezifikation_final.pdf) 

![image](https://user-images.githubusercontent.com/70315945/93070148-cafb4b00-f67e-11ea-9f4e-5a3148f9b1d7.png)

so at least the 
BirthName and the GenderCode of the core Person data model should be added in the current data model diagram (as optional) in order to identify a person via the personal data on the education credential in the German residence registers.

https://joinup.ec.europa.eu/site/core_person/CorePerson/CorePerson-v1.00.html#Link06F84DA0

![image](https://user-images.githubusercontent.com/70315945/93070899-b9ff0980-f67f-11ea-8ff9-188c4d20c669.png)

So knowing that in Sweden the NameOfBirth (https://github.com/SEMICeu/SDG-sandbox/issues/77) is not on the certificate in Germany in absence of a person Identifier it would be useful.

In doing so you could differenciate a person "Erika Mustermann geb. Müller" from "Erika Mustermann geb. Stabler"
https://upload.wikimedia.org/wikipedia/commons/3/37/Mustermann_Reisepass_2017.jpg

**Comment by cbahim** [comment]
@SebastianSklarss thanks for your comment and apologies for the late feedback. Gendercode and BirthName, as your refer them to, have been added to the final version (under internal review) - following the SDG review - of the [completion of secondary education evidence](https://github.com/SEMICeu/SDG-sandbox/tree/master/evidences/certificate_of_completion_of_secondary_education/data_model).
