### ISSUE TITLE
Secondary education - geographic name and URI might not be present or insufficient for matching with national data on location 

### ISSUE THREAD

**Issue by SebastianSklarss** [SEMICeu/SDG-sandbox#106]
In
https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/certificate_of_completion_of_secondary_education/data_model/certificate_of_completion_of_secondary_education_diagram_v0.12.pdf 
now the structured core location address information is no longer present in favor of a generic mandatory
"geographic name" and "Geographic URI".

I suggest 

1. re-adding in addition the more structured (and currently present in the target groups IT systems!) 
core location adminUnitL1 (Country)  as it was in 
https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/certificate_of_completion_of_secondary_education/data_model/certificate_of_completion_of_secondary_education_diagram_v0.10.pdf 
and 
2.  to explicitly allow for a mandatory adminUnitL2 (stating the county or state of the issuing organisation) and other address data as defined by Core Location Address (http://www.w3.org/ns/locn#Address)

**Comment by cbahim** [comment]
Thanks @SebastianSklarss for your comments. We will take your advice and add the attributes adminUnitL1 and adminUnitL2 have been added.
