### ISSUE TITLE
COmments on datamodel for evidence of secondary education

### ISSUE THREAD

**Issue by KlavsHelbergJensenDKDIGST** [SEMICeu/SDG-sandbox#108]
Specific data model comments
In the below mentioned applies an approach to the data model, where it is secured that proof of completion of an upper secondary education is able to include those informations which are characteristic hereof. The approach is chosen for the purpose of avoiding that individuals by who the process of data exchange has been initiated should procure further manually proof of completion of an upper secondary education. Alternatively, a different approach to the data model should be based on the opposite principle, which is characterized by some minimum requirements to a logical model. However, this approach entails the substantial risk of a procedure that lacks the necessary categories and attributes needed to provide acceptable proof of completion of an upper secondary education for the recipient system. Resulting in requirements of supplemental (manually procured) evidence. 

Regarding “Course Result”
The Danish Agency for It and Education (STIL) presume the latter being a part of a certificate, but more information is necessary to describe a mark (grade), including: 
•	SubjectCode: String <typically a six digit identifier>
•	Level: String
•	MarkingScale : String
•	MarkWeight: Float
•	MarkQualifier: String
•	IssuedDate: Date

A course/subject may consist of several marks (eg. an oral examination and a written examination).
Regarding ”SecondaryEducationCompletionCertificate” 
The date of the issue of a certificate must be adopted in the model. In Denmark, specific rules of arithmetic’s applies to calculating the grade point average in upper secondary education (eg. applies a multiplying factor if the student enroll in an additional course/subject on the highest level)

It is necessary to clarify by which marking scale the grade point average is calculated (certificates bases on a prior grade scoring model is still being issued in Denmark).

Furthermore, it has to be clarified whether it should be up to the receiving institution to convert local marking scales to international scales. 

In Denmark, various types of study for upper secondary education. It should be considered if it offers any value for the data consumer to include this kind of information too. An attribute concerning the above is especially worth noting in relation to upper secondary educations which do not directly qualifies you to institutions of further education. 

Regarding “Education Institution”
Regarding “Education Institution”, the following is missing:
•	InstitutionIdentifier : Int <Typically a six digit number>
•	LegalUnitName : String
•	Optionally a value? that describes if the institution still exists/is operative. 
Regarding”IssuingAuthority”
In Denmark, it is the institutions, which provides the education in their field of responsibility that are issuing certificates for upper secondary educations and not the Ministry. 
Regarding “Organization”
STIL presumes, that this refers to the responsible executive Ministry - that is the Ministry for Children and Education. 
Regarding “Student”, “Person”, “Location” and “Address”
In general, STIL questions the use of the term “Student” in the model, as it is redundant to have this appellation in the model. A person (identified by for example a personal identification number) may or may not have a certificate for an upper secondary education. Fundamentally, the registers and systems concerning storage of data evidence, which is used by the Danish Ministry of Children and Education, do not contain person related information such as address and birthplace. This does not make any logical sense for the concerned systems and the data attachment of for example persons “current address” with a ‘UU’-certificate, that could only be established through a data connection between registers of certificates and registers of people, which are not within the Danish Ministry for Children and Education field of responsibility. The connection of data on education and relevant person related data is primarily done by subsequent statistical data processing, which subsequently cannot be used regarding person related administrative processes. 
“Location” appear irrelevant for the data exchange.

**Comment by SebastianSklarss** [comment]
+1 for questioning the term "student" 
I raised an own ticket here https://github.com/SEMICeu/SDG-sandbox/issues/112 suggesting "learner"

**Comment by cbahim** [comment]
With regards to your specific comments

> Regarding “Course Result”

> The Danish Agency for It and Education (STIL) presume the latter being a part of a certificate, but more information is necessary to describe a mark (grade).

We will have a more detailed look on how to model grades in the next round, as many of those evidences relate to education.

> Regarding ”SecondaryEducationCompletionCertificate”

> The date of the issue of a certificate must be adopted in the model.

The issuingDate attribute has been added.

> In Denmark, various types of study for upper secondary education. It should be considered if it offers any value for the data consumer to include this kind of information too. An attribute concerning the above is especially worth noting in relation to upper secondary educations which do not directly qualifies you to institutions of further education.

This evidence relates to ISCED 2011 level 3.

> Regarding “Education Institution”, the following is missing:

>- InstitutionIdentifier : Int
>- LegalUnitName : String
>- Optionally a value? that describes if the institution still exists/is operative.

>Regarding”IssuingAuthority”
 
InstitutionIdentifier relates to PublicOrganisation.identifier and LegalUnitName relates to PublicOrganisation.prefLabel.
 
>  Fundamentally, the registers and systems concerning storage of data evidence, which is used by the Danish Ministry of Children and Education, do not contain person related information such as address and birthplace.
 
These attributes are either removed or optional.
