### ISSUE TITLE
Income tax declaration certificate (AT)

### ISSUE THREAD

**Issue by Carl-MarkusPiswangerAT** [SEMICeu/SDG-sandbox#110]
**1.	Do I agree with the proposed controlled vocabularies (code lists)?** 
We partly agree:
•	Income Tax is not defined clearly. There are 7 types of income in AT, e.g. we differentiate between Income based on self-employed work and employed. 
•	Some of the used vocabularies are not clear enough and need further explaination for our setting. E.g. the attributes „preferred label“, „identifier“ (as described not available in AT) and „address“:
We currently have the following situation: The Financial Authority in charge is based on the Tax Payer's location;
This is subject to change. As from 2021 there will be: One centralized Financial Authority Austria for Residents and Small Businesses. In addition, there will be the (centralized) Financial Authority for Large Businesses.
•	Additional question from our side: Is there a generalized base collection of vocabularies , e.g. like „CPSV“?

**2.	Do I agree with the proposed changes to the data models?**	
We are only familiar with the currently proposed version of the data models.

**3.	Are the entities and attributes definitions clear enough?**				
Please see answer to first question - further explaination would help in some cases.

**4.	Does the modelling approach make sense?**
The current modelling apprach seems static. It covers the data provider view, but also has to be validated against data consumer requirements. 

**5.	Do I agree with the proposed cardinalities (i.e. mandatory versus optional)?**	
From the current point of view, the cardinalities make sense. They also have to be checked from a data consumer perspective and also be monitored when future changes to the data models are made.

**6.	With data minimisation in mind, should some of the entities and or attributes stripped off?** 
The proposed entities and attributes represent the minimum set of data we need (from a data provider view).

**7.	Will my country be able to provide all the mandatory information?** 
We will be able to provide most of the information, except the Identifier for the Income Tax Evidence.
More details are necessary in some cases – please see answer to first question.

**Comment by cbahim** [comment]
Thanks @Carl-MarkusPiswangerAT for your comments. 

> 1. Do I agree with the proposed controlled vocabularies (code lists)?
We partly agree:
• Income Tax is not defined clearly. There are 7 types of income in AT, e.g. we differentiate between Income based on self-employed work and employed.
• Some of the used vocabularies are not clear enough and need further explaination for our setting. E.g. the attributes „preferred label“, „identifier“ (as described not available in AT) and „address“:
We currently have the following situation: The Financial Authority in charge is based on the Tax Payer's location;
This is subject to change. As from 2021 there will be: One centralized Financial Authority Austria for Residents and Small Businesses. In addition, there will be the (centralized) Financial Authority for Large Businesses.
• Additional question from our side: Is there a generalized base collection of vocabularies , e.g. like „CPSV“?

We will look into possibilities to further define Income Tax and attributes related to the Core Vocabularies.

>7. Will my country be able to provide all the mandatory information?
We will be able to provide most of the information, except the Identifier for the Income Tax Evidence.
More details are necessary in some cases – please see answer to first question.

Given that you will not be able to provide the Identifier for the Income Tax Evidence, we have made the latter optional.
