### ISSUE TITLE
Secondary education (and other education data models) - Naming issues with entity named "Student"

### ISSUE THREAD

**Issue by SebastianSklarss** [SEMICeu/SDG-sandbox#112]
A more general term that comprises 
a) secondary and 
b) tertiary education and 
c) professional qualifications might be "learner" instead of student.

Learner is also used by the EMREX/ELMO Specification, a specialised semantic container format for the Transcript of Record used in Scandinavian countries, NL and Poland. 
https://github.com/emrex-eu/elmo-schemas/releases

Europass EDCI uses "Person" or eIDAS natural person and does not have a more education specific term
https://joinup.ec.europa.eu/sites/default/files/release/documentation/2020-03/edci_diagrams_v0.5.0-1.0.0.pdf

**Comment by XHochschuleDE** [comment]
should be reopend as still not solved everywhere:
In the `diploma evidence`  and in the `record of results` the Student is defined as
_"A Person who attended school."_ -> I would have expected _A person who attends a Higher Education Institution_"

In the diploma the Student is defined as Learner (good!) but in the semantic statement there is still "An unambiguous reference to the Student." -> the Learner still is not yet a student in a university.

**Comment by cbahim** [comment]
@SebastianSklarss Thanks for bringing this to our attention. 

Indeed, as requested during [Webinar #5](https://ec.europa.eu/cefdigital/wiki/x/XIcODw), we no longer refer to a `student` but to `learner` for the Completion of Secondary Education evidence. 

We therefore propose to update the definition of `learner` to "A person who attends a Secondary Education Institution" for

- Completion of Secondary Education Evidence

and also update the definition of `student` to "A person who attends a Tertiary Education Institution" for 

- Tertiary Education Diploma Evidence
- Tertiary Education Diploma Supplement Evidence
- Record of Results Evidence

Apologies for closing the issue whereas the matter was not resolved. In the future, don't hesitate to reopen an issue if need be.
