### ISSUE TITLE
Birth Certificate (PT)

### ISSUE THREAD

**Issue by ama-epse** [SEMICeu/SDG-sandbox#113]
In reply to a previous issue (#79) comment a) and b) where dropped because no other MS expressed the need to have it.
Our domain experts reinforce the need for these issues to be addressed on the model for Birth Certificate.

Issues were:

a) In Portugal, the authority that issues the certificate may not be the one who registered the birth. There is no national authority overseeing and issuing these certificates. There is one for each region. Registrations are done in the region of birth (e.g. Lisbon), but can be solicited in a different region (e.g. Faro).
Therefore we need two fields for organisation. The Issuer and the Register.

b) In Portugal information about the clerk that wrote/issued the certificate is required.

**Comment by cbahim** [comment]
@ama-epse thanks for your comments. The reason why the comments were dropped is that if no other MS expressed the need to have it this can be interpreted as MS being either not able to provide it to PT or not needing that information from PT. 

What we propose to do is, add the proposition (a & b) to our next meeting taking place after the end of the first SDG formal review cycle (18th of November - Webinar #8) .
