### ISSUE TITLE
Marriage Certificate (PT)

### ISSUE THREAD

**Issue by ama-epse** [SEMICeu/SDG-sandbox#114]
In reply to a previous issue (#80) comment a) was dropped because no other MS expressed the need to have it.
Our domain experts reinforce the need for this issue to be addressed on the model for Marriage Certificate.

Issue was:

a) In Portugal information about the clerk that wrote/issued the certificate is required.

**Comment by cbahim** [comment]
Thanks @ama-epse for your comment. Please see my answer here #113.
