### ISSUE TITLE
Vehicle Registration (PT)

### ISSUE THREAD

**Issue by ama-epse** [SEMICeu/SDG-sandbox#115]
Regarding the information on Vehicle Registration vs. License Plate Registration, the problem is not only the fact that they are different numbers, (as replied in issue #81) but more the fact that the information resides in two distinct databases, in two different authorities within the country, and therefore is represented by two different models at the moment.

The authority that regulates property registration (in this case for vehicles) is different from the authority that regulates transportation (and therefore Licence Plate Registration).

If the model is global for the Vehicle itself this will have to be considered somewhere along the way.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
