### ISSUE TITLE
Jurisdiction definition

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#117]
In the marriage certificate and in the birth certificate we have a Jurisdiction class. For the ID of that class in one certificate (birth) there is the indication to use the country code list, while in the other certificate (marriage) there is "N/A" as code list for the ID, that sounds strange (we will use the URI of Country concept in the controlled list to define the overall Jurisdiction class, right?). 
Should the overall definition of the class Jurisdiction with its properties be the same in both certificates?

**Comment by cbahim** [comment]
Thanks @giorgialodi for your comment. We are not sure when, but this has been solved 🙂. Thanks for pointing that to us.
