### ISSUE TITLE
University diploma and ISCED (or other) level/controlled list

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#119]
One of the Regions in Belgium commented that it could be helpful to have a property to classify types/levels of diplomas, e.g. ISCED or another controlled list

It seems that the current university diploma does not make a distinction between e.g. bachelor/master/doctor level, other than perhaps a free text description in the diploma title itself.

Somewhat related to #95 (secondary degree)

**Comment by cbahim** [comment]
@barthanssens thanks for your comment. It refers to the following attribute `qualificationLevel`, in line with [ISCED ](https://ec.europa.eu/eurostat/statistics-explained/index.php/International_Standard_Classification_of_Education_(ISCED)#ISCE) and with the following code list (to both the _tertiary education diploma evidence_ & _tertiary education diploma supplement evidence_) :

- ISCED level 5 – Short-cycle tertiary education
- ISCED level 6 – Bachelor’s or equivalent level
- ISCED level 7 – Master’s or equivalent level
- ISCED level 8 – Doctoral or equivalent level
