### ISSUE TITLE
University Diploma Supplements to contain information required by EC / CoE / UNESCO Template for European Higher Education Area (EHEA)

### ISSUE THREAD

**Issue by SebastianSklarss** [SEMICeu/SDG-sandbox#120]
The Diploma Supplement is jointly developed by the Council of Europe, European Commission and UNESCO and an updated version was adopted by the Lisbon Recognition Convention Committee in 2007.

[http://www.ehea.info/media.ehea.info/file/2018_Paris/72/5/MEN_conf-EHEA_AG4_02_950725.pdf](http://www.ehea.info/media.ehea.info/file/2018_Paris/72/5/MEN_conf-EHEA_AG4_02_950725.pdf)
shows a template which has at least the following information **in addition** or more precise to the current proposal of the SDG evidence "University Diploma supplement"

1. **language of instruction / examination**
2. **main fields of studies**
3. level of qualification
4. official duration of programme in credits (ECTS) and/or years 
5. **access requirements**
6. **mode of study**
7. **Programme learning outcomes**
8. **grade distribution table**
9. **linking the transcript of record to the diploma supplement**

More in detail copying the explanatory notes: and _suggesting controlled vocabularies in italic_

1:Language(s) of instruction/examination:
Indicate the language(s) by which the qualification was officially delivered and examined.
_My recommendation is to use the language code list from PO
http://publications.europa.eu/resource/dataset/language_ 

2: main fields of studies
Show only the major field(s) of study (disciplines) that define the main subject
area(s) for the qualification e.g. Politics and History, Human Resource Management, Business
Administration, Molecular Biolog y etc

_My recommendation is to use the ISCED 2013F code list in addition to a text field for the sake of an interoperable approach as mentioned earlier https://github.com/SEMICeu/SDG-sandbox/issues/95#issuecomment-691908592_
 
_ISCED 2013 codes are availabe in machine readable formats from Eurostat codelist server RAMON and can be expressed as ISA² metadata rdf vocabularies also :_
https://ec.europa.eu/eurostat/ramon/nomenclatures/index.cfm?TargetUrl=LST_CLS_DLD&StrNom=CL_ISCEDF13&StrLanguageCode=EN&StrLayoutCode=HIERARCHIC
_Once transfered to RDF they could be hosted together with other "SDG-Codelists" using a persistent URI here 
https://data.europa.eu/URI.html_

3: Level of qualification
Give the precise level of the qualification and its place in the specific national
educational structure of awards, and/or in the National Qualifications Framework,
if available (cross-referenced to the information in point 8). Reference should also be
made to the corresponding level in the two main overarching Qualifications Frameworks:
QF-EHEA and/or EQF, e.g., Second cycle QF-EHEA/Level 7 EQF.

_My recommandation is instead of using only text to use the ISCED 2011 Level, also available on RAMON
https://ec.europa.eu/eurostat/ramon/nomenclatures/index.cfm?TargetUrl=LST_NOM_DTL_LINEAR&IntCurrentPage=3&StrNom=CL_ISCED11&StrLanguageCode=EN_
_and suggested also by Belgium https://github.com/SEMICeu/SDG-sandbox/issues/119_

4: Official duration of programme in credits and/or years:
Indicate the total student workload required and/or the official duration of the
programme in years of full-time study. The student workload should be described in terms
of credits and the credit system used should be indicated. EHEA countries are expected
to make reference to the European Credit Transfer and Accumulation System (ECTS), e.g. 2 years /120 ECTS credits.

5: Access requirement(s)
 List the qualification(s) or periods of study required for access to the programme
described by this Diploma Supplement (cross-referenced to the information in point 8),
e.g. Matura (for access to a first degree programme) or Bachelor Degree (for access to a
second degree programme). This is particularly important when intermediate studies
are a prerequisite for the named qualification. 

_My recommendation is to check whether ISCED-Level 2011 can also be used here_

6:  Mode of study: 
The mode of study refers to how the programme was undertaken e.g. full-time,
part-time, intermittent/sandwich, e-learning, distance, etc. 

_My recommendation is to use the Europass vocabulary learning-opportunity
http://data.europa.eu/snb/learning-opportunity/25831c2_ 
_and to cross check whether other vocabularies from Europass might be useful https://op.europa.eu/en/web/eu-vocabularies/europasstables_

7:  Programme learning outcomes
 Indicate the learning outcomes associated with the qualification. Learning outcomes
are statements of what the graduate knows, understands and is able to do after completing
his/her studies and receiving the qualification (knowledge, skills, competencies). Learning
outcomes should be expressed in the present tense, e.g.: “The graduate can analyse
consumer behaviour trends and apply them in a given consumer market”. This information
is increasingly becoming the key basis on which qualifications are assessed and/or
recognized. 

8: Grading system and, if available, grade distribution table:
 Provide information on the grading system and pass marks relating to the qualification,
e.g.: marks are out of a possible 100% and the minimum pass mark is 40%. Tremendous
variations in grading practices exist within and between different national higher education
institutions and countries. In order to provide information on the use of grades in a
specific context, a grade distribution table relating to the qualification in question should
be included. If more than one grading system is used, e.g.: in the case of joint degrees,
information should be provided on all systems used for the qualification in question. If this
section is too long, it can be included in the transcript of records

9. Linking the transcript of record to the DS
_my recommendation is to link the transcript of record (what here is currently called "results from the previous academic year"to the diploma supplement_ 
The explanatory notes state:
(if this information is available in an official transcript this should be used here) 

The DS template looks like this:

![image](https://user-images.githubusercontent.com/70315945/95157378-1f36ae00-0799-11eb-9c19-d5801cb66053.png)
![image](https://user-images.githubusercontent.com/70315945/95157407-39708c00-0799-11eb-94ec-2b102db404ca.png)

Various real life Diploma, Diploma Supplements and Trancripts of records (in the SDG data model and [the Deloitte Study ](https://sdg.mindigital.gr/uploads/Deloitte_final_report.pdf) called "results from the previous academic year") from Higher Education Institutions (including Universities) are published by students in the internet.
See here a full example of a German and English from the Technical University of Munich
https://me.benediktschmidt.at/data/master_zeugnis.pdf

**Comment by cbahim** [comment]
Thanks for these comments, @SebastianSklarss. Very helpful. 

1. We have just added `language` to all evidences referencing the following [code list](http://publications.europa.eu/resource/authority/language). 
2. This refers to the `qualificationLevel` which has been added, as mentioned in issue #129. However, we will add `mainFieldOfStudies` to the _Tertiary Education Diploma Supplement Evidence_
3. Already present in the model. We will make sure to use the code list you shared with us. 
4. Already present in the model
5. We have added `accessRequirements`as Code to the _Tertiary Education Diploma Supplement Evidence_
6. We have added `modeOfStudy`as [Code](http://publications.europa.eu/resource/authority/snb/learning-opportunity/25831c2) to the _Tertiary Education Diploma Supplement Evidence_
7. We have added `programmeLearningOutcomes`as Text the _Tertiary Education Diploma Supplement Evidence_
8. We will try to clarify the grading issue during our next webinar. 
9. We will explore this proposition during our next webinar.
