### ISSUE TITLE
Vehicle registration certificate

### ISSUE THREAD

**Issue by KlavsHelbergJensenDKDIGST** [SEMICeu/SDG-sandbox#121]
Consider adding measuring norm qualifiers to the exhaust CO2 figure. The figure depends on the measuring norm - e.g. NEDC or WLTP measurements. If the norm of the exhaust figure is unspecified, the recipient of the data cannot interpret it correctly - e.g. for taxation purposes.

Please take a look at the report from EReg Topic Group XXI: Harmonization of registration procedures, and data quality, Proposal on the registration of vehicle data for M1, for more information related to this [problem.](url)

**Comment by kassch** [comment]
To elborate on the above, the report can be found here: https://www.ereg-association.eu/topic-groups/topic-group-xxi/ 
It might be behind a login, though. We've tried uploading the report here. If it doesn't work, contact us for a copy.

[Draft report Topic Group XXI - Proposal on the registration of vehicle data for M1 0.2.docx](https://github.com/SEMICeu/SDG-sandbox/files/5340368/Draft.report.Topic.Group.XXI.-.Proposal.on.the.registration.of.vehicle.data.for.M1.0.2.docx)

**Comment by cbahim** [comment]
@kassch @KlavsHelbergJensenDKDIGST thanks for your comments. What is the status of your document? 

We can propose to our next meeting the splitting of our current `CO2` attribute following your proposition 

- (46) NEDC CO2 emission
- (56	) WLTP  CO2 emission 

Do you also see other attributes that should be split according to your document (e.g. NOx)?

**Comment by kassch** [comment]
@cbahim Thanks for the reply. 

It should be ensure that all emission parameters is delivered with an indication of the measurement standard in use. There will possibly be parameters, other than CO2, where it needs to be clear, what measurement standard is used.
If the data model contains more than one fuel type (e.g. fuel, electricity or a combination thereof), now or in the future, a common set of indicators on measurement standard should be available.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
