### ISSUE TITLE
Feedback on: Birth certificate evidence (AT)

### ISSUE THREAD

**Issue by Carl-MarkusPiswangerAT** [SEMICeu/SDG-sandbox#122]
1) Do I agree with the proposed controlled vocabularies (code lists)? | We agree with the proposed vocabularies.

2) Do I agree with the proposed changes to the data models? We are only familiar with the   currently proposed version of the data models.

3) Are the entities and attributes   definitions clear enough? Yes, the entities and attributes definitions are clear enough.

4) Does the modelling approach make sense? 
The modelling approach makes sense, but there are two aspects that should be considered: 1. In AT, the data for the Evidence is dynamic and can change over time. E.g. academic degrees which are obtained later in life, can also be part of the evidence data, if the evidence is issued afterwards. 2. The person’s identifier should be and EU-wide ID, the usage of a local and national ID as identifier is not advisable from our experience.

5) Do I agree with the proposed cardinalities (i.e. mandatory versus optional)? We agree with the proposed cardinalities.

6) With data minimisation in mind, should some of the entities and or attributes stripped off? The proposed entities and   attributes represent the minimum set of data we need from a data provider   view. From a data consumer perspective, also ‚other names‘ (e.g. middle   names) has to be provided as an attribute where available.

7) Will my country be able to provide all the mandatory information? We will be able to provide most of the information, except of:   
• Evidence.Issuing place: only the state is available on the Evidence   
• Person.Identifier: not available on the Evidence   
• Person.Citizenship: not available on the Evidence   
• Jurisdiction.id: not available on the Evidence   
• Public Organisation.Identifier: not available on the Evidence, but   available in the system   
• Location.Geographic name: not available on the Evidence   
• Location.Geographic Identifier: not available on the Evidence

**Comment by cbahim** [comment]
@Carl-MarkusPiswangerAT Thanks for your comments. 

**(4.2)** We don't say that in our models. Would you care to develop? 
**(7)** Thanks for sharing this, in all cases attributes are optional, so no problem here. However, for the last two, could you develop? You didn't say that you were not able to provide the `birthPlace`.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
