### ISSUE TITLE
Feedback on Marriage evidence (AT)

### ISSUE THREAD

**Issue by Carl-MarkusPiswangerAT** [SEMICeu/SDG-sandbox#123]
1)  Do I agree with the proposed controlled vocabularies (code lists)? | We agree with the proposed vocabularies.

2)  Do I agree with the proposed changes to the data models? We are only familiar with the currently proposed version of the data models.

3) Are the entities and attributes definitions clear enough? Yes, the entities and attributes definitions are clear enough.

4)  Does the modelling approach make sense? The modelling approach makes sense,   but there are two aspects that should be considered: 
- In AT the data for the Marriage Evidence is dynamic and can change over   time. E.g. academic degrees which are obtained later in life, can also be part of   the evidence data, if the evidence is issued afterwards.      
- The person’s identifier should be and EU-wide ID, the usage of a local and   national ID as identifier is not advisable from our experience

5) Do I agree with the proposed cardinalities (i.e. mandatory versus optional)? We agree with the proposed cardinalities, except of place of marriage. This attribute should be mandatory.

6) With data minimisation in mind, should some of the entities and or attributes stripped off? The proposed entities and   attributes represent the minimum set of data we need from a data provider   view. From a data consumer perspective, also other names (e.g. middle names)   and gender have to be provided as an attribute where available.

7) Will my country be able to provide all the mandatory information? We will be able to provide most of the information, except of:
• Evidence.Issuing place: only the state is available on the Evidence
• Person.Identifier: not available on the Evidence
• Person.Citizenship: not available on the Evidence
• Jurisdiction.id: not available on the Evidence
• Additional Marriage Info.marital status before marriage: not available on the Evidence
• Additional Marriage Info.capacity to marry: not available on the Evidence
• Public Organisation.Identifier: not available on the Evidence, but available in the system
• Location.Geographic name
• Location.Geographic Identifier

**Comment by cbahim** [comment]
Thanks @Carl-MarkusPiswangerAT for your comments. 

**(5)** In the [editable tables](https://ec.europa.eu/cefdigital/wiki/x/lwToE) a MS is not able to provide that information, so we propose to keep the `placeOfMarriage` optional. 
**(7)** Thanks for sharing this, all attributes are optional so no problem here. Capacity to marry has been removed from the model.
