### ISSUE TITLE
educational evidences: Feedback on errata issues and deviations between tables and diagrams

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#124]
The German project XHEIE.EU will soon provide several [consolidated comments of German Higher Education Institutions](http://www.xhochschule.de/web/node/16) to the educational evidences on a field per field basis.  

Meanwhile  smaller quick-fix issues recognised during the analysis that were sent to us 
**(credits to Markus von der Heyde of SemaLogic UG):**

1. `contains`-relationship in diagramm but not in table
https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/university_diploma_supplement_evidence/data_model/university_diploma_supplement_evidence_diagram_v0.01.png
shows a "contains" relationship which is not shown in the corresponding table
https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/university_diploma_supplement_evidence/data_model/university_diploma_supplement_evidence_tables_v0.01.md

2. wrong spelling of example name in `given name`
Johan**n** Sebastian Bach the great German composer and musician of the Baroque period has its first given name spelled with two "n" (not Johan!) 
(And yes, this small error needs to be fixed also at the source meaning the core person vocabulary
 

3. missing entity definition `Issuing Authority` in University Diploma and University Diploma Supplement and Record of Results evidence
Issuing Authority is mentioned as entity but not defined in the model diagramm nor in the table.
In https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/certificate_of_completion_of_secondary_education/data_model/certificate_of_completion_of_secondary_education_tables_v0.02.md the expected type was casted to Public Organisation

Sebastian commenting under the umbrella of XHochschule.de / [XHEIE](https://www.youtube.com/watch?v=RGzclgtpnWA )

**Comment by cbahim** [comment]
@XHochschuleDE thanks for letting us know. 

1. This will be corrected in the new version of the table. 
2. Indeed, this is an error at the Core Person Voc level. We will however change it in all our models. 
3. Issuing Authority used to be a class but is now modelled as a relationship in all models. We didn't see any definition missing.

**Comment by SebastianSK** [comment]
@cbahim : In Core Vocabularies 2) was fixed but I still can find it here (saw it through the review of the SDG technical design documents):

Regarding 2) 
Johann Sebastian Bach still missing one "n" in 

a) Income tax  
https://github.com/SEMICeu/SDG-sandbox/blob/5b6c1a4f9ccc38b087648f2d8e25dde9c4895e01/evidences/income_tax_declaration_certificate/data_model/income_tax_declaration_certificate_tables.md

b) and  criminal record
https://github.com/SEMICeu/SDG-sandbox/blob/5b6c1a4f9ccc38b087648f2d8e25dde9c4895e01/evidences/absence_of_a_criminal_record_evidence/data_model/absence_of_a_criminal_record_evidence_tables.md 

Source:
https://github.com/SEMICeu/SDG-sandbox/search?q=johan+Sebastian
