### ISSUE TITLE
Education Evidences in general: not all EducationInstitutions and issuingAuthorities are Public Organisations

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#125]
![image](https://user-images.githubusercontent.com/72596288/95880221-9068f900-0d77-11eb-8172-b0cb2351b1c4.png)

Entity `Education Institutions `is defined as  
_An Organisation that provides instructional services to individuals or education-related services to individuals and other educational institutions_
and
`Public Organisation` defined as
_Any organisation that is defined as being part of the public sector by a legal framework at any level._

Problem: Not all education institutions are public organisations. In  Germany and in other EU Member State private Higher Education Institutions do exist. 

Recommendation:  Use a generic core vocabulary out of "CV legal entity / business" and "Public Organisation" called "Organisation"

This issue was found within the XHEIE German SDG data model "[call for comments](http://www.xhochschule.de/web/en/node/17)" amonst others by _Brandenburgische Technische Universität Cottbus-Senftenberg_  in the [version 0.0.1 of the diploma evidence ](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/university_diploma_evidence/data_model/university_diploma_evidence_diagram_v0.01.png)
and other tables and diagrams

**Comment by cbahim** [comment]
@XHochschuleDE Thanks for your comment, we agree with it. Therefore we propose to change `PublicOrganisation` to `Organisation` and update the definition accordingly.
