### ISSUE TITLE
Education evidences in general: relationship between three evidences and the need for the same (extended) person data model

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#126]
Please note that there is a relationship between the three evidences that currently is not visible in the specification / data models.

A diploma has it's diploma supplement. The diploma supplement contains course results in an extra evidence (not in the supplement itself) called transcript of record (what is called record of results here).  This is also the reason why the grades of the diploma are not repeated in the diploma supplement. 
They all should in the conceptual evidence exchange refer to the same person data (once only, data mininalistic) or at least link to each other via evidence IDs and be on the conceptual level be modelled the same way.

Therefore it is not clear why the person data is modelled so differently in the four evidences:
a) in the Diploma the person benefits of a dateOfBirth and placeOfBirth but not in the corresponding
b) in the diploma supplement has no placeOfBirth and lacks of a location (it is the same person, the supplement just provides supplementary information on the courses that led to the underlying the diploma.
c) in the certificate of completion the person is also not located and does not have the necessary placeOfBirth
d) in the record of results the person is located but benefits of the (more realistic) full address which would be needed in the other educational evidences too

**Recommandation**: To use one and the same data detail from the core person data model and in addition some more fields discussed here (Placeholder)

A real life example featuring the four evidences of one person can be found here: https://me.benediktschmidt.at/data/master_zeugnis.pdf

![image](https://user-images.githubusercontent.com/72596288/95882921-8e546980-0d7a-11eb-8d05-75510ed71462.png)
![image](https://user-images.githubusercontent.com/72596288/95883008-a9bf7480-0d7a-11eb-9b2c-170fd5f5befc.png)
![image](https://user-images.githubusercontent.com/72596288/95885900-24d65a00-0d7e-11eb-9e0e-490559da709c.png)

This issue was found within the XHEIE German SDG data model "[call for comments](http://www.xhochschule.de/web/node/17#issueNoOnceOnlyPersonData)" amonst others by Technical University Munich, Universität Kassel, University Duisburg Essen and RWTH Aachen 
on the evidences certificate of completion secondary education, diploma, diploma supplement and record of results.

**Comment by cbahim** [comment]
Thanks @XHochschuleDE for your comments. 

1.  As mentioned, the evidences should be complementary. Therefore, we have removed the `CourseResult` from the _Tertiary education diploma supplement evidence_. 
2. We will improve the consistency of the Person across evidences by including the `dateOfBirth` as mandatory, `placeOfBirth` and `Address` as optional.
