### ISSUE TITLE
Education Evidences in general: use time periods instead of dates to identify properly a school/academic year/course academic year

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#127]
In Germany and in some other Member States there is no exact identical europewide defined 
`school year` in the certificate of completion of secondary education or
`course academic year` in the diploma supplement
or
`academic year` in the record of results.

These are periods with starting and ending dates which are not the 01.01 and the 31.12. and which may differ among the Member States. There is also the need to store information of semesters or even trimesters.

How will you as a receiving Member State differenciate a winter from a summer semester when the date provided is "01/09/2020"?

**Recommendation**: to use a) a time period instead of a date in the three evidences and b) to provide a text field for the more commonly used mentioning of the semester

This issue was found within the XHEIE German SDG data model "[call for comments](http://www.xhochschule.de/web/en/node/17#issueYearNotSufficientForPeriods)" amonst others by Technical University Munich (TUM), Semalogic and Karlsruhe Institut of Technology (KIT)
on the evidences certificate of completion secondary education, diploma supplement and record of results.

**Comment by cbahim** [comment]
Thanks @XHochschuleDE for you comments. 

- `courseAcademicYear` was removed at the same time than `CourseResults`
- We have added `academicYear` and `studyDuration` to the _Tertiary education diploma supplement_.
- We have added `courseAcademicSemester` to the _Records of results_.

**Comment by XHochschuleDE** [comment]
Thank you @cbahim . 
What about `school year` in certificate of completion of secondary education?
