### ISSUE TITLE
Education Evidences in general: grade point average/ course/overall grade as float or percentage not saying anything without a scale / grading system

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#128]
In Germany and in other Member States there are no grades that can be expressed by percentage or float only.

At school (certificate of completion of secondary education) there are notes ranging from 1.0 to 4.0 (worse notes will not lead to such an certificate).
It is not clearly defined how to transform those marks into percentages and vice versa. Exact marks  are needed e.g. in combination with AdminUnitLevel2 for recognition processes between German federal states. Also the total number obtainable and the minimum points required would form a grade system needed to understand the grade in a seamless data exchange across borders.

If it shall definitely be a percentage then a) a calculation scheme (Notensystem) has to be provided and b) then a xs:decimal or integer would be better to avoid rounding of floats within the system. 

Recommendation:  See how Grading, marks etc is modelled e.g. in DG EMPL Europass and EMREX/ELMO mapping tables and to add at least Minimum grade to graduate and Maximum obtainable grade to the overall grade

https://github.com/european-commission-europass/Europass-Learning-Model/blob/master/Correspondence%20Tables/ELMO/ELMO-EDC%20Correspondence.xlsx
a) there are no credits without a credit scheme
b) grading and gradingSchemeLocalId
c) in addition number of hours and status without grades (passed, failed) give easy context for recognition processes 
d) education level (national and european codelist) complements the grade
f) resultDistribution (as needed by the record of results) is given  

![image](https://user-images.githubusercontent.com/72596288/95895452-f8750a80-0d8a-11eb-816a-22d593a25e4c.png)

[https://www.gesetze-bayern.de/Content/Resource?path=resources%2fBayVV_2235_1_1_2_K_1005_BayVV2235-1-1-2-K-1005-KF-001-Anhang-006.PDF](https://www.gesetze-bayern.de/Content/Resource?path=resources%2fBayVV_2235_1_1_2_K_1005_BayVV2235-1-1-2-K-1005-KF-001-Anhang-006.PDF) shows on the last page a grading scheme:

15 Punkte = +1, 
14 = 1, 
13 = 1-
and so on

This is related to the issue (Platzhalter) where information on the status (passed, failed) is required.

see [https://www.km.bayern.de/download/16343_oberstufeabschluss2017.pdf](https://www.km.bayern.de/download/16343_oberstufeabschluss2017.pdf) for more details on the situation in German federal state Bavaria

This issue was found within the XHEIE German SDG data model "[call for comments](http://www.xhochschule.de/web/en/node/17#issueFloatNotSufficientAsGrade)" amonst others by Technical University Munich (TUM), Semalogic, Karlsruhe Institut of Technology (KIT), University of Kassel, Tieraerztliche Hochschule Hannover, University of Mannheim, 
on the evidences certificate of completion secondary education, diploma, diploma supplement and record of results.

**Comment by cbahim** [comment]
Thanks @XHochschuleDE. The topic at hand relates to issues #54, #108 and #120. We have formulated a proposition which will be presented in our webinar tomorrow at 3.00 PM.
