### ISSUE TITLE
Evidence Diploma: joint degrees, designation, title of final exam and other attributes missing

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#129]
Several information on a diploma that might be necessary for 
a) applying for a job or
b) recognition processes as defined in user centric WP2 and Annexe II of SDGR are not yet present in the data model university diploma.

Examples are:
3. title of the final exam (Abschlussarbeit) should be there coded in TEXT allowing for language variants
4.  language of the diploma (or will there be ONE Diploma with all the language variants in one file?)
5.  ISCED Level 11 and ISCED Level F13  (see also here on the codelist for fields of studys and qualifications https://github.com/SEMICeu/SDG-sandbox/issues/120 and https://github.com/SEMICeu/SDG-sandbox/issues/95 ) Germany has to differenciate a Bachelor of a University from a Bachelor in a Fachhochschule 
6. Academic Programme (Studiengang, Fachkombination)
7. Gender of Person see https://github.com/SEMICeu/SDG-sandbox/issues/105
8. Designation (Summa cum laude, etc)
9. specialisation - it might be important to indicate the specialisation of a student's study
10. multiple courses including the marks leading to the diploma (e.g. Mehr-Fach-Studiengängen  für alle Lehramtsbachelor Gymnasium/Gesamtschule but different grades (B.A. oder B.Sc.) regarding the combination of courses)
11. Link to the diploma supplement - see https://github.com/SEMICeu/SDG-sandbox/issues/126 

In some cases the cardinalities must be fixed:
1.  cardinalities between Diploma and issuingAuthority 1..* allowing for joint degrees (a diploma issued by two or even more higher education institutions, see https://www.dfhi-isfates.eu/de/ for a French-German example)
2. mandatory issuing place (there is no diploma without knowing from which Member State it was issued and if so it will not be recognisable 

This issue was found within the XHEIE German SDG data model "[call for comments](http://www.xhochschule.de/web/en/node/17#issuesDiplomaMissingAttributes)" amongst others by Universität des Saarlandes, Karlsruhe Institut of Technology (KIT), RWTH Aachen, Universität Mannheim, Hochschulen des Freistaates Sachsen
on the evidence diploma.

**Comment by cbahim** [comment]
@XHochschuleDE thanks for your comments 

- We have added the `thesisTitle` attribute with a `text` type as optional. 
- We have added `language` to all evidences as optional and `languageOfInstruction` as  optional to the _Tertiary education diploma supplement_.
- `qualificationLevel` is already present on the _Tertiary education diploma supplement_. The difference between a University bachelor degree and High-school bachelor degree should be capture in the code list. 
- We have added `academicProgramme` as mandatory to the _Tertiary education diploma_.
- We have added `gender` as optional to the _Tertiary education diploma_.
- We have added `levelOfDistinction`  as optional to the _Tertiary education diploma_.
- We have added `specialisation` as optional to the _Tertiary education diploma supplement_.
- The cardinality of `issuingAuthority` as well as `obtainedAt` has been changed to 1...* in all three evidences. 
- We have added `issuingPlace` as mandatory to all evidences.

**Comment by XHochschuleDE** [comment]
Thank you @cbahim , please do not forget diplomas issued by more than one institution. (Joint degrees)

**Comment by cbahim** [comment]
@XHochschuleDE Thanks for your comment! 

Indeed, we did not forget it. We have changed the cardinality of `obtainedAt` and `issuingAuthority` to [1..*] for all education-related evidences (except for the [completion of secondary education evidence](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/certificate_of_completion_of_secondary_education/data_model/certificate_of_completion_of_secondary_education_diagram_v0.14.png)).

New version of the diagrams and tables will be published Monday at the latest. 

Thanks again for your help.
