### ISSUE TITLE
Education Evidences: There is no unique Student.StudentIDNumber and no Person.Identifier in Germany

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#130]
The education (and other) evidences have a personID bound mandatory to the person.

Please note: There is no unique ID for Persons in Germany.
Not for pupils, not for students, not for people willing to get married for historical reasons. 
A debate has started to [use the fiscal ID](https://www.bmi.bund.de/SharedDocs/faqs/DE/themen/moderne-verwaltung/registermodernisierung/registermodernisierung-faq-liste.html;jsessionid=8CF356A4F15CE9051F8EB74DA5152C81.1_cid364#f14787382) but the debate is not finished.

Regarding student ID Number (Matrikelnummer): 
1. They are issued by Higher Education Institutions along different schemes and are not unique. 
2. Students being registered in two Universities will have two different student IDs. 
3. Higher Education Institutions in Europe may issue the same IDs twice. 
4. Student IDs cannot be used for the concept of life long learning. Student IDs are linked to aspects like student cards and the status of being a student meaning rabates and reducations on some spendings like museum entry fees and therefore often become obsolet when the users finishes his studies. 

However initiatives do exist in the educational sector to overcome this burden, but also here we have not reached the goal yet: 
https://ec.europa.eu/education/education-in-the-eu/european-student-card-initiative_en 
and https://www.myacademic-id.eu/ to name two of them.

**Recommendations are** 
a) to make the cardinality less binding [0..*]
b) to discuss together with EU OOP WP6 working on the subject "User Identification, Authentication & Record Matching" the German issue of not having person Identifiers for all the evidences
c) meanwhile to solve identification of persons in Germany (not only German persons) for the next - let's say - 5 years without a europewide unique person ID by submitting more personal data necessary: Gender, Place and Name of Birth, first Names, last names, current (structured) address (see https://github.com/SEMICeu/SDG-sandbox/issues/105)  and 
d) to make the following design considerations
d1 : an own "identifier" class with '"identifier scheme and validity and issuing agency and so on 
d2: to move the studentID as an attribute to the person class -> reasoning: documents are issued and remain with persons even if they change life events and 
d3: to delete the student class that currently only holds the studentID and then 
e) to focus on creating a register of all higher education institutions prior to creating "registers of students". (see here for a register of tertiary education https://www.eter-project.com/#/home) 

This issue was found within the XHEIE German SDG data model "[call for comments](http://www.xhochschule.de/web/en/node/17#issueNoUniquePersonIdenticator)" by ALL GERMAN Contributors
on all evidences.

**Comment by cbahim** [comment]
Thanks @XHochschuleDE for your comments. 
 
- We have relaxed the cardinality to [0..*] for `studentIDNumber` and `Person.identifier`
- We have added the issue of identifier to our agenda for next webinar
- We have added `gender` as well as `address` of `Person` as optional
- We will consider your design proposition with regards to `studentIDNumber`
