### ISSUE TITLE
Education Evidences in general: language of course missing

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#131]
The evidences do name a course or academic programme but they currently do not reveal in which language the course was given. But this is essential for recognition of diplomas and certificate of completions of secondary education issued from other Member States.

**Recommendation** is to add course language / language of academic programme to the `Course Result` class.

This issue was found within the XHEIE German SDG data model "[call for comments"](http://www.xhochschule.de/web/en/node/17#noCourseLanguageAttribute) amongst others by University of Erfurt, University Duisburg-Essen, Technical University Munich and Brandenburgische Technische Universität Cottbus-Senftenberg on the evidences certicate of completion of secondary education, diploma, diploma supplement and record of results.

**Comment by cbahim** [comment]
@XHochschuleDE thanks for your comments

- We have added `courseLanguage` as optional to the _Records of results evidence_.
- We have added `academicProgrammeLanguage` as optional to the _Tertiary education diploma supplement evidence_.

**Comment by akuckartz** [comment]
What about multilingual courses?

**Comment by XHochschuleDE** [comment]
> What about multilingual courses?

raised as own ticket here https://github.com/SEMICeu/SDG-sandbox/issues/144

**Comment by cbahim** [comment]
We'll make the attribute unbounded.
