### ISSUE TITLE
Education Evidence Diploma Supplement: individual course results should not be in the supplement

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#132]
Course results usually should have 
a) the name of course, 
b) ECTS credits achieved, 
c) marks, scaling system and 
d) qualification levels achieved
and other important individual performance information of a student.

However they are 
1) part  of the transcript of record (evidence called "Record of results of a given academic year" in the [Deloitte study](https://sdg.mindigital.gr/uploads/Deloitte_final_report.pdf)) and 
2) might be part of the diploma but 
3) are NOT part of the supplement:

The diploma supplement - the way it was defined by UNESCO, CoE and EC (https://github.com/SEMICeu/SDG-sandbox/issues/120) is meant to describe the course in general and its access requirements without looking at the students performance.

**Recommendation** is to delete the course results from the diploma supplement.

This issue was found within the XHEIE German SDG data model "[call for comments](http://www.xhochschule.de/web/en/node/17#issueCourseResultNotInDS)" amongst others by Technical University Munich, FSU Jena, HfM Dresden and Brandenburgische Technische Universität Cottbus-Senftenberg on the evidence diploma supplement.

**Comment by cbahim** [comment]
@XHochschuleDE Thanks for your comments. 

- `CourseResults` has been deleted from the _Tertiary education diploma supplement evidence_.
- We have added `courseCreditAmounts` to the _Records of results evidence_.
