### ISSUE TITLE
Education Evidence: Persons and Organisations should have structured address information as Core Location in addition to optional Geo-URI

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#133]
Location is used in different granularity on the same use cases for the same information (address of a higher education institution or of a student)

a) a mandatory Geographical-URI has to be used with the description without storing the adress of the student (the address where the diploma was sent to in non-digital form) (DIPLOMA)
b) a full adress in one text field is optional but no Country or county can be provided (record of results) not for the organisation not for the person (RECORD OF RESULTS)
c) no Location information is given at all (DIPLOMA SUPPLEMENT)
d) a location is given to the organisation with optional GeoURIs but not Location on the person (CERTIFICATE OF COMPLETION OF SECONDARY EDUCATION)

As stated in the issue https://github.com/SEMICeu/SDG-sandbox/issues/126 on different person classes for the same thing the issues here is the same with Location:
How can you explain to a Campus Management System developer that when exporting for the Once Only SDG-System 
a) a diploma with b) its supplement and c) the transcript of record of the same  person 
needs to be done with three different data models on the location.

![image](https://user-images.githubusercontent.com/72596288/95978422-746a6380-0e1a-11eb-9b35-b63afef2e1fb.png)
![image](https://user-images.githubusercontent.com/72596288/95978495-8c41e780-0e1a-11eb-9682-3dbe327ccf3e.png)
![image](https://user-images.githubusercontent.com/72596288/95978680-ca3f0b80-0e1a-11eb-9b7b-d51aa8a5ccca.png)

**Recommendation:**
Use for all four evidences the same Location Core Vocabulary including
a) optional Geo-URIs
b) mandatory AdminUnitLevel1 for the country
c) optional fullAddress as text
d) optional structured address including districtKey (Landkreis), Street with Streetnumber. ZipCode including optional AdminUnitLevel2

![image](https://user-images.githubusercontent.com/72596288/95978904-1db15980-0e1b-11eb-9cfa-1f649b4d0094.png)

**Comment by cbahim** [comment]
@XHochschuleDE thanks for the comments. 

> a) optional Geo-URIs
> b) mandatory AdminUnitLevel1 for the country
> c) optional fullAddress as text
> d) optional structured address including districtKey (Landkreis), Street with Streetnumber. ZipCode including optional AdminUnitLevel2

We have added `adminUnitLevel1` as mandatory and `adminUnitLevel2` as optional to all three evidences. `fullAddress ` is now optional in all three evidences. Finally, Geo-URIs are optional.

**Comment by XHochschuleDE** [comment]
Issue should be reopened:
>> d) optional structured address including districtKey (Landkreis), Street with Streetnumber. ZipCode including optional AdminUnitLevel2

current full address in combination with adminUnitLevel1 and 2 is not structured enough (Street? StreetNumber? Postcode?) and may lead to many non "once-only workloads" on recipents side: the address information is structured at the beginning of the process in all systems and should not be copied in to a full address text field for the sake of interoperability

This issue was found within the 2nd [German call for comments](http://www.xhochschule.de/web/sdg_comments_round2#issuesFullAddressNotStructured) by PRIMUSS Verbund of Technische Hochschule Ingolstadt
