### ISSUE TITLE
Education Evidences: mandatory familyName and givenName not always possible for students from outside Europe 

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#134]
Some Countries (e.g. Brasilia or India) do not have always both familyName and givenName for a Person.
What is the rule for the values to be provided in the currently mandatory fields? 
Can the cardinality be set to optional or should we agree on a common character ("-"?) to express the non-existance?

The [W3C](https://www.w3.org/International/questions/qa-personal-names.en) states regarding this aspect: 
_Similarly, don't require that people supply a family name. In cultures such as parts of Southern India, Malaysia and Indonesia, a large number of people have names that consist of a given name only, with no patronym. If you require family names, you may create significant problems in these cultures, as users enter garbage data like "." or "Mr." in the family name field just to escape the form._

This issue was found within the XHEIE German SDG data model "[call for comments](http://www.xhochschule.de/web/en/node/17#issueCountriesWithoutFamilyName)" amongst others by Technical University Munich, FSU Jena, and Tieraerztliche Hochschule Hannove on all education evidences

**Comment by cbahim** [comment]
Thanks @XHochschuleDE for your comment. 

We followed the rules stated by [eIDAS](https://ec.europa.eu/cefdigital/wiki/download/attachments/82773108/eidas_saml_attribute_profile_v1.0_2.pdf?version=1&modificationDate=1497252920317&api=v2). 

<img width="432" alt="eidas" src="https://user-images.githubusercontent.com/67376146/96999743-fc94eb00-1535-11eb-8cb6-a26f367b9e6d.PNG">

**Comment by cbahim** [comment]
Further information, as for our stance,  can be found in the following report https://ec.europa.eu/cefdigital/wiki/x/twLvEg
