### ISSUE TITLE
Education Evidences University Diploma academic qualification and overall grade not sufficient for multidiscipline studies including teaching positions (Lehramt)

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#135]
When studying for a teaching profession three information are at least required on the German diploma
1) one the grade or qualification level (Bachelor, Master) 
2) kind of a permit to teach at what kind of a school (Gymnasium, Gesamtschule, Haupt- und Realschulen, Grundschulen) 
3) the field of study (Specialisation) like English or Mathematics

Also other studies (combination of different disciplines) do exist with more than one discipline and consequently with more then one grade/mark.

Those different disciplines then should have their marks /grades documented not only an overall grade.

The current model suggest an `academic qualification` as text. What language do you suppose the Member States to fill in this academic qualification?

**Recommendations**:

a) Add for studies related to teaching profession the permit to teach at what kind of school (perhaps those [ISCED 2011 Levels](https://www.oecd.org/berlin/publikationen/Zuordnung%20nationaler%20Bildungsprogramme%20zur%20ISCED%202011.pdf) can be reused? )
b) use at least 3 different attributes to store the fields of studies, everyone with an own grade / mark
b1: International [ISCED 2013 Fields of studies](http://uis.unesco.org/sites/default/files/documents/international-standard-classification-of-education-fields-of-education-and-training-2013-detailed-field-descriptions-2015-en.pdf)  and 
b2: National Codelists ( e.G. in Germany the [Fächerschlüssel of DESTATIS](https://www.destatis.de/DE/Methoden/Klassifikationen/Bildung/studenten-pruefungsstatistik.pdf;jsessionid=8F33926A19171C19F218290A38518567.internet8711?__blob=publicationFile) AND
b3: two language variants of free text for qualification for those dynamic field of studies that are not in international of 2013 or yearly updated national list. Suggest for the free text variants to use British English and the national language as implied in SDG for the description of services.

Please note that currently there is no overall mapping between the German DESTATIS Fächerschlüssel and the international ISCED 2013. Some Higher Education Institutions provide individual [non machine-readable mappings](https://www.hu-berlin.de/de/studium/pservice/umrechnung/ects-tab/abschluss-note/2020/isced-codes), which gives a flavor of the mapping tasks that someone would have to do before we all benefit from a smooth recognition of diploma from abroad. 

This issue was found within the XHEIE German SDG data model "[call for comments](http://www.xhochschule.de/web/en/node/17#issueMultipleDisciplinesNotPossible)" amongst others by University Duisburg-Essen, Brandenburgische Technische Universität Cottbus-Senftenberg and Universität des Saarlandes on the evidence diploma supplement.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
