### ISSUE TITLE
Education evidences (diploma, diploma supplement, result record) - IT

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#136]
In the following I am reporting some comments we collected from our Ministry of Education and Ministry of University and Research. I will probably receive additional comments next Monday, they promised.

1) the diploma supplement is an attachment of the university diploma. We support a previous message from Germany, saying that the two models should be connected with each other. BTW: looking at the various diagrams, the previous suggestion to try to unify the models regarding educational evidences still applies, and our Ministry agreed on this point. All the four models share common modelling patterns and this will definitely help in harmonizing, for example, the different ways in which we treat the Location part of the modelling.

2) In Italy the education institutions can also be private but in any case the services they provide fall into the public sphere. I think that the proposed solution to use Organisation rather than Public Organisation is good.

3) The diploma supplement in Italy does contain the performance of the student. There was a previous issue about that from another country, likely Germany. So we support the model that for this evidence includes the performances

4) the grade in float does not make a lot of sense, especially in the University domain. 

5) the proposal to use the ISCED level is good

6) for personID and studentID. Our Ministry clarified that in the Student database they manage, the ID that uniquely identifies the student is the fiscal code (that, as also reported in previous Italian issues for previous evidences we use a lot across different authentic sources). The specific ID for students can indeed change over time and depends on the different universities. They also use another internal ID to identify students, but it is used only for internal purposes. 
The general issue they explained to us is that exchanging the fiscal code for student/person is not allowed in the current legislation scenario since the fiscal code is a personal data that identifies directly a person. Our data protection authority may raise some issues in the exchange of this type of data. I think this comment is general and does not apply only to the evidences pertaining the educational domain; we must consider this (probably not here in the modelling WP but as a general issue, I would say an important one since everything should be based on unique identifiers).

In addition to these comments coming from our Ministry, I also would suggest you to harmonize terminology. In the secondary completion evidence we finally used the term Learner. In all the three new evidences we use instead Student. I think that, going back to point 1 above, if we consider to merge all the four models, these situations can be easily dealt with.

**Comment by cbahim** [comment]
Thanks @giorgialodi for the comments already. 

> the diploma supplement is an attachment of the university diploma. We support a previous message from Germany, saying that the two models should be connected with each other. BTW: looking at the various diagrams, the previous suggestion to try to unify the models regarding educational evidences still applies, and our Ministry agreed on this point. All the four models share common modelling patterns and this will definitely help in harmonizing, for example, the different ways in which we treat the Location part of the modelling.

Indeed, we agree. An effort has been made to harmonise as well as to make the evidences complementary. This will be presented next Wednesday, during the 6th Webinar. 

> In Italy the education institutions can also be private but in any case the services they provide fall into the public sphere. I think that the proposed solution to use Organisation rather than Public Organisation is good.

We agreed. The change has been made (#125).

>The diploma supplement in Italy does contain the performance of the student. There was a previous issue about that from another country, likely Germany. So we support the model that for this evidence includes the performances. 

We agree and will add performances once the discussion on grades is sorted out. We will create a separate thread for that. 

> for personID and studentID. Our Ministry clarified that in the Student database they manage, the ID that uniquely identifies the student is the fiscal code (that, as also reported in previous Italian issues for previous evidences we use a lot across different authentic sources). The specific ID for students can indeed change over time and depends on the different universities. They also use another internal ID to identify students, but it is used only for internal purposes.
> The general issue they explained to us is that exchanging the fiscal code for student/person is not allowed in the current legislation scenario since the fiscal code is a personal data that identifies directly a person. Our data protection authority may raise some issues in the exchange of this type of data. I think this comment is general and does not apply only to the evidences pertaining the educational domain; we must consider this (probably not here in the modelling WP but as a general issue, I would say an important one since everything should be based on unique identifiers).

`Student ID number` redefined the ID of a `Person`, thus if you only provide that Student ID it's fine. With regards to your second point, we'll put it to the agenda of next week's webinar. 

> In addition to these comments coming from our Ministry, I also would suggest you to harmonize terminology. In the secondary completion evidence we finally used the term Learner. In all the three new evidences we use instead Student. I think that, going back to point 1 above, if we consider to merge all the four models, these situations can be easily dealt with.

We agree with harmonizing terminologies, however in that particular case a comment was made during the last webinar. [It was requested for the term ‘student’ to be replaced by ‘learner’, as ‘student’ is a term used for higher education](https://ec.europa.eu/cefdigital/wiki/x/XIcODw).
