### ISSUE TITLE
Question on social security evidence

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#137]
I saw that the social security evidence has been removed recently, is that correct? Is that because we are gonna follow the already existing model developed at the European level that you mentioned in the last webinar? 
If so, I think it could help to report it anyway in this repository, explaining the overall scenario for this evidence. What do you think about it?

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
