### ISSUE TITLE
main readme.md of the overall repository

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#138]
Probably it could be worth updating the main readme of the repository with the current new evidences (now there is the list of the first 5, only) and all the remaining ones organised according to the different phases of modelling we will encounter. What do you think about this? So people jumping in Github here can clearly understand where we are and the future plans.

**Comment by cbahim** [comment]
Thanks @giorgialodi for the comment. I've already updated the main readme, adding the current evidences with links. 

> So people jumping in Github here can clearly understand where we are and the future plans.

On that aspect, we'll try to enhance the readme to report on the steps being currently ongoing.
