### ISSUE TITLE
Feedback: Vehicle registration evidence (AT)

### ISSUE THREAD

**Issue by Carl-MarkusPiswangerAT** [SEMICeu/SDG-sandbox#140]
**1.	Do I agree with the proposed controlled vocabularies (code lists)?** 
We agree with the with most of the proposed vocabularies, but there are unclear terms e.g.:
•	Evidence.Registration Number: it is unclear if license plate number is meant
•	Evidence.certifies: certifies itself is an unclear term

**2.	 Do I agree with the proposed changes to the data models?**	
We are only familiar with the currently proposed version of the data models.

**3.	Are the entities and attributes definitions clear enough?**				
Please see answer to question 1. Most of the entities and attributes definitions are clear, in some cases further information is needed.

**4.	Does the modelling approach make sense?**
It highly depends on the purpose and specific use cases for the distribution of the evidence data between the member states (please also see: general questions and remarks).
If in the future an application for a vehicle registration or de-registration should be possible in a different member state (for which there is currently no EU law given), then all the data fields according to „Council Directive 1999/37/EC of 29 April 1999 on the registration documents for vehicles“ and complete vehicle data have to be provided.
In comparison to this, there are attributes missing in the data model, e.g.:
•	Vehicle category (J)
•	Color of the vehicle (R)
•	Type approval number
•	Type approval date
•	Certificate of Conformity, Date, issuer
•	CO2-Emission
•	Power

In addition, depending on the purpose we also need the following attributes in the data model:
•	Status: information if the vehicle is currently not registered, registered or de-registered
•	Issuing country: information about the country that issued the evidence

**5.	Do I agree with the proposed cardinalities (i.e. mandatory versus optional)?**	
It depends on the purpose for the distribution of the evidence data between the member states (please also see: general questions and remarks). If for registration or de-registration purpose, the cardinalities have to be aligned with „Council Directive 1999/37/EC of 29 April 1999 on the registration documents for vehicles.”

**6.	With data minimization in mind, should some of the entities and or attributes stripped off?** 
It depends on the purpose for the distribution of the evidence data between the member states (please also see: general questions and remarks).
Please see answer to question 4. For registration or de-registration purpose, the current data entities and attributes of the data model are not sufficient.

**7.	Will my country be able to provide all the mandatory information?** 
We will be able to provide most of the information, except of:
•	Evidence.vehicle legal user: term is unclear, registration holder has to be legal possessor
•	Agent.identifier: term is unclear
•	Location.address: term is unclear, location of vehicle in principle is main residence of user

**General questions and remarks regarding „REGULATION (EU) 2018/1724 OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL“ and the Vehicle Registration Document**

1)	Annex II of the regulation states the life event „moving“ and the procedure „Registering a motor vehicle originating from or already registered in a Member State, in standard procedures“. It is unclear what explicitly will be done with the exchanged data.
Is the provision of the data by the originating Member State sufficient for registering the vehicle in the new Member State (without additional steps)?

2)	Annex II of the regulation states „Proof of registration of a motor vehicle“ as expected output, without specifying if the vehicle registration document and the license number plates are meant. 
How shall the evidence and license number plates be provided to the user?
A postal delivery, according to Article 6 (c), entails a high fraud-risk, as well as massive efforts and costs, of which the responsibility is also subject for clarification. Due to the safety concerns, from our point of view, the postal delivery of the vehicle registration document and license number plates according to Article 6 (3) of the SDG Regulation is not possible.

3)	How shall payments be handled? What shall be done if the user has no possibility to pay online?

4)	Recital 27 of the regulation describes exceptions of the online procedure. It explicitly states the restriction to public safety, public health or the fight against abusive behavior. Although practical impossibility in some cases is admitted in the beginning, it then emphasizes that this is no reason for an exception, "provided that such evidence can be submitted in electronic format".
What is the expected process, if this is not the case?

5)	If "Registering a motor vehicle originating from or already registered in a Member State, in standard procedures" has to be done completely online, then:
a)	this also involves the de-registration procedure, since a vehicle cannot be registered in two Member States at the same time. 
What is the legal basis for the de-registration procedure and by which technical means shall a vehicle be de-registered in Member State that is not responsible?
b)	then there is no reason why it should not be possible to register other vehicles online. Thus, the entire registration procedure in general, for all vehicles (also to be clarified whether it is an additional and optional step), would have to be switched to an online procedure.
c)	who will bear the expected high costs for the implementation of the online-procedure?

6)	In AT, the registration of vehicles is carried out by the Joint institution of the insurers authorized to operate motor vehicle liability insurance (Verband der Versicherungsunternehmen,VVO) in accordance with Sections 40a, 40b KFG (Motor Vehicle Act). Accordingly, authorized facilities of the insurers have the capture the provided data in accordance with Section 40b (6) Z 2 KFG and save it in a central register (Section 47 (4a) KFG). 
The central register is therefore kept by Joint institution of the insurers authorized to operate motor vehicle liability insurance (Verband der Versicherungsunternehmen, VVO). Hence, technical implementations of any data model/data exchange/data capture/online procedures/changed processes as part of the procedure, therefore affect the VVO.

7)	If the vehicle registration document and license number plates are supposed to be physically picked up by the user from an authorized facility of the insurers, then an (additional or optional?) online-application or –procedure would be additional effort from a user-perspective, since this is not necessary at the moment.

**Comment by cbahim** [comment]
@Carl-MarkusPiswangerAT thanks for all your comments. 

1. `VehicleRegistrationEvidence.registrationNumber`'s definitionhas been clarified. We'll propose a better definition for `certifies`
2. • Vehicle category (J) - *We can propose to add this*
• Color of the vehicle (R) - *We can propose to add this*
• Type approval number - *Already in the model*
• Type approval date - *The date is not in the legislation, can you point us to it?*
• Certificate of Conformity, Date, issuer - *We didn't see that in the directive you shared. Does that correspond to the technical inspection in our model?*
• CO2-Emission - *Already in the model*
• Power - *Already in the model*
• Status: information if the vehicle is currently not registered, registered or de-registered - *Already in the model*
5. "If for registration or de-registration purpose, the cardinalities have to be aligned with „Council Directive 1999/37/EC of 29 April 1999 on the registration documents for vehicles." *The cardinalities were aligned at first, but based on some discussion happening in WP4 we relaxed the cardinality of certains attribute. We'll put that on the agenda for our next meeting.* 
7. "Evidence.vehicle legal user: term is unclear, registration holder has to be legal possessor". *The definition refers to [(C.3)](https://eur-lex.europa.eu/legal-content/en/ALL/?uri=CELEX%3A31999L0037) in the directive.* 
"Location.address: term is unclear, location of vehicle in principle is main residence of user" - *We nowhere mention that it relates to the vehicle but either to the `registered.Location` of the Agent or `placeOfBirth`*

Finally, with respect to your comment on **"General questions and remarks regarding "REGULATION (EU) 2018/1724 OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL" and the Vehicle Registration Document"**, we'll get back to you in a separate issue.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
