### ISSUE TITLE
Feedback: Secondary Education Completion Evidence (AT)

### ISSUE THREAD

**Issue by Carl-MarkusPiswangerAT** [SEMICeu/SDG-sandbox#141]
1.	Do I agree with the proposed controlled vocabularies (code lists)? 
There are no code lists used in the given data model.

2.	 Do I agree with the proposed changes to the data models?	
We are only familiar with the currently proposed version of the data model.

3.	Are the entities and attributes definitions clear enough?				
Yes, the entities and attributes definitions are clear enough.

4.	Does the modelling approach make sense?
Yes, the proposed entities and attributes themselves make sense, BUT a visual data model (e.g. diagram) has to be provided including the connections between die entities, in order to be evaluated.
 
5.	Do I agree with the proposed cardinalities (i.e. mandatory versus optional)?	
We agree with the proposed cardinalities, except of:
•	school year: currently optional; should be mandatory
•	final examination date: currently optional; should be mandatory

6.	With data minimisation in mind, should some of the entities and or attributes stripped off? 
The proposed entities and attributes represent the minimum set of data we need.

7.	Will my country be able to provide all the mandatory information? 
Currently only aggregated data is used and published, e.g. by Statisik Austria. 
At the moment there is no legal base for providing the information on a person/individual level and therefore a change of law („Bildungsdokumentationsgesetz“) is necessary. How shall we proceed here? 

In addition, the following attributes are not available: 
•	Student.student ID number: not available in the evidence data; systemintegration planned for 2020 (this will be a national ID)
•	Person.identifier: currently not available in the evidence data;
•	Location.geoprahic name: address data is only available as text-attributes street, zip code, city, state, district
•	Location.geographic identifier: not available in the evidence data

**Comment by cbahim** [comment]
Thanks @Carl-MarkusPiswangerAT for your comments. 

- On the use of code lists, we agree with your comment. Currently there is no code list. However, in an harmonization context, we will reuse the [ones we proposed already for the tertiary education related evidence](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/tertiary_education_diploma_evidence/data_model/tertiary_education_diploma_evidence_tables_v0.02.md), where it fits. 
- We will consider making school year and final examination mandatory providing that all MS can provide these attributes. 
- `Person.identifier` is currently optional, so it should not pose problems. However, `learnerIDNumber` is not. We will model this differently for it to be optional. Lastly, for `Location` we will base ourselves on[ our proposition for tertiary education related evidences](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/tertiary_education_diploma_evidence/data_model/tertiary_education_diploma_evidence_diagram_v0.02.png).
