### ISSUE TITLE
Education Evidences Errata - Missing complex types Period and Identifier in diagramme and tables

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#142]
The following complex data types are mentioned, but in contrast to other concepts, not defined further in the specification (table, diagramm).

1. Period e.g. in Academic Year in Record of Results Evidence
2. Identifier in Organisation.Identifier e.g. in Diploma 

This issue was found in the [2nd German call for comments ](http://www.xhochschule.de/web/sdg_comments_round2#issuesMissingDefinitions) by Universität des Saarlandes & Hochschule für Technik und Wirtschaft des Saarlandes and Technische Hochschule Ingolstadt Primuss-Verbund

**Comment by cbahim** [comment]
@XHochschuleDE further clarifications on the data types can be accessed [here](https://github.com/SEMICeu/SDG-sandbox/blob/master/technical_documentation/data_types.md). Let me know if this is still unclear to you.
