### ISSUE TITLE
Generic Question: Publications Office human-sex authority table value "Not Applicable" corresponding to "non-binary gender"?

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#143]
The gender / sex codelist from Publications Office
https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/human-sex/?target=Browse&uri=http://publications.europa.eu/resource/authority/human-sex

currently shows four different possibilities.

![image](https://user-images.githubusercontent.com/72596288/98119062-630df780-1eac-11eb-95b7-0a76f8290331.png)

In Germany we need to express "male, female, divers and unknown".

Can you please cross-check with Publications Office e.g. with @OP-EU-VOCABULARIES@publications.europa.eu  that the value "Not Applicable" is the correct term for mapping to the "legal recognition of non-binary gender". (see e.g. [wikipedia](https://en.wikipedia.org/wiki/Legal_recognition_of_non-binary_gender) for more information)

This issue was found in the [2nd German call for comments](http://www.xhochschule.de/web/sdg_comments_round2#issueNoDiversGender) organised by [XHochschule ](https://www.youtube.com/watch?v=RGzclgtpnWA) by Universität Greifswald and HIS eG

**Comment by EmidioStani** [comment]
I guess this would address the issue https://github.com/SEMICeu/Core-Person-Vocabulary/issues/7

**Comment by cbahim** [comment]
thanks @XHochschuleDE and @EmidioStani for your comments. We have picked up similar comments on that aspect.

For instance AT commented the following; 

>  As for the human sex code list, in AT there are the following values: „male“, „female“, „open“ [...] In case it is not possible to clearly distinguish between male and female, there are the values: „inter“ and „divers“. When no information is provided, the value is: „not specified“.

We will further investigate that matter and get back to you here.

**Comment by SebastianSK** [comment]
Meanwhile the code list was updated in December 2020 and now features "not stated".
Not sure whether this now maps to "divers".

![image](https://user-images.githubusercontent.com/3493618/115850294-0684a180-a426-11eb-83a8-3730af256025.png)

https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/human-sex

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
