### ISSUE TITLE
Education Evidences: academic programme language should reflect multilanguage courses

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#144]
1. In Tertiary Education Evidence `academic programme language` and 
2. in Course the `course language` 
has cardinality of `0..1` 
but should have `0..*` 
to reflect courses given in more than one language - as already done with `language of instruction`  in diploma supplement.

3. The semantics of programme language vs. language of instruction vs. course language is not sufficiently clear whereas the language of the evidence seems to be missing.

This issue was found by the University of Mannheim and Universität des Saarlandes and Hochschule für Technik und Wirtschaft des Saarlandes within the [2nd German call for comments](http://www.xhochschule.de/web/sdg_comments_round2#issuesMonoLingualCoursesOnly).

**Comment by cbahim** [comment]
Thanks @XHochschuleDE for your comment. Indeed, we will update the cardinality of `courseLanguage` to allow multilinguality. 

However, related to the language, we have the following attributes; 

- `TertiaryEducationEvidence.language`, with definition _"The language in which the Tertiary Education Evidence is issued."_	
- `TertiaryEducationDiplomaSupplementEvidence.academicProgrammeLanguage`, with definition _"The language in which the qualification was officially delivered and examined."_
- `TertiaryEducationDiplomaSupplementEvidence.languageOfInstruction`, with definition _"The different languages in which the programme was given."_
- `CourseResult.courseLanguage`, with definition _"Main language in which the course was taught."_

As far as we are concerned, the language of evidence is not missing. What would be your suggestion(s) to improve clarity? 👍
