### ISSUE TITLE
Education Evidences Record of Results: total number of semesters studied by student is missing for use case "apply for financing"

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#145]
SDG Annexe II quotes "Applying for a tertiary education study financing" as a use case.

For granting study financing in Germany (BAföG) it is important to know beside the financial capacity of the student and its parents and many other things also [how many semesters](https://www.mystipendium.de/bafoeg/foerderungshoechstdauer-bafoeg) the student already has studied in total (in German Hochschulsemester) in contrast to the semester he / she is currently subscribed to or he / she wants to change to (in German Fachsemester).

This information could be useful in the record of results evidence if this will be used in a "study financing application from abroad" SDG use case. Perhaps it is better to foresee an own "application for financing study" that then should be linked to the record of result evidence.

![image](https://user-images.githubusercontent.com/72596288/98210646-2a6c2d80-1f41-11eb-9b16-a7703c3bf9d8.png)
 

This issue was handed in by [XHochschule](https://www.youtube.com/watch?v=RGzclgtpnWA) but was found by the University of Mannheim in the [2nd German call for comments](http://www.xhochschule.de/web/sdg_comments_round2#issuesNoTotalAndCurrentSemesters)

**Comment by cbahim** [comment]
Thanks for your comment, @XHochschuleDE. We'll add `totalSemesters` with cardinality [0..1] and definition

> Number of 6-month periods the student already has studied in total 

to the record of results evidence. OK for you? @XHochschuleDE
