### ISSUE TITLE
Education Evidences: "access to regulated profession" and "access to further study" should be in diploma supplement also

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#146]
`access to regulated profession`
and
`access to further study`
currently are in the diploma evidence but should be **in addition** also be in the diploma supplement as
indicated here 
https://github.com/SEMICeu/SDG-sandbox/issues/120 as an requirement demanded by UNESCO, Council of Europe and European Commission template for diploma supplements
and as announced here 
https://github.com/SEMICeu/SDG-sandbox/issues/120#issuecomment-710040041

This issue was handed in by [XHochschule ](https://www.youtube.com/watch?v=RGzclgtpnWA) but was found by the University of Mannheim in the [2nd German call for comments](http://www.xhochschule.de/web/sdg_comments_round2#issuesAccessConditionsAlsoAreSupplements)

**Comment by cbahim** [comment]
Thanks @XHochschuleDE for your comment. We will duplicate these two attributes to the Tertiary Education Diploma Supplement Evidence.

**Comment by cbahim** [comment]
@XHochschuleDE thanks for your comment, we'll add the following attributes in the tertiary education diploma supplement evidence:

* `accessToFurtherStudy` [0..*]
* `accessToRegulatedProfession` [0..*]
