### ISSUE TITLE
Education Evidence Diploma "overall grade" not always exists

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#147]
The cardinality of `overall grade` in the diploma evidence currently is `1..1` but should be `0..*` to reflect two different issues:

a) (`0..`) studies (that do have particular grades of courses and also a status but) that do not indicate an overall grade. (perhaps status should be the mandatory thing but not be modelled inside the complex type `grade` ?)
b)( `..*`) studies with 
b1: multiple disciplines (Kombinations- bzw. Mehr-Fachstudiengänge) have multiple overall grades (Fachgesamtnoten) and 
b2: joint degrees issued from Higher Education Institutions such as the French-German University reflected in the [ISFATES](https://www.dfhi-isfates.eu/de/), so joint degrees issued by organisations laying in different EU Member States should indicate on the joint-diploma the non-joint :) overall grades separately by Member State. 

This issue was handed in by [XHochschule](https://www.youtube.com/watch?v=RGzclgtpnWA) but was found by the University of Mannheim and Universität des Saarlandes und der Hochschule für Technik und Wirtschaft des Saarlandes in the [2nd German call for comments](http://www.xhochschule.de/web/sdg_comments_round2#issuesNoOverallGradeInMannheim)

**Comment by cbahim** [comment]
Thanks for your comments @XHochschuleDE. You can propose (a) during the next webinar. In the meantime, we can make `overalGrade` optional and unbounded.
