### ISSUE TITLE
Tertiary Education Evidence: user centric "date of final exam" more important than issuer centric "date of issue" for SDG use cases for studying

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#149]
In the educational sector knowing when the diploma was issued by the organisation is fine but knowing when the last final exam was absolved by the learner is even better (for recognition and application for study financing). 

Suggestion: add an own `date of final exam` in the evidence or for a cleaner solution: 
group exam information that led to the diploma in an own class (date of last exam, perhaps also [type of assessment](https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/assessment/?target=Browse&uri=http://data.europa.eu/snb/assessment/25831c2) as done in EDCI)

This issue was handed in by [XHochschule](https://www.youtube.com/watch?v=RGzclgtpnWA) but was found by the University of Mannheim in the [2nd German call for comments](http://www.xhochschule.de/web/sdg_comments_round2#issuesdateOfFinalExamMissing) and by University of Kassel in the [1st German call for comments](http://www.xhochschule.de/web/node/17#issuesDateOfFinalExamMissing)

**Comment by cbahim** [comment]
Thanks for the suggestion, @XHochschuleDE. 

Concretely, we should have an `Exam` entity, with `dateOfFinalExam`, `dateOfLastExam` and `typeOfAssessment`. Can you tell me what the difference is between `dateOfFinalExam` and `dateOfLastExam`? What should be the cardinalities?

**Comment by cbahim** [comment]
@XHochschuleDE we would really appreciate your feedback on this 😊

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
