### ISSUE TITLE
[EXAMPLE] XSD's for Vehicle Owner/Holder data exchanged already in the EU based on COUNCIL REGULATION (EU) 2018/1541

### ISSUE THREAD

**Issue by roefie64** [SEMICeu/SDG-sandbox#15]
Here are the specifications and XSD's for exchanging vehicle owner/holder data used for investigating VAT fraud. It can be used to verify the vehicle registration evidence design against a pratical implementation. It does contains addresses in 2 ways: 1 as all separate fields like street, streetnumber, postcode, city and one as "Printable Address" lines. The first is used to store as structered data the second can be used for writing a letter or envelope in the right order. The same goes for the person/company name fields.

[XSD-VAT.zip](https://github.com/SEMICeu/SDG-sandbox/files/4931483/XSD-VAT.zip)
[EUCARIS XML Message Specification VAT.pdf](https://github.com/SEMICeu/SDG-sandbox/files/4931485/EUCARIS.XML.Message.Specification.VAT.pdf)

**Comment by cbahim** [comment]
@roefie64 thanks a lot for this! We will analyse them and report back either here or during the next webinar of WP4, on the 29th of July.

**Comment by cbahim** [comment]
After an analysis of the VAT XSD’s, we can conclude that there seem to be no major semantic differences between both models. Nevertheless, some additional classes/attributes can be found within the VAT XSD’s, for which we need input from the member states on whether or not they are required.
 
Classes/attributes with regards to mileage and odometer history.

Classes/attributes with regards to vehicle signal, i.e. the status of a vehicle or vehicle registration related circumstance or qualification, that normally emerged after registration of the vehicle. A signal/status may be temporary or definite. E.g. vehicle stolen, de-registered, exported, plates stolen, duplicate certificate, etc. For further discussion on this, see issue #16 
 Additional attributes for Vehicle:
- colour;
- category. Currently, EU legislation distinguishes about 100 different categories of vehicles. Most common categories are M1 for person’s cars, N1 for vans, L3e for motorcycles.
Please note that both attributes are optional as mentioned by the [Council Directive 1999/37/EC](https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A31999L0037) in Annex 1 - Part I - VI. - (J) and (R).
 
Additional dates:

- Start and end data for both the vehicle holder and owner
- First, start and end date for the Registration.

Definitions:

- VehicleHolder.StartDate [1..1]: Date of the registration to which the registration certificate refers, e.g. date at which the holdership starts.
- VehicleHolder.EndDate [0..1]: Last date at which holdership is in effect. Not applicable if the holder is the current holder. 
- VehicleOwner.StartDate [1..1]: Date at which ownership starts.
- VehicleOwner.EndDate [0..1]: Last date at which ownership is in effect. Not applicable if the owner is the current owner. 
- VehicleRegistration.FirstDate [0..1]: Date of first registration of the vehicle (somewhere in the world).
- VehicleRegistration:StartDate [0..1]: Start date of registration in the Member State.
- VehicleRegistration.EndDate [0..1]: End date of registration in the Member State. Is populated if the vehicle has been de-registered in the Member State.
 
Relevant definitions that can be reused:
- Vehicle holder: The natural person or legal person in whose name the vehicle is registered.
- Vehicle owner: Natural person or legal person that is the legal owner of the vehicle (i.e. the entity that has bought the vehicle, and has the right to sell it). [..] In many countries the owner of a vehicle is not specifically registered in the Vehicle Registration.
 
The last sentence raises the question whether the cardinality of vehicle owner should be changed to [0..1].
 
Finally, it would be useful if the usage notes refer to the Community Codes as in the [Council Directive 1999/37/EC](https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CONSLEG:1999L0037:20070101:EN:PDF) of 29 April 1999 on the registration documents for vehicles, e.g. (D.1) = Vehicle.make.

**Comment by cbahim** [comment]
Since no member states further commented on adding the above mentioned attributes, we will therefore leave them out of the model.
