### ISSUE TITLE
Education Evidences language text variants often disallowed by "..1" cardinality

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#151]
In the educational evidences for example a complex type "course" is defined that has a course name with [multilingual ](https://github.com/SEMICeu/SDG-sandbox/blob/master/technical_documentation/multilinguality.md)datatype text (good!) but disallowing multiple variants qua cardinality `1..1` -> I think having learned this long time ago from @makxdekkers that occurences of data type text should allow for multiple variants `..*` 

Please in general check the usage of `text `and the corresponding cardinalities in the (educational) evidences: 
also in `thesis title`, `programme learning outcomes`, `academic programme` only one attribut is allowed.

**Comment by cbahim** [comment]
@XHochschuleDE thanks for you comment. Indeed, we also picked up that remark in your review of WP4 first batch of models. 
We'll pay extra attention to attributes having `text` as data type to support multilinguality.

**Comment by XHochschuleDE** [comment]
@cbahim : The pickup did not yet go in the models :) I came across when testing the diploma evidence towards our conceptual xheie data model V0.3:

In the current model there still is:
Diploma Evidence
monolingual `AcademicProgramme` and `thesis title` despite being declared as potentially multilingual text
![image](https://user-images.githubusercontent.com/72596288/109263889-5ec36c80-7804-11eb-9a03-857f461e4429.png)
Diploma Supplement: p`rogramme learning outcomes` only allowed 0..1
course result: `course `being text but restricted to 1
