### ISSUE TITLE
Education Evidences Course complex type lacks of an ID

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#152]
In the educational evidences a complex type "`course`" is defined that lacks of possibilities to hold a courseID.
Courses (also referred to as modules in Higher Education Institutes) can not be referenced back in the source system of the evidence when only the name is present and no ID. 
Courses may keep the same `course name` but contentwise and/or access requirement-wise may change from academic period to academic period.

This issue was handed in by [XHochschule](https://www.youtube.com/watch?v=RGzclgtpnWA) but was found by Technical University of Munich in the [2nd German call for comments](http://www.xhochschule.de/web/sdg_comments_round2#issuesModulIDMissing)

**Comment by cbahim** [comment]
@XHochschuleDE thanks for your comment. Indeed, we will add `courseID` to `courseResult`

**Comment by XHochschuleDE** [comment]
Thank you @cbahim, 
Please note that the courseID is not yet shown in the diagram

https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/record_of_results_evidence/data_model/record_of_results_evidence_diagram_v0.03.png
