### ISSUE TITLE
Level of redundancy and denormalization in the data models

### ISSUE THREAD

**Issue by psiotwo** [SEMICeu/SDG-sandbox#153]
Birth Certificate data model considers Birth as an event, although it does not have specific attributes. On the other hand, the event of issuing the Birth Evidence is not reified. 

Depending on the required use-case of the model, I was wondering whether the Birth is of any value in the model (rewiring parent/child to the certificate seems to do the same job). 

Were You considering a more normalized data model for evidences? In particular, having a generic --> Evidence -> Issuance -> Event[attributes date, place].
- child.dateOfBirth would be rewired to Birth.date.
- placeOfBirth would be rewired to Birth.place 
Evidence would be linked to Issuance event and thus issuingDate and issuingPlace would be rewired to Issuance.date and Issuance.place respectively.

A partial reason for this might have been an aprior alignment of the data model with ISA Core vocabularies (that prescribe e.g. Person.birthDate as an attribute). If this is the reason, maybe direct reference to which elements are interpreted in which external vocabularies (e.g. ISA Core vocabularies), would be beneficial. 

Similar questions relate to the other evidence types;

![image](https://user-images.githubusercontent.com/1140626/98301795-a5722a00-1fbb-11eb-8f81-5800652c1109.png)

**Comment by cbahim** [comment]
Thanks for the proposition, @psiotwo. However, several member states reported not being able to provide the `sex` of the parents. How would you tackle this aspect in your re-modelling proposition? The same goes for `dateOfBirth`.

**Comment by psiotwo** [comment]
To answer Your question, I would need to know an answer to https://github.com/SEMICeu/SDG-sandbox/issues/157 first :-) .

The reason is that it depends on the goal of the data model which I am not sure about (maybe I missed it somewhere in the documentation). If the data models are "offerings" of possible attributes, then why not keep sex/dateOfBirth with zero min cardinality. An alternative for sex would be to move it to the Child class. For "dateOfBirth" I cannot see any problem - birth events typically won't be recorded for them.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
