### ISSUE TITLE
Contingent properties of the data classes

### ISSUE THREAD

**Issue by psiotwo** [SEMICeu/SDG-sandbox#154]
Additionally to to #153, multiple marriages are expected for a single person. Thus the fields familyNameAfterMarriage, familyNameBeforeMarriage, maritalStatusBeforeMarriage seem to be more properties of the person’s participation in the marriage than of the person herself. Having this in mind, either having them inside the Marriage class, or (more ontologically correctly) having them in a dedicated Qua object PersonParticipationInMarriage might help in data integrations.

**Comment by cbahim** [comment]
Thanks for your comment, @psiotwo. Allow me to ask, but in case of multiple marriages, we would have multiple evidences, correct? 
But I agree with your comment, which is why we modelled this evidence that way. 

> Thus the fields familyNameAfterMarriage, familyNameBeforeMarriage, maritalStatusBeforeMarriage seem to be more properties of the person’s participation in the marriage than of the person herself

Could you illustrate the following point? 

> having them in a dedicated Qua object PersonParticipationInMarriage might help in data integrations.

**Comment by psiotwo** [comment]
> Thanks for your comment, @psiotwo. Allow me to ask, but in case of multiple marriages, we would have multiple evidences, correct?

Since MarriedPerson inherits from Person, I can imagine that having two marriage certificates reflecting two different marriages of the same person would result in having e.g. two different properties for the `familyNameAfterMarriage` attribute (provided the two MarriedPerson instances will share their Identifier) that will not be distinguishable.

But I understand that maybe this scenario is beyond the scope of this data modeling initiative.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
