### ISSUE TITLE
Private universities vs. Public Organization mismatch

### ISSUE THREAD

**Issue by psiotwo** [SEMICeu/SDG-sandbox#155]
Secondary Education Completion Evidence mentions private universities as possible issuers of the Evidence. How do private universities (mentioned in the methodology doc) fit to this? Can they be considered PublicOrganizations?

**Comment by cbahim** [comment]
Thanks for your comment, @psiotwo. Can you point us to where we refer to private universities in the completion of secondary education evidence? 

It is true that we received a comment about not all `EducationInstitutions` and `issuingAuthorities` being Public Organisations (#125). We made the change accordingly in all [tertiary education related evidences](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/tertiary_education_diploma_evidence/data_model/tertiary_education_diploma_evidence_tables_v0.02.md#education-institution) but not in the secondary education completion evidence.

**Comment by psiotwo** [comment]
I am speaking about the description of Step 1.3

https://github.com/SEMICeu/SDG-sandbox/blob/4ebf35da80a013c909c68e890e5e56622c095fea/process_and_method/methodology/phase1.md#step-13-identify-the-competent-authorities

**Comment by cbahim** [comment]
Private universities can be related to the `organisation` class. All references to public organisations have been removed from our education related models.
