### ISSUE TITLE
VIN-based attributes consistency

### ISSUE THREAD

**Issue by psiotwo** [SEMICeu/SDG-sandbox#156]
For the Vehicle Registration Evidence, many attributes seem derivable from VIN (Make, Type) - were You considering this dependence/redundance?

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
