### ISSUE TITLE
Contract of the data models

### ISSUE THREAD

**Issue by psiotwo** [SEMICeu/SDG-sandbox#157]
According to the rule  “if at least three Member States request an attribute, the attribute is included”, 3 countries can agree on an attribute A, while 24 don’t. Thus A becomes an optional attribute, e.g. with cardinality 0..* . At this point as a data consumer, when I get the data with an attribute A, I am not sure why I am getting this particular attribute. So I can see several types of use of the data models:

1) Data models are complete data structures which describe all attributes all EU countries “can provide” when exchanging evidence data. Thus, all attributes that a country identifies for each evidence is part of the final data model (with cardinality 0). Those attributes which can be unified across countries will be unified, the other not. At this point, as a data consumer, I am sure that whenever I get data compliant with the data format, no matter which country it comes from, I can use the data model as a reference point for interpreting the evidence data.

2) Data models are minimal common data structures – only attributes shared across all countries will be listed (are there any such)

3) Data models are anything between 1 and 2 – here I would expect an explanation, why some attributes are listed and others are not, what are the guarrantees for data consumer about data completeness.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
