### ISSUE TITLE
Secondary education completion (NO): Reuse existing models

### ISSUE THREAD

**Issue by stigbd** [SEMICeu/SDG-sandbox#158]
### The evidence to which the issue applies
Secondary education completion
### The entity(ies) and / or attribute(s) to which the issue applies
The model itself
### The problem
There are a number of data models describing credentials from education, both standards and de facto standards. For Europe, two models are already in use for data exchange; ELMO and EDCI. ELMO is used within the EMREX and Erasmus Without Papers networks. EDCI is coming up as the standard for describing credentials for all levels of education.  The relation between ELMO and EDCI has been described.
### The possible solution
Use existing models

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
