### ISSUE TITLE
Person (NO): given name vs original name

### ISSUE THREAD

**Issue by stigbd** [SEMICeu/SDG-sandbox#159]
### The evidence to which the issue applies
Person
### The entity(ies) and / or attribute(s) to which the issue applies;
given name, family name
### The problem
NPR does only operate with official names i Norway which may hav been "adjusted" to an approved restricted character set within a "latin" subset. This means that original foreign names may not be reflected in NPR
### The possible solution
Introduce separate data-entity for "original name"

**Comment by cbahim** [comment]
Thanks for your comment @stigbd. See [my comment](https://github.com/SEMICeu/SDG-sandbox/issues/63#issuecomment-740734297) in issue #63
