### ISSUE TITLE
Jurisdiction (NO): NPR does not use the URIs 

### ISSUE THREAD

**Issue by stigbd** [SEMICeu/SDG-sandbox#160]
### The evidence to which the issue applies
Jurisdiction
### The entity(ies) and / or attribute(s) to which the issue applies;
id
### The problem
National Population Registry (NPR) does not use the URIs in question for (eg. https://op.europa.eu/en/web/eu-vocabularies/at-concept/-/resource/authority/country/ABW/).
### The possible solution
NPR may make a code-list with ISO-3166 alpha3 - URI

**Comment by cbahim** [comment]
Thanks @stigbd, we'll take the proposed solution into account. Note that currently `Jurisdiction` is not mandatory.
