### ISSUE TITLE
Location (NO): NPR does not operate with URI as location identifier type

### ISSUE THREAD

**Issue by stigbd** [SEMICeu/SDG-sandbox#161]
### The evidence to which the issue applies
Location
### The entity(ies) and / or attribute(s) to which the issue applies
geographicIdentifier
### The problem
NPR does not operate with URI as location identifier type
### The possible solution

**Comment by cbahim** [comment]
Thanks for your comment @stigbd, `geographicIdentifier` has been made optional across all evidence types models.
