### ISSUE TITLE
Marriage evidence (NO): The National Population Register (NPR) Does not operate with evidence identifier

### ISSUE THREAD

**Issue by stigbd** [SEMICeu/SDG-sandbox#162]
### The evidence to which the issue applies
MarriageEvidence
### The entity(ies) and / or attribute(s) to which the issue applies
identifier
### The problem
The National Population Register (NPR) Does not operate with evidence identifier
### The possible solution
NPR may generate and operate with unique ID for each formal evidence issued by NPR (birth, death, marriage/divorce.., family relation)

**Comment by cbahim** [comment]
Thanks for your comment, @stigbd. Following the SDG formal review, it was decided to make all evidence id's optional.
