### ISSUE TITLE
MarriedPerson (NO): The family name before marriage may not exist in NPR.

### ISSUE THREAD

**Issue by stigbd** [SEMICeu/SDG-sandbox#163]
### The evidence to which the issue applies
MarriedPerson
### The entity(ies) and / or attribute(s) to which the issue applies
familyNameBeforeMarriage
### The problem
The family name before marriage may not exist in NPR. See also #159

**Comment by cbahim** [comment]
Thanks @stigbd for your comment. In this situation, the `MarriedPerson.familyNameBeforeMarriage` is optional, so this should not pose a problem.
