### ISSUE TITLE
MarriedPerson (NO): The type "Code" does not contain any semantic meaning as a code-name

### ISSUE THREAD

**Issue by stigbd** [SEMICeu/SDG-sandbox#164]
### The evidence to which the issue applies
MarriedPerson
### The entity(ies) and / or attribute(s) to which the issue applies
maritalStatusBeforeMarriage
### The problem
The type "Code" does not contain any semantic meaning as a code-name. It is too general
### The possible solution
It should be named something in the genre of "MaritialStatusCode"

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
