### ISSUE TITLE
MarriedPerson (NO): The different codes does not appear to have unique codes

### ISSUE THREAD

**Issue by stigbd** [SEMICeu/SDG-sandbox#165]
### The evidence to which the issue applies
MarriedPerson
### The entity(ies) and / or attribute(s) to which the issue applies
maritalStatusBeforeMarriage
### The problem
The different codes does not appear to have unique codes, they seem to have the common code: NT1

**Comment by cbahim** [comment]
Thanks @stigbd for your comment. [If you click on a term of the code list](https://op.europa.eu/en/web/eu-vocabularies/th-concept/-/resource/eurovoc/74?uri=http://eurovoc.europa.eu/74), you'll be redirected on another [web page which provides more details](https://op.europa.eu/en/web/eu-vocabularies/th-concept/-/resource/eurovoc/74?uri=http://eurovoc.europa.eu/74) for the term in question and notably has a unique code for the term.
