### ISSUE TITLE
MarriageEvidence (NO): Generally the "evidence" does not give confidence in the information

### ISSUE THREAD

**Issue by stigbd** [SEMICeu/SDG-sandbox#166]
### The evidence to which the issue applies
MarriageEvidence
### The entity(ies) and / or attribute(s) to which the issue applies
familyName+givenName
### The problem
Generally the "evidence" does not give confidence in the information when the only two required instances of data is given name and family name. The "evidence" of marriage is that two people with those names got married, but the user of this may coincidentally have the same name.
### The possible solution

**Comment by cbahim** [comment]
Thanks for your comment, @stigbd. I'd invite you to look at [my comment](https://github.com/SEMICeu/SDG-sandbox/issues/63#issuecomment-740734297) in issue #63.
