### ISSUE TITLE
question on academic programme

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#167]
The definition of academic programme says that it is a set of course units. However it is a text and a single mandatory element. Do you mean here, as individuals of this property, something like "Bachelor in Computer Science"@en , "Corso di laurea in Informatica"@it, etc.?

**Comment by cbahim** [comment]
Thanks for your comment, @giorgialodi! 

As per the model, `academicProgramme` is a textual description of 

> The set of course units, the various components of which complement and build on each other in order to provide the student with a higher education qualification.

What you refer to is the `qualificationName`

> Full name of the qualification, at least in the original language(s) as it is styled in the original qualification, e.g. Master of Science, Kandidat nauk, Maîtrise, Diplom, etc.	

Therefore "Bachelor in Computer Science" (en) or "Corso di laurea in Informatica" (it) correspond to the `qualificationName`

Let us know if any improvement can be made.
