### ISSUE TITLE
"hasSupplement" property in tables with definitions

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#169]
In the diploma supplement and in records of results pages with the tables and all the definitions, for the class TertiaryEducationDiplomaEvidence the property hasSupplement is missing. It is only included in the tables with the definitions for the TertiaryEducationDiplomaEvidence

**Comment by cbahim** [comment]
@giorgialodi thanks for your comment. This is normal, it is replaced by `isSupplementOf` in the diploma supplement and record of results.
