### ISSUE TITLE
Data minimisation: Is the address relevant for VehicleRegistration evidence

### ISSUE THREAD

**Issue by roefie64** [SEMICeu/SDG-sandbox#17]
Do we need the address in the VehicleRegistration evidence? The vehicle is registered to a person or a company who has to identify  with a unique ID. It would be enough to know that the vehicle was indeed registered to this person/company where it's address is irrelevant.

**Comment by roefie64** [comment]
The same could be said about the persons/company name but this could be used to verify/doublecheck. Also the vehicle technical data is not relevant for the evidence but could be used to register the vehicle in the new country.

**Comment by cbahim** [comment]
As mentioned in issue #45,

In the data model provided by ES, 
- The location class is omitted (which is a redundant issue for all evidences)
- There is an additional relationship between Vehicle and Address. How Is this different from the Vehicle Holder address? Could other MS provide their views on that?

**Comment by cbahim** [comment]
We propose to remove the `Address` class and use the `address `attribute of the `Location `class. The attribute is a
single string with address information mandatory.  Such a field is available in Core Location (fullAddress, _The complete address written as a string, with or without formatting. Use of this property is recommended as it will not suffer any misunderstandings that might arise through the breaking up of an address into its component parts._)

**Comment by ibodor** [comment]
**Ingrid (FIN):** the address/location of the owner (and the holder/legal user) is present in the Finnish document. So the relationship in the Finnish data model is between person-address and not vehicle-address. Moving the address as an attribute of the Location class sounds reasonable.

**Comment by roefie64** [comment]
I still do not see the need for Location and Address in the Vehicle registration evidence. The evidence should be that an identified person (Agent in the data model) has registered an identified vehicle. I know that in many countries the address is registered at the Vehicle registration authority but is not kept up to date when a person moves within a country. Providing the registered address in the evidence might lead to problems when a person/organisation provides it's current address.

**Comment by cbahim** [comment]
@roefie64 and @ibodor thanks for your comments. Looking at them, we will propose the `registeredLocation` to be optional.
