### ISSUE TITLE
Location in Tertiary Education Evidence

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#171]
I think that we need to say that if the Location is specified at least the name of the location (geographic name) should be mandatory :)

**Comment by cbahim** [comment]
Thanks for your comment,  @giorgialodi! Currently Location related entities are aligned on the completion of secondary education evidence, in which `geographicName` is optional. Should we still proceed and make the attribute mandatory for Tertiary education related evidences?

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
