### ISSUE TITLE
Issue with the Identifier of Person in all diagrams - IT

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#172]
We included this comment for the official review of the first set of deliverables in WP4, but it also applies to the class Person used in the evidences of the second round. At the time being, with some non-uniform exceptions, a Person is identified uniquely through the given name, the family name and the date of birth (this latter property is not always mandatory). 
In Italy for instance we have many "Mario (given name) Rossi (family name)" and there are cases, especially for foreign people who come from countries where there is no civil registry and so no trusted data, where all these three properties may coincide even if they refer to actual different people. We believe it is important to consider a mandatory identifier that can be used to uniquely identify a Person.

**Comment by cbahim** [comment]
Thanks for your comment, @giorgialodi. I believe we have answered your comment our report titled Author's views, which can be accessed here: https://ec.europa.eu/cefdigital/wiki/x/twLvEg

> Person identification. For instance, concerning the tax declaration certificate. Some countries have their own Personal Identification number (e.g. TIN, etc.) where individuals can be identified but there is nothing in common at EU level. Identifying a person with certainty is almost impossible with the information presented. Italy further commented that without common identifiers, identifying a person is mission impossible (e.g. “Mario Rossi” is very common).

> _Proposed resolution: When person identifiers are available in a Member State, they should be used to identify a person. However, there are countries where such identifiers do not exist. In those cases, an alternative way to identify persons (via other input parameters) is therefore required._
