### ISSUE TITLE
Location and Address in certificate of completion of secondary education - IT

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#173]
We already included this message as a review comment for the first set of WP4 deliverables. We believe that the current modelling solution for Address in the specific evidence does not add anything. 
AdminLevel1 is the country (which is a Location) and adminLevel2 is the region (which is a Location). These are two components (AdminUnit/AddressComponent according to INSPIRE Address data model - https://inspire.ec.europa.eu/file/1728/download?token=K1Jh4B5h) of the address that is more than this. It includes also a street name, civic number and depends on the different ways the countries specify their addresses. 

Therefore, **our proposal** is the following:
either we add to the Address class the fullAddress property of Core Location Vocabulary, meaning that we are indeed modelling an Address or we do not specify the Address class, and we say that a PublicOrganisation hasRegisteredLocation 0..N.  meaning: 
`ex:PublicOrganisation1 sdgmodel:hasRegisteredLocation <http://publications.europa.eu/resource/authority/atu/ITA_RG_LOMB> , <http://publications.europa.eu/resource/authority/country/ITA> .`

BTW: also the EU Administrative territorial unit controlled vocabulary for Regions can be considered. There is also NUTS.

The same comment I mentioned in previous issues related to evidences of the second round, applies for the geographic name of the Location in this specific evidence.  In this model we need to specify a registeredLocation for the PublicOrganisation. At least a geographical name should be specified, from our point of view.

**Comment by cbahim** [comment]
Thanks for your comments @giorgialodi. I believed we've addressed them in our [updated version of the completion of secondary education evidence model.](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/certificate_of_completion_of_secondary_education/data_model/certificate_of_completion_of_secondary_education_tables_v0.02.md). Of course, we'll follow the same logic for all education related evidences.
