### ISSUE TITLE
Location and Address in Income Tax Declaration Evidence  - IT

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#174]
We already included this comment as a review comment for the first WP4 deliverables. 
It is not clear why we need to pass through a class Location to specify a domicile address of a person. The address property in Core Location Vocabulary has as domain rdfs:Resource and then can be used with domains that are not necessary locaions.
Therefore, **our proposal is the following**:

The Tax Payer has a domicile address that points to an address class directly. The address class can then include the fullAddress property and probably adminLevel1 and adminLevel2 properties too representing the country and the region of the address.

**Comment by cbahim** [comment]
@giorgialodi thanks for your comment. Good point, we'll simply remove `Location` and have the `domicile` pointing to `Address`
