### ISSUE TITLE
mandatory address property in Location for Vehicle registration evidence - IT

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#175]
We already included this comment as a review comment for WP4 deliverable. 
In the diagram of this evidence, in the Location we need to specify the address. Does it means that when we specify the place of birth of a person through a location we need to specify the address? I think that we must include here the geographical name and geographicl id properties to be used when we specify the place of birth of a person, for instance, and an optional property address that links location to address to be used in all those cases in which an address is required, for instance in order to indicate the registeredLocation of an agent (and BTW if we need to indicate the registeredLocation of an agent as an address we can directly use the property address of the Core Location Vocabulary and connect directly to the Address class, as reported in our previous comments).

**Comment by cbahim** [comment]
@giorgialodi thanks for your comment. Indeed, we also picked it up in our review of WP4 SDG review. We took good note of it and our proposition is indeed to align on tertiary education related evidences and propose the `geographicalName` and `geographicalID` as optional. We'll also align on the Core Location Vocabulary and have the `registeredLocation` pointing to the `Address`
