### ISSUE TITLE
Feedback: Absence of a Criminal Record Evidence (AT)

### ISSUE THREAD

**Issue by Carl-MarkusPiswangerAT** [SEMICeu/SDG-sandbox#176]
**Answer of data model core questions**

1.	Do I agree with the proposed controlled vocabularies (code lists)? 

There are no code lists in use in the data model. Will the ECRIS vocabulary be used?

2.	Do I agree with the proposed changes to the data models?	

We are only familiar with the currently proposed version of the data models.

3.	Are the entities and attributes definitions clear enough?				

Yes, the entities and attributes definitions are clear enough, **except of: The definition of the absence of a criminal record evidence currently is: Official document attesting whether there is a known record of a Person having been arrested in the past for committing a crime. In AT, the corresponding register does not hold the data of arrested persons, but of convicted people when the judgement is final.** 

4.	Does the modelling approach make sense?

No, since there a lot of aspects are not clear at the moment:
What will the business process look like?
What is the legal basis for this?

5.	Do I agree with the proposed cardinalities (i.e. mandatory versus optional)?	

No, legal and business aspects have to be clarified first.

6.	With data minimisation in mind, should some of the entities and or attributes stripped off? 

None of the entities and attributes of the data model should be stripped off. 
In addition, the following attributes are needed:
•	Person.academic title: as text

7.	Will my country be able to provide all the mandatory information? 

We will be able to provide most of the information, except of:
•	Evidence.identifier: is not available
•	Person.identifier: is not available
•	Location.geographic name: is available as plain text
•	Location.geographic identifier: is not available

**General questions and remarks**

1.	 Is there a paper-based exchange of evidence-data between member states currently in place?

2.	What happens if a member state provides data which has no equivalent in the data consuming MS (e.g. AT provides a value for gender which does not exist in NL?)

3.	For the exchange of criminal record data between member states ECRIS is already in use since 2012. Will there be an interaction between ECRIS and the new system? What will be the difference?

4.	In AT, there are different types of criminal record evidences. Beside the standard one, there are also specific types for:
a.	care and support
b.	child and youth care

5.	How shall the processing fees for the issuing of the evidence be handled? Which member state can claim which fees?

6.	Automated provision of evidence data shall only be granted when authorities of the member states or the user himself applies for it. The data shall not be provided to other institutions (e.g. banks, etc. ), since according to national law private companies or employers are not authorized to do so.

7.	From our experience the online issued absence of criminal record evidence is not recognized as an official document by some member states, due to the lack of a handwritten signature and seal. How will this topic be addressed?

8.	Our current system is based on a phonetic search on names. This search also includes former names (e.g. before marriage, alias names, etc.). If there is an inquiry to issue an evidence and the system finds multiple matches with similar names, then the automatic issuing of the evidence is stopped and the case has to be manually processed, including a proper identity check. The automatic processing is also stopped, if the subject/person is being searched for due to criminal proceedings against the person concerned or an arrest warrant.

**Comment by SebastianSK** [comment]
To my knowledge
1. Currently an "europäisches Führungszeugnis" is in place but not all Member States have implemented it:
German speaking information:
https://www.bundesjustizamt.de/DE/Themen/Buergerdienste/BZR/Inland/14.html
Legislation in Germany:
https://www.gesetze-im-internet.de/bzrg/__30b.html

The [Study ](https://sdg.mindigital.gr/uploads/Deloitte_final_report.pdf) in addition to EESSI (social security), Europass (education) and Eucaris (vehicle) mentions the European Criminal Records Information Exchange System (ECRIS) on page 36 as existing systems with data models that the SDG technical system does not aim to replace.

The European legal basis can be found here:
https://e-justice.europa.eu/content_criminal_records-95-en.do

![image](https://user-images.githubusercontent.com/3493618/99069091-00a0af80-25ae-11eb-8777-5b0f75b9abfb.png)

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
