### ISSUE TITLE
Feedback additiv to Issue 176: Criminal Record (AT)

### ISSUE THREAD

**Issue by Carl-MarkusPiswangerAT** [SEMICeu/SDG-sandbox#177]
additional 1: This evidence is highly sensitive information.

additional 2: We support all data minimisation strategies, and the removal of attributes if possible.

**Comment by anarosa-es** [comment]
We agree that this is highly sensitive informatiion.

The information about the subject is in the request of the evidence, so the response only need to say if such a person has or has not a criminal record. 

The response cannot provide other information about the subject than the one included in the request and the YES/NO answer about te absence.

**Comment by cbahim** [comment]
@anarosa-es, @Carl-MarkusPiswangerAT thank you both for your feedback. Currently, the absence of a criminal record evidence is modelled in a way that the response - beyond identification elements - includes only whether there is an absence of a criminal record. Let us know if further improvements are needed. Thanks!
