### ISSUE TITLE
Feedback: Tertiary Education Evidence (AT)

### ISSUE THREAD

**Issue by Carl-MarkusPiswangerAT** [SEMICeu/SDG-sandbox#178]
1.	Do I agree with the proposed controlled vocabularies (code lists)? 
We agree with the proposed vocabularies.

2.	 Do I agree with the proposed changes to the data models?	
We are only familiar with the currently proposed version of the data model.

3.	Are the entities and attributes definitions clear enough?				
Yes, the entities and attributes definitions are clear enough, except of:
•	Record of Results: here it is not clear which document it refers to

4.	Does the modelling approach make sense?
Yes, the modelling approach makes sense. Especially the links between the entities are important, otherwise there could be duplicates.
 
5.	Do I agree with the proposed cardinalities (i.e. mandatory versus optional)?	
We agree with the proposed cardinalities, except for the following attributes. These should be mandatory:
•	Tertiary Education Diploma Supplement Evidence.academic programme language
•	Tertiary Education Diploma Supplement Evidence.access requirement
•	Tertiary Education Diploma Supplement Evidence.main field of study
•	Tertiary Education Diploma Supplement Evidence.mode of study
•	Tertiary Education Diploma Supplement Evidence.programme learning outcomes
•	Tertiary Education Diploma Supplement Evidence.qualification level
•	Tertiary Education Diploma Supplement Evidence.study duration
•	Tertiary Education Diploma Supplement Evidence.total credits

6.	With data minimisation in mind, should some of the entities and or attributes stripped off? 
In general, we support all data minimisation strategies, and the removal of attributes if possible.

From an AT as data consumer perspective: The attribute language of instruction can be stripped off, since for us it is the same as academic programme language. All other proposed entities and attributes represent the minimum set of data we need.

7.	Will my country be able to provide all the mandatory information? 
We will be able to provide most of the information, except of:
•	Tertiary Education Diploma Evidence.access to further study: not available on the evidence, but available in the system
•	Tertiary Education Diploma Evidence.access to regulated profession
•	Tertiary Education Diploma Evidence.level of distinction
•	Tertiary Education Diploma Evidence.overall grade
•	Tertiary Education Diploma Evidence.thesis title: is not always available on the evidence
•	Tertiary Education Diploma Supplement Evidence.grade point average
•	Tertiary Education Diploma Supplement Evidence.language of instruction: is the same as academic programme language in our case
•	Location.geographic identifier: it is not clear, if this can be provided at the moment

General questions and remarks

1.	The entire list of attributes is available in the Campus Management System of over 70 educational institutions. Currently, only a subset of the data is transferred to the data network of the authorities. Is there an architectural plan of the new system how to retrieve the data from various sources?

2.	How do the business processes look like?

3.	What is the legal basis for the exchange of the tertiary education data, as it seems like it is only partly covered in the SDG regulation?

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
