### ISSUE TITLE
Domain ontology vs evidence common data model

### ISSUE THREAD

**Issue by anarosa-es** [SEMICeu/SDG-sandbox#179]
I was very surprised when I saw that **tertiary_education_diploma_evidence** and **tertiary_education_diploma_supplement_evidence** share the same data model. It they are considered two different evidences, then they cannot share the same data model.

However, I understand the concern that some evidence data models should be compatible with others because all of them belongs to the same domain.

The DE4A project has adopted a strategy that could work also here: create domain-specific ontologies from which evidence common data models are built.

So, SDG WP4 can develop an ontology for the education domain from which all the evidences related to that domain are built.

Besides, an evidence type should have a name according to its common data model and the design practice should consider the data minimization, so each evidence common data model  should consider only the minimal information required by the majority of the procedures. If the procedure needs more information, it can be provided by several evidences and this is a better approach that collecting information in only one evidence that is not needed.

Evidence is more than information because it is issued by a competent authority from an authentic source. Therefore its granularity it is not only set by the data minimization principle but also by how it is lawfully issued.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
