### ISSUE TITLE
Education Evidences language text variants often disallowed by "..1" cardinality

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#183]
In the current model there still is:
Diploma Evidence
monolingual `AcademicProgramme` and `thesis title` despite being declared as potentially multilingual text
![image](https://user-images.githubusercontent.com/72596288/109263889-5ec36c80-7804-11eb-9a03-857f461e4429.png)
Diploma Supplement: p`rogramme learning outcomes` only allowed 0..1
course result: `course `being text but restricted to 1

_Originally posted by @XHochschuleDE in https://github.com/SEMICeu/SDG-sandbox/issues/151#issuecomment-786444929_

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
