### ISSUE TITLE
Absence of a criminal record - definition

### ISSUE THREAD

**Issue by sethvanhooland** [SEMICeu/SDG-sandbox#184]
The definition of "Absence of a criminal record" currently states: official document attesting that there is no known record of a Person having been arrested in the past for committing a crime.

Shouldn't arrested be convicted, as noted by a WP7 colleague? An innocent person can be arrested and not convicted.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
