### ISSUE TITLE
Proposed resolutions for the Record of Results data model

### ISSUE THREAD

**Issue by cbahim** [SEMICeu/SDG-sandbox#185]
As presented during our tenth webinar, work package editors carried out a testing exercise with a subset of member states. For this exercise, volunteers were tasked to test the model against instance data and look at both the provider and consumer perspective. As a result, some comments were made on the potential flaws and blind spots of the current education credentials common data models. In the table below you can find a list of changes concerning the [record of results](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/record_of_results_evidence/data_model/records_of_results_evidence_tables.md) that will be applied to the model. Note that changes marked ‘quick fix’ will be made to the model regardless of the discussions on this thread. Changes marked as ‘proposal’ are up for discussion. If by the end of April 2021, no objections are made, work package editors shall proceed with the changes. 

|     Evidence               |     Attribute                  |     Issue                                               |     Solution                                                          |     Type         |
|----------------------------|--------------------------------|---------------------------------------------------------|-----------------------------------------------------------------------|------------------|
|     Record of Result       |     Course academic year              |     The definition isn’t clear enough                   |     Clarifiy the definition and clearly dissociate with the diploma supplement academic year            |     Quick fix    |
|     Record of Result       |     Total credits              |     Attribute is redundant with diploma   supplement    |     Remove the attribute                                              |     Proposal     |
|     Record of Result    |     N/A                        |     Course id is missing                                |     Add course id attribute                                           |     Proposal     |
|     Record of Result       |     Course academic period            |     The expected type isn’t appropriate                 |     Change to Period                                                  |     Quick fix    |
|     Record of Result       |     Course academic year       |     The definition isn’t clear enough                   |     Improve the definition                                            |     Quick fix    |
|     Record of Result       |     Course credit amount       |     N/A                                                 |     Align on [Europass Learning model](https://github.com/european-commission-europass/Europass-Learning-Model/blob/master/Learning%20Opportunities/Learning%20Opportunities.md#learning-specification) for the attribute   |     Quick fix    |
|     Record of Result       |     N/A  |     Course learning outcome is missing                  |     Add learning outcome attribute                                    |     Proposal     |
|     Record of Result       |     Academic year  |     Academic year is already present in the diploma supplement                  |     Remove the attribute                                    |     Proposal     |

**Comment by cbahim** [comment]
additionally, the definition of `record of result` has been simplified.  Further, the `course academic period` expects information related to e.g. semester, trimester, etc. Can a `period `type deliver this type of information?

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
