### ISSUE TITLE
Proposed resolutions for the Diploma Supplement data model 

### ISSUE THREAD

**Issue by cbahim** [SEMICeu/SDG-sandbox#186]
As presented during our tenth webinar, work package editors carried out a testing exercise with a subset of member states. For this exercise, volunteers were tasked to test the model against instance data and look at both the provider and consumer perspective. As a result, some comments were made on the potential flaws and blind spots of the current education credentials common data models. In the table below you can find a list of changes concerning the [diploma supplement](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/tertiary_education_diploma_evidence/data_model/tertiary_education_diploma_evidence_tables.md) that will be applied to the model. Note that changes marked ‘quick fix’ will be made to the model regardless of the discussions on this thread. Changes marked as ‘proposal’ are up for discussion. If by the end of April 2021, no objections are made, work package editors shall proceed with the changes.

|     Evidence           |     Attribute                         |     Issue                                                                                 |     Solution                                                          | Type | 
|------------------------|---------------------------------------|-------------------------------------------------------------------------------------------|-----------------------------------------------------------------------|----------|
|     Diploma Supplement         |     Academic programme language       |     The attribute is redundant with   language of evidence and language of instruction    |     Remove the attribute                                              | Proposal |
|     Diploma Supplement         |     Academic year                     |     The definition isn’t clear enough                                                     |     Specify that the attribute requires the   date of graduation      | Quick fix |
|     Diploma Supplement |     Academic year                     |     The expected type isn’t appropriate                                                   |     Change to Date                                                    | Quick fix |
|     Diploma Supplement |     Access to further study           |     Attribute is already present in the diploma                                                   |     Remove the attribute                                              | Proposal |
|     Diploma Supplement |     Access to regulated profession    |     Attribute is already present in the diploma                                             |     Remove the attribute                                              | Proposal |
|     Diploma Supplement |     Main field of study               |     There is no ISCED 2013 code list                                                      |     Refer to RAMON – ISCED Fields of   education and training         | Proposal |
|     Diploma Supplement |     Mode of study                     |     N/A                                                                                   |     Align on [Europass Learning model](https://github.com/european-commission-europass/Europass-Learning-Model/blob/master/Learning%20Opportunities/Learning%20Opportunities.md#learning-specification) for the attribute   | Quick fix |
|     Diploma Supplement |     Programme learning outcomes        |     N/A                                                                                   |    Align on [Europass Learning model](https://github.com/european-commission-europass/Europass-Learning-Model/blob/master/Learning%20Opportunities/Learning%20Opportunities.md#learning-specification) for the attribute    | Quick fix |
|     Diploma Supplement         |     Qualification level               |    Attribute is already present in the diploma                                                    |     Remove the attribute                                              | Proposal |
|     Diploma Supplement |     Total credits                     |     N/A                                                                                   |     Align on [Europass Learning model](https://github.com/european-commission-europass/Europass-Learning-Model/blob/master/Learning%20Opportunities/Learning%20Opportunities.md#learning-specification) for the attribute   | Quick fix |

**Comment by cbahim** [comment]
For efficiency reasons, the `academicYear` has been transformed into `awardingDate` as specified in the [Europass Learning Model](https://github.com/european-commission-europass/Europass-Learning-Model/blob/master/Qualifications/Qualifications.md#awarding-process). The definition has been aligned too.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
