### ISSUE TITLE
Proposed resolutions for the Diploma data model

### ISSUE THREAD

**Issue by cbahim** [SEMICeu/SDG-sandbox#187]
As presented during our tenth webinar, work package editors carried out a testing exercise with a subset of member states. For this exercise, volunteers were tasked to test the model against instance data and look at both the provider and consumer perspective. As a result, some comments were made on the potential flaws and blind spots of the current education credentials common data models. In the table below you can find a list of changes concerning the [diploma](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/tertiary_education_diploma_evidence/data_model/tertiary_education_diploma_evidence_tables.md) that will be applied to the model. Note that changes marked ‘quick fix’ will be made to the model regardless of the discussions on this thread. Changes marked as ‘proposal’ are up for discussion. If by the end of April 2021, no objections are made, work package editors shall proceed with the changes.

|     Evidence    |     Attribute                         |     Issue                                                                 |     Solution                                                                      |     Type         |
|-----------------|---------------------------------------|---------------------------------------------------------------------------|-----------------------------------------------------------------------------------|------------------|
|     Diploma     |     Academic programme                |     The definition isn’t clear enough                                     |     Improve the definition and clearly   differentiate from qualification name    |     Quick Fix    |
|     Diploma     |     Academic programme                |     There aren’t enough attributes to   identify an academic programme    |     Add the academic programme ID, and   academic programme description           |     Proposal     |
|     Diploma     |     Access to further study           |     The definition isn’t clear enough                                     |     Improve the definition and remove the   notion of ‘details’                   |     Proposal     |
|     Diploma     |     Access to further study           |     There is no ISCED 2013 code list                                      |     Refer to [RAMON – ISCED Fields of  education and training](https://ec.europa.eu/eurostat/ramon/nomenclatures/index.cfm?TargetUrl=LST_NOM_DTL_LINEAR&StrNom=CL_ISCED11&StrLanguageCode=EN&IntCurrentPage=2)                    |     Proposal     |
|     Diploma     |     Access to regulated profession    |     The expected data type poses problems   for automated processing      |     Propose a code list or remove the   attribute?                                |     Question     |
|     Diploma     |     Level of distinction              |     There is no match with national models   nor code lists               |     Remove the attribute                                                          |     Proposal     |
|     Diploma     |     Thesis title                      |     Should not be in the diploma                                          |     Move the attribute to the diploma   supplement                                |     Proposal     |
|     Diploma     |     Qualification level               |     Discrepancy as for what to propose as   code list ([EQF](https://europa.eu/europass/en/european-qualifications-framework-eqf) or ISCED)      |     N/A                                                                           |     Question     |

**Comment by GeraldGrootRoessink** [comment]
Three attributes start with "Access tot further.. ".  They are unexpected.  What I do expect are rules for admission for a study or a profession that include statements about previous work. But that is outside this model.

**Comment by GeraldGrootRoessink** [comment]
EQF has legal foundation in the EU. ISCED has not. EQF is approved on 23 april 2008 by the European Parliament to maken national qualifications more readable across Europe. Once national frameworks are referenced to the EQF all newly issued qualifications (e.g. certificates, diplomas, certificate supplements, diploma supplements), and/or qualifications databases should  contain a clear reference to the appropriate EQF and NQF level. It is used in Europass.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
