### ISSUE TITLE
Proposed resolutions for the education credentials related data model

### ISSUE THREAD

**Issue by cbahim** [SEMICeu/SDG-sandbox#188]
As presented during our tenth webinar, work package editors carried out a testing exercise with a subset of member states. For this exercise, volunteers were tasked to test the model against instance data and look at both the provider and consumer perspective. As a result, some comments were made on the potential flaws and blind spots of the current education credentials common data models. In the table below you can find a list of changes concerning the [diploma](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/tertiary_education_diploma_supplement_evidence/data_model/tertiary_education_diploma_supplement_evidence_tables.md), [diploma supplement](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/tertiary_education_diploma_evidence/data_model/tertiary_education_diploma_evidence_tables.md) and [record of results](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/record_of_results_evidence/data_model/records_of_results_evidence_tables.md) that will be applied to the models. Note that changes marked ‘quick fix’ will be made to the models regardless of the discussions on this thread. Changes marked as ‘proposal’ are up for discussion. If by the end of April 2021, no objections are made, work package editors shall proceed with the changes.

|     Evidence    |     Attribute                 |     Issue                                                                                                                                                     |     Solution                                                                       |     Type          |
|-----------------|-------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|-------------------|
|     All         |     All                       |     Allow multilingualism                                                                                                                                     |     All text-related attributes will have   an unbounded cardinality               |     Quick fix     |
|     All         |     Identifier                |     The identifiers provided might not be   unique                                                                                                            |     Specify in the usage notes that the   identifiers might not be unique          |     Quick fix     |
|     All         |     Identifier                |     The identifiers provided are national   identifiers                                                                                                       |     Specify in the usage notes that the   identifiers might be country-specific    |     Quick fix     |
|     All         |     Issuing place             |     Location of the education institution /   organisation is already captured. Besides, it might open the door to scoping   issue (e.g. which location, whether it's about where the evidence was issued, or else?)      |     Remove the attribute                                                           |     Proposal      |
|     All         |     Belongs to                |     The attribute should expect Person   instead of Student                                                                                                   |     Change the relation between evidence   and Student to Person                   |     Quick fix     |
|     All         |     N/A                       |     The licence of the education is not   captured                                                                                                            |     Add a licence related attribute                                                |     Proposal      |
|     All         |     Institution identifier    |     The definition isn’t clear enough                                                                                                                         |     Improve the definition and remove the   reference to ‘acronym’                 |     Quick fix     |
|     All         |     Person identifier         |     The definition isn’t clear enough                                                                                                                         |     Improve the definition and remove the   reference to ‘relation’                |     Quick fix     |
|     All         |     Admin unit level 2        |     The code list does allow non-European   issuer. The code list does allow for a precise   location, e.g. Berlin city, Berlin district, Berlin region    |     N/A                                                                            |     Question      |
|     All         |     Grade distribution    |     A text field hinders providing data,   besides the attribute has no match with national models    |     Remove the attribute                                                                                                                                      |     Proposal    |
|     All         |     N/A                   |     N/A                                                                                               |     Align on Europass learning model and   add assessment type, language of assessment, mode of assessment and method of   assessment                         |     Proposal    |
|     All         |     N/A                   |     Grading scheme is complex to implement                                                            |     Delete the attribute and add two   new   ones, e.g. minimum mark to pass and maximum mark (it can either be   alphabetical scales or numerical scales)    |     Proposal    |
|     All         |     Grade value           |     N/A                                                                                               |     Align on Europass learning model                                                                                                                          |     Proposal    |
|     All         |     Person registered address           |     Not needed & sensitive data                                                                                              |     Remove the attribute | Proposal |    
|     All         |    Sex          |     Not needed & sensitive data                                                                                              |     Remove the attribute | Proposal |

**Comment by SebastianSK** [comment]
The "German" concerns on Admin Unit Level 2 not being sufficienct were raised now directly at core location vocabulary review:
https://github.com/SEMICeu/Core-Location-Vocabulary/issues/12

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
