### ISSUE TITLE
Diploma supplement for all types of education

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [SEMICeu/SDG-sandbox#189]
There is at least one procedure that might need evidence from 1) secondary ,  2) vocational and 3) tertiary education, "enrolling in tertiary education". All kinds of diploma evidences can give access depending on the level, specific subjects and sometimes even grades .  So why is secondary separate and why is vocational missing? My suggestion:  combine the three.

As an example :  secondary education in the Netherlands  comes with a "cijferlijst" required by law. See https://wetten.overheid.nl/jci1.3:c:BWBR0024042&bijlage=3a&z=2021-02-17&g=2021-02-17. This includes subjects and various grades and is the most commonly used piece of evidence for this procedure.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
