### ISSUE TITLE
Use identifier in the person class instead of a "single-attribute class" student / learner

### ISSUE THREAD

**Issue by init-xbildung** [SEMICeu/SDG-sandbox#190]
`Learner `and `Student `class functionality currently is limited to hold a "learnerID" or "studentID" property.
Meanwhile the `person `class has also an identifier.

![image](https://user-images.githubusercontent.com/99474274/188852758-9454f733-fc46-4df4-b6b6-da7e9ec84978.png)

We recommend to use the identifier of the person class and to get rid of the redundant layer "learner" and "student"  

+++ This issues was raised by [HIS eg](https://www.his.de/) and [TU Braunschweig](https://www.tu-braunschweig.de/)
 within the [2022 XBildung Call for Comment on SDG Data models.](https://xbildung.de/web/SDG_call-for-comments_2022?HIS_TU_Use_identifier_in_person) +++

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
