### ISSUE TITLE
Strip property "sex/gender" from person class in secondary education completion evidence

### ISSUE THREAD

**Issue by init-xbildung** [SEMICeu/SDG-sandbox#192]
The deletion of `sex/gender` was mentioned here (https://github.com/SEMICeu/SDG-sandbox/issues/188) but was not done yet in the secondary education completion evidence. 

Even though the definition of gender in the Core Person 2.0 model [was changed](https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/2.00/Changelog_definitions.md), we recommend to delete the property "sex" from person class also in the secondary education completion evidence.
![image](https://user-images.githubusercontent.com/99474274/188854350-9ab20228-9700-4112-945d-ef9fd6080456.png)

![image](https://user-images.githubusercontent.com/99474274/188854384-26722a5f-8434-4a4e-803e-85d40c21582a.png)

+++ This issue was raised by [FH Aachen](https://www.fh-aachen.de/) and [HIS](https://www.his.de/) within the [2022 XBildung Call for Comment on SDG Data models.](https://xbildung.de/web/SDG_call-for-comments_2022?FHAACHEN_HIS_NO_GENDER) +++

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
