### ISSUE TITLE
Add foaf:homepage to education institution

### ISSUE THREAD

**Issue by init-xbildung** [SEMICeu/SDG-sandbox#193]
Several processes would benefit from information that usually can not be replicated in data exchange but that can be retrieved from webpages of the education instititution. 

In Public Organisation there is a `foaf:homepage`.  property for this purpose.

![image](https://user-images.githubusercontent.com/99474274/188854713-d1a29c85-0058-403c-ab53-0cf99c47e0cc.png)

The recommendation is to add a property that can contain a hyperlink to more information about the institution, such as the` foaf:homepage`

+++ This issues was raised by [HIS eg](https://www.his.de/)  within the [2022 XBildung Call for Comment on SDG Data models.](https://xbildung.de/web/SDG_call-for-comments_2022?HIS_foaf_homepage_education_institution) +++

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
