### ISSUE TITLE
Make registeredLocation mandatory and multiple in all education evidences

### ISSUE THREAD

**Issue by init-xbildung** [SEMICeu/SDG-sandbox#194]
`registeredLocation `is 0..1 in secondary education completion evidence and 0..* (https://github.com/SEMICeu/SDG-sandbox/issues/148)  in diploma and diploma supplement
The recommendation is to make the `registeredLocation `1..* to reflect a mininum of one registeredLocation should be present and to allow for several locations of a higher education institution or a school.

+++ This issues was raised by [HIS eg](https://www.his.de/) and [SfH](https://hochschulstart.de/startseite) within the [2022 XBildung Call for Comment on SDG Data models.](https://xbildung.de/web/SDG_call-for-comments_2022?HIS_TU_Use_identifier_in_person) +++

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
