### ISSUE TITLE
Add qualification level to secondary education evidence

### ISSUE THREAD

**Issue by init-xbildung** [SEMICeu/SDG-sandbox#195]
The secondary education evidence lacks of some important information, e.G. the qualification level (that is present in diploma).
In German school diploma the DQR/EQR information is [mandatory](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32017H0615(01)&from=EN). (EQR 4 is indicated).

![image](https://user-images.githubusercontent.com/99474274/188858278-1a47232e-117a-4895-9601-749bd3588b5a.png)

The recommendation is 
1) to include examples for `programmeNames `and 
2) to discuss be able to indicate the `main language` of several course languages and
4) most important to add the` qualification level` (NQR/EQR) that was achieved with the secondary education evidence.

+++ The requirement for qualifcation level in secondary education institution was also mentioned by the German Stiftung für Hochschulzulassung ([SfH](https://hochschulstart.de/startseite)) [HIS ](https://www.his.de/)and [FH Aachen](https://www.fh-aachen.de/) within the [2022 XBildung Call for Comment on SDG Data models.](https://xbildung.de/web/SDG_call-for-comments_2022?SFH_qualificationLevel) +++

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
