### ISSUE TITLE
Use NQR/EQR instead of ISCED2011L

### ISSUE THREAD

**Issue by init-xbildung** [SEMICeu/SDG-sandbox#196]
The tertiary education evidence includes information about the` qualifcation level `achieved. It therefore uses the 3-digit ISCED2011 Level.
More appropriate and sufficient seems to be the 1-digit DQR/EQR.  https://europa.eu/europass/de/compare-qualifications
The recommendation is to add EQF/NQF property to document the level of qualification. 
The EQF was mapped to national qualification frameworks in more than 30 countries.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
