### ISSUE TITLE
Streamline properties between secondary and tertiary education

### ISSUE THREAD

**Issue by init-xbildung** [SEMICeu/SDG-sandbox#197]
The classes `courseResult `and `courseGrade `highly differ in the properties they contain. Not always this seems to be intended.

Another aspect is that the information on courses without the course name seem not to be really useful.

The recommendation is 
a) to streamline the classes (e.g. heritage from a common super class `EducationCourseResult`  and 
b) to make `courseName `mandatory. 

Course Grade (secondary)
![image](https://user-images.githubusercontent.com/99474274/188860267-5748f04b-85db-4443-b456-2b0831b37a1a.png)

Course Grade (tertiary)
![image](https://user-images.githubusercontent.com/99474274/188860312-9ef96b55-24a0-4608-b3aa-4d82e870617d.png)

+++ The issue was raised by [SfH](https://hochschulstart.de/startseite) within the [2022 XBildung Call for Comment on SDG Data models.](https://xbildung.de/web/SDG_call-for-comments_2022?SFH_courseName) +++

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
