### ISSUE TITLE
[EXAMPLE] Birth certificate – birthDate

### ISSUE THREAD

**Issue by cbahim** [SEMICeu/SDG-sandbox#2]
In our country the birth date is always accompanied by the hour. Would it be possible to add it to the _expected datatype_ of the birthDate attribute?

**Comment by barthanssens** [comment]
Additional question, I assume this should also include the timezone ?

**Comment by cbahim** [comment]
@barthanssens thanks for your comment.  Time zone is indeed included in the syntax of ISO8601.
