### ISSUE TITLE
Birth certificate (and others): gender / controlled vocabulary

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#20]
The EU Publication Office has a controlled vocabulary 'Human Sex'.

(https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/human-sex/?target=Browse&uri=http://publications.europa.eu/resource/authority/human-sex)

So a few questions here:

- is this list complete ? (e.g. "X" ?)
- is there one agreed upon list for all EU Member States ?
- is it possible that, for other (future) types of evidence, there would be more options than the one for Birth Certificate (e.g. "encoding" for some reason change of gender/sex) ?

**Comment by dechden** [comment]
We are in the process of updating the human sex authority table (addition of "X").

**Comment by cbahim** [comment]
Thanks @barthanssens and @dechden the table mentioned is used as code list for the `sex` attribute of Person.
