### ISSUE TITLE
Tax declaration: clarify that income tax can be negative (= tax return)

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#21]
Perhaps specify that, in some cases, the income tax (monetary amount) can be negative (tax return)

One (rare ?) example in Belgium is the return of dividend tax: depending on the share, 15% - 30% of the dividend is already withheld by the bank "anonymously" (does not show up in the tax declaration / Tax department does not know about it)
 
A limited amount of this dividend tax can be refunded via the income tax declaration, even if one does not have another taxable or low income (i.e. a job as employee).
So the income tax can be negative (neglecting the dividend tax already paid via another channel)

**Comment by pfragkou** [comment]
It is a common case in countries like Greece, due to the fact that, a citizen of businnes should pay in advance a tax amount, i.e., before submitting the tax declaration. According to the amount of expenses and different tax classification categories, a tax return might take place.

**Comment by barthanssens** [comment]
@pfragkou that's similar to Belgium, though I assume that would probably still result in a positive number ? 
E.g if 10.000 EUR was paid upfront in the "normal" flow, but the tax agency returns 2.000 EUR, the net result would still be +8.000 EUR (and it is mentioned on the income tax declaration) Or should it indeed be -2.000 EUR ? To be clarified :-)

In the (rare) case mentioned above, it's also possible to have a tax return even when zero euro is paid in advance (because it's already taxed in another "tax flow", i.e. at the bank level... which does not show up on the final income tax declaration)

**Comment by pfragkou** [comment]
After the tax declaration is being proceesed, the result is always positive but there is an indication "amount to pay", or "amount to be returned/refound".

**Comment by cbahim** [comment]
@barthanssens, @pfragkou float can contain negative values, therefore it is deductible whether it is a refund (negative) or a payment due (positive). Nevertheless, it is still an open issue on how to define `incomeTax` (#68)
