### ISSUE TITLE
Generic question on dates / timezones

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#22]
Could be out of scope, and is probably obvious, but whenever a date / timestamp is provided, I assume the default timezone will be the local one, where the event happens, if no TZ is explicitly provided ?

I.e.:
- no TZ does not mean 'UTC' (nor UTC+1 / Brussels-Paris etc)
- no TZ does not mean the same TZ as the state capital (more specifically: birth certificate of someone born in French Guiana, no TZ means the TZ is actually UTC-03.00 , and not Paris/UTC+01:00  ?)

**Comment by sethvanhooland** [comment]
Would the PO have a best practice for this context @costezki ? And hopefully you don't mind I drag you into these discussions, your input is very much appreciated!

**Comment by costezki** [comment]
If there is a way to recover the TZ from another part of the description, then fine, functionality can be set in place to update/correct the TZ where it is missing (relevant fields with timestamp, time and dateTimes datatype). 

If the TZ information is not critical then I would rely on the fallback interpretation that then missing TZ is, in fact, the Coordinated Universal Time (or UTC). 

Without knowing the context of the project, I would go for the latter, unless the former is a necessity.

**Comment by pfragkou** [comment]
when a document is digitally signed, the information of the time zone is mentioned. See for example

![digital_signature](https://user-images.githubusercontent.com/55881299/96462676-1c6e9b00-1226-11eb-86da-b844dccbf515.jpg)

the same rational can be used here

**Comment by costezki** [comment]
The original question was about recovering the TZ in situations when the TZ is not explicitly mentioned. The case above shows that the TZ is available in the data.
