### ISSUE TITLE
Marriage certificate: is marital status required ?

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#23]
It looks like "marital status before marriage" is mandatory, is this really the case for cross-border exchange ? 
I'd suggest to make this optional

**Comment by sethvanhooland** [comment]
Interesting comment Bart. Hopefully we can reach out to domain experts from various MS to discuss the necessity of this attribute...

**Comment by ibodor** [comment]
**Ingrid (FIN):** agreeing with the suggestion to make it optional. In Finland it can be requested that the digital marriage certificate would contain previous marriages of the person in question (NOT the marital statuses prior to getting married) if the requestor chooses to do so.

**Comment by cbahim** [comment]
In view of the above, we propose to make the `maritalStatusBeforeMarriage` attribute optional.
