### ISSUE TITLE
Vehicle registration: power to weight ratio

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#24]
I don't think the power to weight ratio is required / part of the registration in Belgium, so I'd suggest to make this optional

**Comment by barthanssens** [comment]
In addition, assuming the mass and engine power are always known, I guess this attribute could simply be calculated if needed ?

**Comment by cbahim** [comment]
As mentioned by the [Council Directive 1999/37/EC](https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A31999L0037) in Annex 1 - Part I - V. - (Q), the power/weight ratio is only mandatory for motorcycles. We therefore concur with @barthanssens  proposal to make it optional.
