### ISSUE TITLE
Vehicle registration: add emission class / CO2 ?

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#26]
In Belgium the registration form also has 

- an emission or environmental class (which may or may not be known: for some vehicles this is not available, even for some cars after the year 2000), which should be on a controlled list
- CO2 emission / km (again, may not always be known, but typically a integer value which can also be 0)

**Comment by cbahim** [comment]
As mentioned by the [Council Directive 1999/37/EC](https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A31999L0037) in Annex 1 - Part I - VI. - (V.7) and (V.9), the CO2 (in g/km) and the indication of the environmental category of EC type-approval (reference to the version applicable pursuant to Directive 70/220/EEC(2) or Directive 88/77/EEC(3)) are optional.

**Comment by cbahim** [comment]
@barthanssens since no member states expressed the need to have this attribute, we propose not to add it to the model.
