### ISSUE TITLE
Vehicle registration: controlled list of fuel types ?

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#27]
Is there a EU list available of the possible fuel types ?

IIRC Belgium currently has a list of 15 fuel types:

- Gasoline
- Diesel
- (Gasoline +) LPG
- Diesel + LPG
- Electricity (only)
- Other
- Natural gas
- Gasoline + Natural gas
- Hydrogen
- Hybrid (Gasoline + El)
- Hybrid (Diesel + El)
- Hybrid (LPG + El)
- Hybrid (Hydrogen + El)
- Petroil mix (2-stroke) 
- Bio-ethanol

**Comment by sethvanhooland** [comment]
Dear @costezki would you know if someone from the Publications Office would know of an available controlled list on fuel types ?

**Comment by costezki** [comment]
To my knowledge, there is no such list on EU VOcabularies. It is, however, easy to request one provided that the codes, labels and related metadata (if any) are available. 

I suspect such a list should/might be already available in the petrochemical industry which can be used to bootstrap creation of such a controlled list. 

I'll provide the functional mailbox of EU Vocabularies team, shortly.

**Comment by sethvanhooland** [comment]
Great thanks @costezki !

**Comment by costezki** [comment]
Got it: OP-EU-VOCABULARIES@publications.europa.eu

**Comment by cecileguasch** [comment]
For this I contacted the MOVEHUB responsible. MOVEHUB is a MOVE interoperability project around transport.
