### ISSUE TITLE
Reuse "Regulation on Public Documents"

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#28]
Via https://twitter.com/emidiostani/status/1284180028616519681?s=20

The work on different certificates in Europe was already done with DG Justice, see the starting work here:
See https://github.com/EmidioStani/publicdocs

**Comment by sethvanhooland** [comment]
Thanks @EmidioStani for referring to the existing work on the Regulation of Public Documents. We are indeed re-using these data models within the context of the SDGR and discussed this with our colleagues from DG Justice.
