### ISSUE TITLE
Birth certificate:  Parent Two should be optional

### ISSUE THREAD

**Issue by guascce** [SEMICeu/SDG-sandbox#31]
Cardinality of parent two should be relaxed . May be Parent One as well to cater for Orphans
<xs:element name="parentTwo" type="PersonType" minOccurs="1" maxOccurs="1"/> to change to
<xs:element name="parentTwo" type="PersonType" minOccurs="0" maxOccurs="1"/>

**Comment by sethvanhooland** [comment]
Good comment Cécile, TBD next week!

**Comment by ibodor** [comment]
**Ingrid (FIN):** taking this idea further: personOne could be mandatory with a single mandatory element (string) e.g. familyName. In this case orphans would have only parentOne element with a single sub-element: familyName=Unknown. please consider also making parentTwo mandatory with a single mandatory element (to specify that it is too unknown), usually it is better to have some kind of indication about missing data than having null/non-existing elements, which often leaves room for (mis)interpretation.

Another thought: should we check if adoption - though typically documented in another evidence - modifies/adds data to birth certificates retroactively?

**Comment by cbahim** [comment]
Thanks for your comment Ingrid! 

> Another thought: should we check if adoption - though typically documented in another evidence - modifies/adds data to birth certificates retroactively?

To be discussed in the next [webinar](https://ec.europa.eu/cefdigital/wiki/pages/viewpage.action?pageId=252610385). What could potentially be the modified / added data, from your point of view?

**Comment by ibodor** [comment]
**Ingrid (FIN):** this is more of a speculation here: if there are MSs, where e.g. a child's father is marked as "Unknown" originally, the mother gets married and the husband adopts the child: does the original birth certificate get updated? or a "2nd version" gets issued? or the birth certificate never gets updated and the adoption is documented separately? What if the child's name is changed as part of the adoption (family but maybe given names, too)? So basically changes in data of the person itself and potentially also of the parents. Before the person (child) in questions gets his/her first ID card or passport, birth certificate may be the only  accepted document EU-wide showing personal data, I believe it would be beneficial to understand and document whether or not the birth certificate is a living document in MSs.

**Comment by cbahim** [comment]
@ibodor from our understanding, a birth certificate is _not_ a living document and cannot be updated retroactively. Please note that certificates of change of name exist.
