### ISSUE TITLE
Vehicule registration certificate: Location

### ISSUE THREAD

**Issue by cecileguasch** [SEMICeu/SDG-sandbox#34]
Location is also a concept defined in the INSPIRE catalogue.
https://inspire.ec.europa.eu/metadata-codelist/TopicCategory/location

**Comment by cbahim** [comment]
Thanks @cecileguasch for your comment! 

We are following the [ISA Core Location Vocabulary](https://www.w3.org/ns/locn), which is conformant to INSPIRE (if some considerations are taken into account). For more information see section 3.5.1 of the [specification](https://joinup.ec.europa.eu/solution/core-location-vocabulary/distribution/corevocabularies-locationv100specificationpdf).
