### ISSUE TITLE
Marriage certificate: Citizenship

### ISSUE THREAD

**Issue by cecileguasch** [SEMICeu/SDG-sandbox#35]
Would   https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/atu (Administrative territorial unit) be the appropriate controlled vocabulary for this code list.

**Comment by makxdekkers** [comment]
That vocabulary only includes "_the various administrative territorial units of the EU Member States_".  Marriages may involve persons with citizenship of countries outside of the EU.

**Comment by dechden** [comment]
We would suggest to use the _country_ authority table 
https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/country

**Comment by cecileguasch** [comment]
I agree

**Comment by ibodor** [comment]
**Ingrid (FIN):** please note, citizenship (of either of the parties) does not appear (not mandatory) in the digital marriage certificate issued by the competent Finnish authority.

**Comment by cbahim** [comment]
As mentioned in issue #38, ES does not record information on `citizenship`

>  we don't have in our marriage records information on the "citizenship", "capacityToMarry" or "maritalStatusBeforeMarriage" of persons

**Comment by cbahim** [comment]
As mentioned in issue #53, IT suggests to have the attribute `citizenship` **optional**. 

> Finally, citizenship is mandatory in this data model (unlike in the case of the birth certificate). We suggest to keep this property optional in the Person class.

For EL, the attribute is **mandatory**.

> Citizenship is also mandatory in Greece.

**Comment by barthanssens** [comment]
> That vocabulary only includes "_the various administrative territorial units of the EU Member States_". Marriages may involve persons with citizenship of countries outside of the EU.

Wondering if there is a common agreed upon list of countries en territories for EU Member States (in other words, do all the EU Member States recognize the same territories as being independent countries ?)

**Comment by cbahim** [comment]
@barthanssens in the `Jurisdiction` entity we refer to the [country table](https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/country/?target=Browse&uri=http://publications.europa.eu/resource/authority/country). In conclusion to this thread, the `citizenship` is optional, so it should not pose a problem.
