### ISSUE TITLE
Tax declaration: public organization label model

### ISSUE THREAD

**Issue by Bernardstanislas** [SEMICeu/SDG-sandbox#36]
- In France, we only have one issuing authority for all the income tax declaration certificates, called the fiscal administration
- The Public Organisation model might not entirely reflect all the rules described in the definition of the "preferred label" attribute:
  - if there is only on such name in any given language, maybe it would be useful to create a Public Organization Label model, as such:
    - a language attribute, of type string, [1..1] cardinality
    - a label attribute, of type string, [1..1] cardinality
    - then the Public Organization's preferred label attribute would have the Public Organization Label type, with a [1..*] cardinality
  - this suggestion is summarized in the following pull request: https://github.com/SEMICeu/SDG-sandbox/pull/32

**Comment by sethvanhooland** [comment]
Merci Bernard, we'll make sure to follow up on your comment!

**Comment by cbahim** [comment]
We propose to change the datatype of preferred label from *string* to *text*, as explained [here](https://github.com/SEMICeu/SDG-sandbox/blob/master/technical_documentation/data_types.md#text). This should have the same effect as your proposal @Bernardstanislas, without the need to introduce an additional class. For more information, we refer to the document on [multilinguality](https://github.com/SEMICeu/SDG-sandbox/blob/master/technical_documentation/multilinguality.md).
