### ISSUE TITLE
Marriage Certificate issues (ES)

### ISSUE THREAD

**Issue by anarosa-es** [SEMICeu/SDG-sandbox#38]
1. we think that "certificate" is something related only to documents. So we propose to use the word "**evidence**" instead which is the word used by the SDGR
2.  we think that the **issuing attributes** of an evidence should be present **independently of the evidence**
3. In our marriage evidences is essential to be **able to represent the registration data**, i.e., civil registry, volume and page of the marriage event registration
4.  **we don't have** in our marriage records information on the "**citizenship**", "**capacityToMarry**" or "**maritalStatusBeforeMarriage**" of persons
5. Marriage in Spain does not alter the familiy names, so **we don't have "familyNameAfterMarriage" nor "familyNameBeforeMarriage"**
6. as you know, we have 1st and 2nd family names that can be joint in a "family name" attribute, but for the legal validity of the data, we should be **able to specify the Spanish two family names as well**. Besides, it is important for our request to **distinguish if the person has not a 2nd famility name or it is just not specified**.
7. we **identify spouses by their identification number** either from their passport or from their Spanish/foreign national document
8. **we don't include** in our marriage evidences any **"address", but only the municipality or consulate**
9. we think that it is necessary to **model as well the input parameters for requesting a particular evidence**. This is important for data modelling and matching. 

Here you are the request and response data models of our current marriage data service. The common parts with other civil registry evidences are in yellow, and the request data model is common for any evidence of events registered in the Spanish Civil Registry:

![ES-marriage-evidence](https://user-images.githubusercontent.com/38435170/88385007-d97b6380-cdad-11ea-91e5-52e85905683f.PNG)

![ES-civil-registry-evidence-request](https://user-images.githubusercontent.com/38435170/88385017-df714480-cdad-11ea-8406-05bddb294d88.PNG)

**Comment by anarosa-es** [comment]
The marriage data model proposed by the COM mixes several evidences, according to the Regulation on Public Documents (Regulation 2016/1191) to simplify the circulation of certain public documents, which was adopted on 6 July 2016 and applies in all EU countries as from 16 February 2019. In the [Regulation Annexes for the multilingual standard forms](https://beta.e-justice.europa.eu/35981/EN/public_documents_forms), there are three different evidences for marriage (annex IV), capacity to marry  (annex V) and marital status  (annex VI).

**Comment by cbahim** [comment]
@anarosa-es thanks for your comments. 

- For your points (2), (3), (7), (9) see my answer in #37  
- Discussions related to the `citizenship`, `capacityToMarry `and `maritalStatusBeforeMarriage`, point (4), have been moved to #53 
- Discussions related to family names, points (5) and (6), have been moved to #61  
- Discussions related to the address, point (8), have been moved to #53
