### ISSUE TITLE
SK - General comments to the first 5 evidences

### ISSUE THREAD

**Issue by michal-o** [SEMICeu/SDG-sandbox#40]
1. Generally speaking, we would be able to provide the proposed "certificates". With little exceptions, the data contained in the models are stored in structured form and all but the vehicle data are available through data exchange platform.  If the specification of the data exchange through the OOP technical system will be based on predefined packages of data, we will generate them according the adopted standards. However, we will support the approaches fulfilling the need-to-know principle, allowing for requests and answers only providing the attributes needed by the service provider.

2. Note on identifiers: The problems of identity matching are generally known. Birth certificates are often used to certify the parent-child relation as the basis for representation. Especially for these cases, but probably also for other scenarios it deserves further analysis of the kinds of identifiers which are used in the certificates and make connection to the identification of the user via eIDAS.

3. We are still trying to verify with service providers if the proposed structures will satisfy their need for evidences, at least in the scope of services from the Annex II.

**Comment by sethvanhooland** [comment]
Thanks a lot Michal for providing a high-level feedback!  

1) Good to hear that the proposed approach and data model can be validated according to you, as it supports the exchange of data and the need-to-know principle. 

2) The point you raise in regards to identifiers is indeed an important ones and we need to discuss this aspect with our colleagues working on user ID and authentification.    

3) Thanks for continuing the effort and let us know when you receive more feedback. Do know that the proposed data models focus on the minimum obligatory attributes so any MS may add supplementary attributes if needed.

**Comment by janmicik** [comment]
I recommend that the name of the expected identifier should be clearly distinguished in the data models if differs. In data models are many times mentioned in the field attribute name **Identifier** despite it has different definitions / descriptions. it will help in the mapping of identifiers.

**Comment by roefie64** [comment]
I agree to the "the need-to-know principle"

**Comment by cbahim** [comment]
On the topic of the identifier you can find more information [here](https://github.com/SEMICeu/SDG-sandbox/blob/master/technical_documentation/data_types.md#identifier).
