### ISSUE TITLE
Completion of secondary education issues (ES)

### ISSUE THREAD

**Issue by anarosa-es** [SEMICeu/SDG-sandbox#42]
1. We assume that this is referred to the level 3 of the UNESCO ISCED 2011 classification.
2. We cannot provide the curseGrade.
3. We identify the course with many other attributes besides course name.
4. We identify the education institution by a code and the province where it is located.

In general, here you are other comments:
   

1.  we think that "certificate" is something related only to documents. So we propose to use the word "evidence" instead which is the word used by the SDGR
2.  we think that the issuing attributes of an evidence should be present independently of the evidence
3.  as you know, we have 1st and 2nd family names that can be joint in a "family name" attribute, but for the legal validity of the data, we should be able to specify the Spanish two family names as well
4.  we think that it is necessary to model as well the input parameters for requesting a particular evidence. This is important for data modelling and matching. Requesting an Spanish birth evidence by citizen.  We can request this data service either by the Spanish identification number of the student or by the name of the student (full name, given name, 1st famliy name and 2nd family name if exists) and his/her birth data (birth date, birth municipality and province).

**Comment by sethvanhooland** [comment]
Thank you Ana Rosa for the comments, both the generic ones and the related to the secondary education certificate - we can indeed discuss on the terminology (certificate vs evidence) on Wednesday

**Comment by SebastianSklarss** [comment]
+1 for point 4 as documented here https://github.com/SEMICeu/SDG-sandbox/issues/105 (Germany may need the gender and Name of Birth in addition to what was stated for Spanish Identification without ID)

**Comment by cbahim** [comment]
With regards to your specific comments:

> We assume that this is referred to the level 3 of the UNESCO ISCED 2011 classification.

This discussion will continue in #95.

> We cannot provide the curseGrade.

This is optional, so no problem there.

> We identify the course with many other attributes besides course name.

No other member state has expressed the need to include other attributes, so for now we will only keep the name.

>We identify the education institution by a code and the province where it is located.

 You can use the properties identifier and the registered location for the code and province respectively.
