### ISSUE TITLE
Certificate of completion of secondary education: helpful resources for data models/controlled vocabularies

### ISSUE THREAD

**Issue by OP-EU-Vocabularies** [SEMICeu/SDG-sandbox#44]
OP-EU-VOCABULARIES@publications.europa.eu contribution for the **Certificate of completion of secondary education**: helpful resources for data models/controlled vocabularies

### **Data models**

- Core Business Vocabulary (ISA)
- Core Person Vocabulary (ISA)
- Core Location Vocabulary
- Core Public Service Vocabulary

### **Controlled vocabularies**

- ESCO vocabularies (https://op.europa.eu/en/web/eu-vocabularies/esco)
- ISCED classification (http://uis.unesco.org/sites/default/files/documents/international-standard-classification-of-education-isced-2011-en.pdf, https://ec.europa.eu/eurostat/statistics-explained/index.php/International_Standard_Classification_of_Education_(ISCED)#ISCE)
- Eurothesaurus (European Information Network on International Relations and Area Studies (Einiras))
- UNBIS thesaurus (United Nations) (http://metadata.un.org/thesaurus/?lang=en)
- EuroVoc thesaurus (https://op.europa.eu/en/web/eu-vocabularies/th-top-concept-scheme/-/resource/eurovoc/100141?target=Browse)
- UNESCO thesaurus (http://vocabularies.unesco.org/browser/thesaurus/en/)
- TESE thesaurus (Eurydice) (https://data.europa.eu/euodp/fr/data/dataset/tese-the-thesaurus-for-education-systems-in-europe-2009-edition)
- ETT thesaurus (Cedefop) (https://www.cedefop.europa.eu/en/publications-and-resources/publications/4114)
- Europass authority tables (OP, EU Vocabularies)
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/accreditation/?target=Browse&uri=http://data.europa.eu/snb/accreditation/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/assessment/?target=Browse&uri=http://data.europa.eu/snb/assessment/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/com-channel/?target=Browse&uri=http://data.europa.eu/snb/com-channel/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/credential/?target=Browse&uri=http://data.europa.eu/snb/credential/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/education-credit/?target=Browse&uri=http://data.europa.eu/snb/education-credit/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/encoding/?target=Browse&uri=http://data.europa.eu/snb/encoding/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/entitlement/?target=Browse&uri=http://data.europa.eu/snb/entitlement/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/learning-activity/?target=Browse&uri=http://data.europa.eu/snb/learning-activity/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/supervision-verification/?target=Browse&uri=http://data.europa.eu/snb/supervision-verification/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/learning-assessment/?target=Browse&uri=http://data.europa.eu/snb/learning-assessment/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/learning-opportunity/?target=Browse&uri=http://data.europa.eu/snb/learning-opportunity/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/learning-schedule/?target=Browse&uri=http://data.europa.eu/snb/learning-schedule/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/learning-setting/?target=Browse&uri=http://data.europa.eu/snb/learning-setting/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/target-group/?target=Browse&uri=http://data.europa.eu/snb/target-group/25831c2
- https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/verification-status/?target=Browse&uri=http://data.europa.eu/snb/verification-status/25831c2
- corporate body authority table (https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/corporate-body)
- country authority table (https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/country)
- honorific authority table (https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/honorific/?target=Browse&uri=http://publications.europa.eu/resource/authority/honorific)
- human sex authority table (https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/human-sex/?target=Browse&uri=http://publications.europa.eu/resource/authority/human-sex)
- place authority table (https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/place)
- INSPIRE

**Comment by init-dcat-ap-de** [comment]
An important EU initiativedefining a semantic application profile based on W3C verifiable credentials is the data model Europass Learning Model governed by DG EMPL.
 
There some of the forementioned OP vocabularies are profiled together to define data exchange between students and the the recently launched Europass website https://europa.eu/europass/en 

More information on the model here:
https://github.com/european-commission-europass/Europass-Learning-Model

I suggest to consider aligning the modeling work on education certificates with the Europass initiative
