### ISSUE TITLE
Vehicle Registration Certificate issues (ES)

### ISSUE THREAD

**Issue by anarosa-es** [SEMICeu/SDG-sandbox#45]
General comments:

1. we think that "certificate" is something related only to documents. So we propose to use the word "evidence" instead which is the word used by the SDGR.
2. we think that the issuing attributes of an evidence should be present independently of the evidence
3. as you know, we have 1st and 2nd family names that can be joint in a "family name" attribute, but for the legal validity of the data, we should be able to specify the Spanish two family names as well. Besides, it is important for our request to distinguish if the person has not a 2nd famility name or it is just not specified.

Specific comments:

1. we are commenting this evidence in regards to **our data service on vehicle data regarding to one of its owners**
1. we provide the data of a vehicle **owned by a natural person** (the subject of the request with a Spanish ID number) **and with a certain vehicle identifier** (nive, chassis number or plate number)
2. we don't provide information on persons related to the vehicle but **the owner who has requested the evidence**
3. we sometimes provide "full-locator" for legacy puposes as a composition of locator-designator+locator-name+loc-number-type+loc-number 
4. **we provide other attributes** as gases emission level or if the vehicle is temporary or definetively deregistered and more information on the vehicle technical inspection, etc.
`there is much infomation registered regarding a vehicle, so we need to understand what is intended to be proved by this evidence in order to identify the appropiate attributes`

Here you are the request and response data models of our current data service on vehicle data:

![vehicle-registration-evidence](https://user-images.githubusercontent.com/38435170/88549292-66c5ee80-d020-11ea-908f-5f0a04fc875a.PNG)

![vehicle-registration-request](https://user-images.githubusercontent.com/38435170/88549302-69284880-d020-11ea-9005-6ae5e5240088.PNG)

**Comment by cbahim** [comment]
@anarosa-es thanks for all your comments. 

Regarding the general comments (1) and (2), we will create a separate issue. Concerning your third point, please see issue #63. 

Regarding the specific points:
(1), (2), (3) and (4): thank you for the information;
(5) currently the technical Vehicle attributes are limited to those that are mentioned as mandatory by the [Council Directive 1999/37/EC](https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A31999L0037) in Annex 1. Regarding the registration status and emission attributes, please also see issues [#16](https://github.com/SEMICeu/SDG-sandbox/issues/16) and [#26](https://github.com/SEMICeu/SDG-sandbox/issues/26).

Regarding the provided data model, there seem to be no major semantic differences, except:
- The owner is a relation (attribute) of the Vehicle not the Vehicle Registration. We move this discussion to issue #74
- Multiple registration dates: see issue #73 
- The omittance of the Location class. We move this discussion to issue #17
- The additional relationship between Vehicle and Address. Is this different from the Vehicle Holder address? We move this discussion to issue #17 

Regarding your question on the intended goal of this evidence, we can mention that this evidence relates to the following two procedures of the SDG:

- Registering a motor vehicle originating from or already registered in a Member State, in standard procedures
- Obtaining emission stickers issued by a public body or institution
