### ISSUE TITLE
General suggestions made by OP EU Vocabularies 

### ISSUE THREAD

**Issue by OP-EU-Vocabularies** [SEMICeu/SDG-sandbox#49]
OP EU Vocabularies would suggest to:

-	build data models in VocBench (a web-based, multilingual, collaborative development platform for managing OWL ontologies, SKOS(/XL) thesauri, Ontolex-lemon lexicons and generic RDF dataset) http://vocbench.uniroma2.it/

-	our knowledge and expertise in data modelling : please contact OP-DATA-MODELLING@publications.europa.eu 

-	create mappings between attributes contained in various ontologies.

**Comment by dechden** [comment]
The OP Data Modeling team can be reached at: OP-DATA-MODELLING@publications.europa.eu (please add OP-EU-VOCABULARIES@publications.europa.eu in CC).
