### ISSUE TITLE
Birth Certificate issues (IT)

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#50]
1) The Birth certificate is indeed an evidence, as highlighted by Spain in issue #37. However, if we talk here about a certificate (in Italy we distinguish the certificate from other types of documents that can also be considered as evidences, such as the ”birth act” and the ”extract of the birth act” it would be better to keep the term BirthCertificate but specifying that is a subclass of Evidence of the CCEV. In this way, we can also represent whether it is a document or structured data, according to CCEV’s specifications.
2) The concept of Birth is not clear. Is it a life event (as defined in CPSV-AP)? Why did you choose this type of modeling? In the birth certificate in Italy, what counts is to demonstrate the birth of a person (the child). Why do not you consider to have something like BirthCertificate certifiesBirthOf Person (mandatory property of BirthCertificate). In this way, we are obliged to enter the data on the born person available on the certificate. Since in Italy the parents are not necessarily available in the birth certificate (and indeed you indicated 0..1 as cardinality for these two properties) you could manage, in case, a parental relationship from Person to Person (in this case the parental relationship is “child of”). The parental relationship is something provided for by the Italian law and that we store it in our civil registry. It could also be very important in specific cases (e.g., just to cite an example, the parental relationships were strategic in COVID-19 lockdown period).
This possible modeling method could simplify some data queries.
3) We also agree with Spain on another point of their issue #37: the presence of the concept Address. Probably there is no need for the Address concept; rather it is enough Location. In fact, it is not clear why Location has only a mandatory property named “address” used to represent two address components (to use INSPIRE’s terminology): city (post name) and country (admin unit level 1).
We suggest to keep Location only in order to represent both a country and a city. The definition of Location is “A spatial region or named place” which is general enough to capture the concepts of city and country. BTW: all the properties with range location have multiple cardinality; therefore, even this solution (without address) would be good to represent both country and city.
4) Finally, we agree with Spain that some input parameters may be required in order to obtain the birth certificate (e.g., identity card). It is probably better to consider these aspects as well.

**Comment by cbahim** [comment]
Thanks @giorgialodi for you comments. 

We redirect you to issue #37, where we answered points (1), (3) and (4). As for point (2), would the following be a better definition of `Birth`? 

> The event indicating the moment a person emerges from the body of another person (start of life).

In the definition above, notions of child, parents, etc. have been removed because they can then be defined separately from the definition of birth, but also because they have a biological meaning and a legal meaning. This raises the question whether a clarification on the child-parents relationship interpretation (e.g. legal, biological, etc.) is needed?

Additionally, if I understand correctly you propose to remove the notion of birth and have a direct relation from the birth certificate to a Person and make the information about the birth attributes of the person – e.g. the date and place of birth and the relationships about the person’s parents can be modelled as attributes of the person. Do other member states agree on the approach?

**Comment by giorgialodi** [comment]
hi @cbahim, the so-called "parental relationships" have also a legal characterization in our context, not only biological.  In any case, I noticed that the modelling proposal was not accepted. Fine. However, I would like to raise your attention that I am not fully sure that the current model allows us to certify the date of birth (and place of birth). In this sense, the Spanish model in issue #37 seems to me highlighting better this aspect. The current model you propose certifies the birth of a child (with possibly parent 1 and parent 2 useful for those member states including this information in the evidence), but I do not see how it can certify the date of birth and place of birth since these are attributes of a person, not of the event being certified. Said in another way, with this model I would have expected to see that a BirthEvidence certifies Birth (of a child with parent 1 and parent 2) occuringIn Place and happeningAt Date. Not sure if I was able to let you understand what I mean :)

BTW: what we want to certify? Which is the minimum set of information we want to certify with the Birth Evidence, considering all the possible cases of Member States reacting to this work?

What do you think about this?

**Comment by giorgialodi** [comment]
Ah, I forget, in the marriage evidence, you indeed certify the marriage date and place because you included these properties in the marriage event being certified by the evidence. So in the case of Birth, you do not want to certify the date of birth and place of birth, correct?

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
