### ISSUE TITLE
Marriage certificate: Location and Address

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#53]
1) Also in this case, we report the same considerations as in issue #50 for location/address and input parameters that may be required in some cases.  Moreover, is marriage another life event  as in the case of Birth? If yes, we report the same suggestions of issue #50 with the introduction of the "spouse of" relationship between Person and Person. 
2) Looking at the Italian law modified in 2013, it seems that when getting married, spouses can choose whether to keep their surname or use a marital surname. In light of this, it is probably not appropriate to include the "family surname after/before marriage" as compulsory properties. 
3) It is unclear why 'marital status before marriage' is a mandatory property for the purposes of modeling marriage certificate The same applies to the 'capacity to marry'.  We suggest to relax the cardinality of these properties, leaving them optional in case some countries use them
4) Finally, citizenship is mandatory in this data model (unlike in the case of the birth certificate). We suggest to keep this property optional in the Person class. 

In Italy the marriage certificate only serves to prove that the marriage took place between two people in a certain place and date.

**Comment by pfragkou** [comment]
1. In greece regarding spouse last name, due to different laws over the year we keep the familly surname. According to the current law, the wife keeps her familly surname after the wedding (she doesn't take her husband's). It is not under her preferrence/choose to keep it or choose her husband's. 
2. Citizenship is also mandatory in Greece.

**Comment by ibodor** [comment]
**Ingrid (FIN):** 

- supporting the idea of making citizenship optional as it is not shown in the digital certificate issued in Finland for any of the parties. 

- about location: Public Organization / identifier is not shown in the Finnish certificate. Suggesting that Location and Address elements would be optional as the location/place where the marriage was actually registered are also not shown/available.

**Comment by cbahim** [comment]
Thanks @giorgialodi , @pfragkou  and @ibodor for your comments. 

- discussions about surnames and marital surnames will now take place in a dedicated issue thread (#61)

- discussions about `maritalStatusBeforeMarriage` should take place in issue (#41) 

- discussions about `citizenship` should take place in issue (#35)

This thread will now essentially focus on `Location `and `Address`

**Comment by cbahim** [comment]
As mentioned in issue #38, for ES, `Address` doesn't have the same attributes [as in the data model](https://github.com/SEMICeu/SDG-sandbox/tree/master/evidences/marriage_certificate/data_model) proposed. 

> we don't include in our marriage evidences any "address", but only the municipality or consulate
