### ISSUE TITLE
Data minimization + datatype: Secondary education: grade

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#54]
Should grade be a mandatory attribute ?

Moreover, it is currently defined as a float, but what would the range be ? Is it a percentage, or a score on 10 points ? 
Could it also be a letter code (A, B, C...) or some honors ("cum laude...") instead of a number ?

**Comment by thodoris** [comment]
overall grade is defined as a float.
I agree with @barthanssens that defining overall grade as a float is problematic. 
Different ranges and scales are probably used between member states and/or regions.

We could model it on a compex type supporting 2 different representations  
- grade100 | float  , numerical graqde rebased on the 100 scale (e.g 18/20  = 90/100 , or 7/10 = 70/100) 
- gradeDescription | string , which will allow a string representation of the grade (e.g Excellent , honor , etc)

Even more the description of the attributes states that 
> overall grade | float | A mark indicating a degree of accomplishment **for the whole year.**

Does whole year refers to the last year of the secondary education or the average for all the years that consist the secondary education  ?  We shall probably include the year range that the certificate represents.  #55

**Comment by cbahim** [comment]
As mentioned in issue #56, IT raised the point of multiple dates missing, 

> It seems to me that important dates are missing such as the issuing date, date on which the final examination took place, the school year, the date of delivery of the certification, etc.

**Comment by bertvannuffelen** [comment]
maybe we should consider grade as a measured value with a unit.

grade : {
   value : "1.0"
   unit: "https://edu.gov.de/academiagrades"
}

This is means that every from of grading can be represented, with a clear definition on how it should be interpreted according to the grade issuing authority.
The drawback is of-course, no easy comparison can be made, but that is then up to the reciever's end how to assess this value. 

The conversion to a common interpretation like grade100percent has a subjective element in it. If there is a mapping/conversion, then this mapping should be made transparent, both for the issuers of the diploma as for the receiver. I believe the discussion on this mapping/conversion is beyond the objectives of the semantic modelling of the evidence.

**Comment by SebastianSklarss** [comment]
As an inspiration (https://github.com/emrex-eu/elmo-schemas/releases/tag/v1.5.0) 
 
In the ELMO V1.5 XSD (based on a CEN Standard, optimised for Transcript of Record and diploma supplements, in use in Norway, Sweden, parts of Netherland and Poland)  the grade is expressed 

a) as float
b) linked to a local grading Scheme
c) accompagnied by the status information "passed" if so
d)  and accompanied by the resultDistribution (we need to define whether this is needed in SDG use cases):

```
 <learningOpportunityInstance>
                    <start>2014-10-01</start>
                    <date>2015-03-17</date>
                    <academicTerm>
                        <title xml:lang="en">Winter Semester of 2014</title>
                        <start>2014-10-01</start>
                        <end>2015-02-15</end>
                    </academicTerm>
                    <status>passed</status>
                    <gradingSchemeLocalId>0-100</gradingSchemeLocalId>
                    <resultLabel>45.1</resultLabel>
                    <shortenedGrading>
                        <percentageLower>62.3</percentageLower>
                        <percentageEqual>21.8</percentageEqual>
                        <percentageHigher>15.9</percentageHigher>
                    </shortenedGrading>

<resultDistribution>
                        <!--
                        Artificial (and exaggeratedly complex) grading scheme was used in this example
                        in order to highlight the possibility of the enormous variety of different
                        grading schemes which might be used throughout different countries and HEIs.
                        -->
                        <category count="43" label="Less than 20"/>
                        <category count="193" label="20-39.9"/>
                        <category count="198" label="40-59.9"/>
                        <category count="35" label="60-79.9"/>
                        <category count="7" label="80-100"/>
                        <description xml:lang="en">Some extra information about the description, might include links etc.</description>
                        <description xml:lang="pl">Po polsku...</description>
                    </resultDistribution>



```

**Comment by SebastianSklarss** [comment]
in Europass Learning Modell (EDCI) 0.10.0
https://github.com/european-commission-europass/Europass-Learning-Model

the grade
a) is expressed as percentage
b) accompagnied by information on ID validation during the examen ( I think we do not need this information)
c) semantic web RDF URI link to the organisations that specified the examen and that did the assessment

```

 <wasDerivedFrom id="urn:epass:assessment:2" pk="d71224b4-ff4f-43eb-8251-7e89a775782d">
               <identifier schemeID="LAss ID Scheme">LAssID-84</identifier>
               <title>
                  <text content-type="text/plain" lang="en">Online Communication Management Test</text>
               </title>
               <description>
                  <text content-type="text/plain" lang="en">LAss 84 description</text>
               </description>
               <additionalNote>
                  <text content-type="text/plain" lang="en">LAss Additional Field Content 2</text>
                  <subject>LAss Additional Field Title</subject>
               </additionalNote>
               <grade>88%</grade>
               <issuedDate>2020-03-30</issuedDate>
               <idVerificationMethod targetFrameworkUrl="http://data.europa.eu/snb/supervision-verification/25831c2" targetNotation="nosupid" uri="http://data.europa.eu/snb/supervision-verification/df2880c5cb">
                  <targetName>
                     <text content-type="text/plain" lang="en">Unsupervised with ID Verification</text>
                  </targetName>
                  <targetFrameworkName>
                     <text content-type="text/plain" lang="en">Europass Standard List of Methods Of Supervision And Verification</text>
                  </targetFrameworkName>
               </idVerificationMethod>
               <assessedBy idref="urn:epass:org:3"/>
               <specifiedBy idref="urn:epass:asssessmentspec:2"/>
            </wasDerivedFrom>


<achievements>
         <learningAchievement id="urn:epass:learningAchievement:1">
            <identifier schemeID="Ach-ID-Scheme">AchID-72</identifier>
            <title>
               <text content-type="text/plain" lang="en">Creative Writing</text>
            </title>
            <description>
               <text content-type="text/plain" lang="en">This achievement covers story plot creation and how to make choices in storytelling in a fictional world.</text>
            </description>
            <wasDerivedFrom id="urn:epass:assessment:1" pk="f6eea209-70f9-4951-9b06-ea99b251ca76">
               <identifier schemeID="LAss ID Scheme">LAssID-72</identifier>
               <title>
                  <text content-type="text/plain" lang="en">Creative Writing Assignment</text>
               </title>
               <description>
                  <text content-type="text/plain" lang="en">LAss 72 description</text>
               </description>
               <additionalNote>
                  <text content-type="text/plain" lang="en">LAss Additional Field Content 1</text>
                  <subject>LAss Additional Field Title</subject>
               </additionalNote>
               <grade>88%</grade>
               <issuedDate>2020-03-30</issuedDate>
               <idVerificationMethod targetFrameworkUrl="http://data.europa.eu/snb/supervision-verification/25831c2" targetNotation="nosupid" uri="http://data.europa.eu/snb/supervision-verification/df2880c5cb">
                  <targetName>
                     <text content-type="text/plain" lang="en">Unsupervised with ID Verification</text>
                  </targetName>
                  <targetFrameworkName>
                     <text content-type="text/plain" lang="en">Europass Standard List of Methods Of Supervision And Verification</text>
                  </targetFrameworkName>
               </idVerificationMethod>
               <assessedBy idref="urn:epass:org:2"/>
               <specifiedBy idref="urn:epass:asssessmentspec:1"/>
            </wasDerivedFrom>
```

**Comment by sethvanhooland** [comment]
Thank you Sebastian, it's indeed a good idea to refer to the EDCI standard, very relevant
