### ISSUE TITLE
Completion of secondary education certificate issues (IT)

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#56]
**General comment**:
what do you mean with “secondary education”? In Italy we have two stages: lower secondary school (middle school) that corresponds to ISCED 2011 Level 2 and upper secondary school (high school) that corresponds to ISCED 2011 Level 3. At the end of both stages we produce a diploma; namely, Diploma of lower secondary education and Diploma of upper secondary education (4-5 years). They correspond to different ages: roughly 11 to 14 and 14-19.

Should the model target both cases or just Level 3 as it is assumed by Spain in issue #42 intended as the last stage that completes the overall secondary education?

Which is the specific procedure for which this evidence is to be used? For instance, as far as I know, in Italy if you have to present this certificate for University enrollment, the mark and the story of the course results are not necessarily required.

**Specific comments on the current data model:**

1) It seems to me that important dates are missing such as the issuing date, date on which the final examination took place, the school year, the date of delivery of the certification, etc..

2) Why do you have a class Issuing Authority (subclass of Organisation) and not directly Organisation as in the other data models?

3) Probably we should consider to include a reference to the Education Institution in the certificate concept. In the current model it can be specified only if the course results are included (and the contains property is not mandatory). I think that diplomas include the references to the Education institutions involved in the diploma.

4) In the Italian national registry of students maintained by our Ministry of Education, mandatory attributes for students are the following: student number, fiscal code (or tax code that in the Italian data model is associated directly to a Person concept and not necessary only to a so-called tax payer as you use in another evidence. The tax code is assigned to a person when (s)he born), family name, given name, date of birth, place of birth (it can be a foreign country or a city in Italy), sex, citizenship, place of residency, age of the first year of participation in the education system.  We still need to verify with domain experts if all these attributes are mandatory in certificates too (probably not all of them, especially the last one I reported), however, better to take them into account (in particular the residency concept).

5) In the definition of the "contains" property there is the following typo “Seconduary“

6) If I need to say that I took a high school diploma "in science", is the specific type of diploma modeled using the "contains" property? In general these references are quite standard in the Italian certificates templates I have seen, and it is not clear to me how to currently model this, unless using the Course Result class which in any case seems representing something sightly different.

**Comment by cbahim** [comment]
@giorgialodi Thanks for your comments! 

With regards to your specific comments, 

1. Point taken. The discussion with regards to dates will continue in issue #55
2. We propose to indeed align this with the other data models. If no specific attributes are needed for Education Institution, we can follow this modeling approach there as well.
3. We invite other MS to provide their input on a direct link between the Secondary Education Completion Certificate and the Education Institution.
4. We invite other MS to provide their input on the mandatory attributes for the Student class.
5. This has been fixed. Thanks for letting us know. 
6. Our current idea of courses was more specific, e.g. Mathematics. But we invite other MS to share their opinion on this.

**Comment by cbahim** [comment]
Update on my comment above; 

3. This reference has been added.
