### ISSUE TITLE
Vehicle registration certificate issues (IT)

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#57]
**General comment**
In Italy, starting from 1 January 2020 it entered into forced a brand-new single digital document that collects all data of the registration certificate and the ownership certificate. This document is called single document of vehicle circulation and ownership. It has been introduced as a form of simplification in order to have just one digital document and not two in all those procedures that regard registering a vehicle, re-registering a vehicle and managing the changes in the ownership of a vehicle (for this latter procedure the data is also included in the registration certificate). 
The single document includes the following data:
A) Data of the registration certificate. The data of the old registration certificate is:
1.  plate of the vehicle and other data on the registration (date, ID); 
2.  data of the owner / holder of the certificate (i.e., family name, given name, date and place  of birth, address in the Member State of registration of the vehicle on the issuing date of the document);
3.  technical details of the vehicle (e.g., mark , tyoe, commercial name, VIN – Vehicle identification number – or vehicle chassis number, maximum technically permissible laden mass,  maximum permissible laden mass in service, maximum permissible mass of the assembly comprising the laden vehicle and trailer, vehicle category, destination of use, number of axles (and others details on axles), indication of the environmental class of EC type-approval, emissions of exhaust gases, seats (standing places if applicable), color, power to weight ratio (only for motorcycle), sound level of the vehicle, engine capacity, etc.)
4.  data on the changes in the ownership of the vehicle (every different owners with family name, given name, birth and place of birth), when it happened the change and an ID.
5.  data on the inspections of the vehicle with the related results.

B)  Data of the ownership certificate. This data of the old ownership certificate is:

1. data of the owner (i.e., family name, given name, **fiscal number** or tax code, date and place of birth, r**esidency address)**; 
2. data on the vehicle (including some of the ones mentioned above); 
3. Any (administrative) stops (due also to scrapping or permanent export abroad), mortgages or tax burdens

**Specific comments:**

1) What do you mean with “legal user”? Is that what we call “Usufruttuary” or “legal representative of the lender? And why it is not “vehicle legal user” (as it is in the “vehicle owner” property)? 
2) I think the address may be attached directly to an agent. Just to give you an example: for the data of the owner of the vehicle we register family name, given name, date and place of birth (that seem missing in the diagram) and the address of the owner in the Member State of registration of the vehicle on the issuing date of the document. Since in the core location vocabulary the address is a property with domain rdfs:Resource, you can use this property directly linked to the person (you do not need to pass through another class Location). Address components include also administrative units such as country, region, city etc.
3) Probably some details of the vehicle are missing according to what I reported above. In addition, I have two doubts regarding the Vehicle data:

- Some of these attributes have specific measurement units. You do not consider at all measurement units. There is also no definition for the properties (where an indication of the measurement unit can be given) that I would suggest to include (for instance, in the case of seats, the registration certificate says “seats, including vehicle driver”). Obviously, the measurement units do not apply to all properties (as in the case of the seats). Do you assume that measurement units are implicitly defined in the properties themselves?
- Some properties you indicated as mandatory are instead applicable only in specific circumstances (e.g., standing places). Therefore, the question is: if all these properties are mandatory, in the case they are not applicable, which valorisation of those properties should we include? I mean, shall we put 0 or a blank string? 

4) As mentioned above, and in addition to the point about the address, I think some data regarding people is missing and should be included: date of birth, place of birth, fiscal number. Regarding to this latter, you could consider this property as a property of the general class Person to also be used in other evidences (e.g., income tax declaration certificate).

**Comment by cbahim** [comment]
Thank you for your general and specific comments.

With regards to the specific comments:
1.  Legal user (_“natural or legal person who may use the vehicle by virtue of a legal right other than that of ownership”_) is taken from the [Council Directive 1999/37/EC](https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A31999L0037) in Annex 1 - Part I - VI. - (C.3). We indeed agree with your proposition to call this attribute “`vehicle legal user`” to be in line with “`vehicle owner`”.
2.  We will create a specific issue for this. 
3.  The attributes we have included are currently the ones that are mandatory as per the [Council Directive 1999/37/EC](https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A31999L0037).
3.1 We propose to include the measurements (as specified by the Council Directive) in the definitions of the attributes. With regards to the the definitions themselves, input from the MS is welcome.
3.2 Standing places are indeed optional as mentioned by the Council Directive. We have aligned the cardinalities with the Council Directive. Do you still see mandatory attributes that should be optional?
4. As mentioned in (3), we have currently only included the mandatory attributes as mentioned by the Council Directive. If other MS, however, express the same need to add additional attributes, we can expand the list.

**Comment by cbahim** [comment]
Thanks again @giorgialodi. Further looking at other issues, we have added the following; 

- Date of birth
- Place of birth
- Data related to the inspection of the vehicle

> A) Data of the registration certificate. The data of the old registration certificate is:
> 1. plate of the vehicle and other data on the registration (date, ID);
> 2. data of the owner / holder of the certificate (i.e., family name, given name, date and place of birth, address in the Member State of registration of the vehicle on the issuing date of the document);
>3. technical details of the vehicle (e.g., mark , tyoe, commercial name, VIN – Vehicle identification number – or vehicle chassis number, maximum technically permissible laden mass, maximum permissible laden mass in service, maximum permissible mass of the assembly comprising the laden vehicle and trailer, vehicle category, destination of use, number of axles (and others details on axles), indication of the environmental class of EC type-approval, emissions of exhaust gases, seats (standing places if applicable), color, power to weight ratio (only for motorcycle), sound level of the vehicle, engine capacity, etc.)
>4. data on the changes in the ownership of the vehicle (every different owners with family name, given name, birth and place of birth), when it happened the change and an ID.
>5. data on the inspections of the vehicle with the related results.

>B) Data of the ownership certificate. This data of the old ownership certificate is:
>1. data of the owner (i.e., family name, given name, fiscal number or tax code, date and place of birth, residency address);
>2. data on the vehicle (including some of the ones mentioned above);
>3. Any (administrative) stops (due also to scrapping or permanent export abroad), mortgages or tax burdens

- A.1 it corresponds to `VehicleRegistrationEvidence.registrationNumber`, `VehicleRegistrationEvidence.startRegistrationDate`, `VehicleRegistrationEvidence.firstRegistrationDate` and `VehicleRegistrationEvidence.endRegistrationDate`
- A.2 all these elements are present in the `Person` entity
- A.3 most of these elements are present in the `Vehicle` entity
- A.4 no other member state has expressed the need to have these attributes included in the model
- A.5 a `TechnicalInspection` entity has been added
- B.1 all these elements are present in the `Person` entity
- B.2 most of these elements are present in the `Vehicle` entity
- B.3 this is convered by the `VehicleRegistrationEvidence.status` attribute
