### ISSUE TITLE
Income tax declaration certificate issues (IT)

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#58]
1) I am not sure about the address for the domicile - City and Province (location) seem to be enough. It seems very similar to comment 4 of issue #39 of Spain
2) The property “payment date” is not clear. Do you mean the year of reference of the income tax declaration? In this case we agree with comment 1 in issue #39 of Spain
3) If the income tax declaration certificate certifies the total income and taxes, how come that at least the total income is not mandatory? It means that is possible to have a certificate of income tax declaration with no indication of the total income for example? It sounds strange :) 
4) We agree with Spain again that it may be worth considering input parameters
5) In general the fiscal number or tax code is an attribute of a person (we have it since we born) so it could be useful to consider this property directly applied to a person with no need to indicate a Tax Payer role. This can be useful in other evidences too, as I have reported in previous issues

**Comment by cbahim** [comment]
Thanks @giorgialodi for your comments! 

1. The domicile is optional, so no real problem there. But removing `Address` seems to be a shared view across the different models (#53 & #62)
2. We have created a separate issue for this. Please see #67 
3. The total income and income tax attributes were identified as optional attributes by the preliminary study. However, we have created an issue #68  to ask input from MS on the need to make these mandatory.
4. "Input parameters" seems to be a cross-cutting issue, we will create a separate issue for that.  
5. We have created a separate issue for this. Please see #69
