### ISSUE TITLE
Vehicle Registration: Cyrillic addresses

### ISSUE THREAD

**Issue by roefie64** [SEMICeu/SDG-sandbox#6]
Some countries in the EU use cyrillic script for names and addresses on their vehicle registration certificates and in their register. For the Vehicle Registration evidence it would be great to add extra fields to hold both the cyrillic as the latin data.

**Comment by sethvanhooland** [comment]
Thank you for your contribution Roelof, as it's also relevant for the work on other evidences. We'll get back in touch to discuss how we can address the issue you raised.

**Comment by barthanssens** [comment]
Would it be an option to allow for multiple occurrences of the attributes but with a different xml:lang, to specify multiple languages/scripts ? 

And preferably to make it mandatory to (either on the root element or on the various elements) explicitly specify the language ? Using an explicitly defined language may help other tools and processes (e.g. machine translation)

(EU also has Greek script, by the way)

**Comment by roefie64** [comment]
It might indeed be an option to have multiple occurances for languages but this is more about the script used then about the language. We need at least one in latin alphabet to be able to store and understand it in most of the countries in Europe. The origanal script can be used to check written documents and for addressing information letters.

**Comment by makxdekkers** [comment]
Please see the note on [multilinguality](https://github.com/SEMICeu/SDG-sandbox/blob/master/technical_documentation/multilinguality.md) with more details on how this could be done.

**Comment by dechden** [comment]
We would suggest to use following authority tables:

- language / https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/language

- script / https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/script

**Comment by pfragkou** [comment]
see also http://cldr.unicode.org/index/cldr-spec/transliteration-guidelines and https://ec.europa.eu/translation/greek/guidelines/el_guidelines_en.htm
