### ISSUE TITLE
Birth certificate: givenName and familyName

### ISSUE THREAD

**Issue by cbahim** [SEMICeu/SDG-sandbox#63]
This thread will now essentially focus on `givenName ` and `familyName` for the Birth certificate

As mentioned in issue #37, ES requests the possibility to be able to add two family names

> as you know, we have 1st and 2nd family names that can be joint in a "family name" attribute, but for the legal validity of the data, we should be able to specify the Spanish two family names as well. Besides, it is important for our request to distinguish if the person has not a 2nd famility name or it is just not specified.

As mentioned in issue #37, FI requests adding separate elements for `givenName` and `familyName`

> family name and given name elements: please consider adding separate elements for each part of the family name and for each given names. In Finland it is very common to have 3 given names, hyphen can also be present in them. Similarly, family names can be composed of two separate family names with a hyphen. Agreeing to the comment above: better to have a clear understanding if an element is not specified/null or non-existent at all. I think this will be critical when it comes to request methods of the API: request parameter will most likely be the family name(s) in case no ID is available as a search parameter.

**Comment by thodoris** [comment]
From what is mentioned in issue #37 , for the givenName we could have cases with 1,2, or even 3 given names. 
The same apply probably and for the familyName. 

If for some member states there are legal validity issues that require knowledge of the order of the names (e.g if the second or the first familyName is missing) then I cannot see any othe solution than extending the Person entity to support at least 3 fields for the given and family names.

Another approach would be to change the data type to an array of strings e.g
['Johan', 'Sebastian'] for givenName 
['Cervantes', 'Saavedra'] for familyName
['Cervantes' , ''] for cases in which the second family name does not exists or is not specified. 

However, I'm not sure how we should deal with the hypens and prefixed in this approach (e.g van , de , etc..)

**Comment by cbahim** [comment]
Thanks for you comment @thodoris. 

We propose to make a reference to the eIDAS metadata schema, which uses the approach from Core Person: one field for **first name(s)** (`givenName`) – as many as you like as one string – and one field for **last name(s)** (`familyName`) – again, as many as you like as one string, including prefixes, infixes, postfixes, hyphenated names etc. 

In SDG, as in eIDAS, names are a means to identify a person.

**Comment by ibodor** [comment]
**Ingrid (FIN):** fine, in this case please be prepared to match a person/ID successfully and return data e.g. "Ari-Pekka Olavi Eemeli Lahtinen-Rantanen" to be returned when the search word is  "Lahtinen". Or do you mean to say, that in such a case this person will be matched and found ONLY if you put the last name, the whole last name exactly as it is written here "Lahtinen-Rantanen"? again, speculating here since we do not have a list of MS procedures that would use birth certificate as an input and no info about search criteria either. as a hint, the name goes like this : given name1= Ari-Pekka, given name2=Olavi, given name3= Eemeli, family name=Lahtinen-Rantanen.

**Comment by cbahim** [comment]
@ibodor thanks again for your comment. Identification and names issues have been addressed in our[ Author's view report](https://ec.europa.eu/cefdigital/wiki/x/twLvEg) following the first formal SDG review cycle. I'd advise you to have a look specifically at issues 15,16 and 17 in the report.
