### ISSUE TITLE
Income tax declaration certificate: income tax and total income

### ISSUE THREAD

**Issue by cbahim** [SEMICeu/SDG-sandbox#68]
As mentioned in issue #39, we need a clear definition for total income. All the MS are invited to share their definition of this attribute.

**Comment by cbahim** [comment]
As mentioned in #58, the attributes income tax and total income are currently optional as proposed by the preliminary study. We however invite member states to share their opinion on making these attributes mandatory.

**Comment by thodoris** [comment]
Hello from Greece (GR),
We think it would make more sense to have both income tax & total income attributes mandatory as those are key fields of a tax declaration certificate. For those cases where a person declares zero income or tax, the attributes should be filled accordingly with zeros.

**Comment by anarosa-es** [comment]
Hello from Spain,

Our data service currently provides the income level of the citizen as the result of additions and subtractions of the net balances correspoding to several profit and loss accounts, such as the equity capital. However, our data service does not provide the amount of taxes to be paid or received in return resulting of the tax declaration.

Then, I guess the our "income level" would correpond to the "total income", but we cannot provide the proposed "income tax".

**Comment by giorgialodi** [comment]
According to these discussions I would suggest to have total income mandatory (at least, as I mentioned in a previous issue and as reported by @thodoris here, a key field for this certification is included) and leave the income tax as optional since some Member States (e.g., ES) seem not providing it.

**Comment by cbahim** [comment]
Thanks @giorgialodi for concluding the discussion in this thread.
