### ISSUE TITLE
Income tax declaration certificate: tax identification number (TIN)

### ISSUE THREAD

**Issue by cbahim** [SEMICeu/SDG-sandbox#69]
As mentioned in #58, 

> the fiscal number or tax code is an attribute of a person [...] so it could be useful to consider this property directly applied to a person with no need to indicate a Tax Payer role.

We ask input from the MS on the allocation of TINs (tax identification numbers). There appear to be some differences between MS (see https://ec.europa.eu/taxation_customs/business/tax-cooperation-control/administrative-cooperation/tax-identification-numbers-tin_en). 

Is it possible to make TIN a mandatory property of Person or do some Persons don't have a TIN (yet)?

**Comment by thodoris** [comment]
According to the European TIN Portal:

>  not all EU countries have TINs. Some have other identifiers, which for legal or other reasons cannot be treated as TINs. Some do not automatically issue TINs to all taxpayers. 

Having a rough look at the fact sheets of the TIN portal, all memeber states appear to use a unique identifier to identify tax payers. Differences lies on whether those identifiers can be considered as tax identification numbers (exclusively used in taxation services/transactions) or are considered as more general identification numbers used in a broader scope (e.g as  Citizen identification numbers or ΙD card number). 

Having said that, my personal opinion is that the **identifier** attribute on the **Person** entity, which is obligatory and has a [1..*] cardinallity, could be extended and used in this case.

The **identifier** type could be extended to include 2 attributes: 

- Identifier | string | [1..1]
- Type | string | [0..1] (this could be a dictionary with specifric values e.g TIN, PID,NDID , SSID )

This way the identifier attribute, could be filled with either

1. the TIN number (in cases where the Member state uses a dedicated TIN number) 
2. the general Identification number of the person (in cases where a more general identification number is used) 
3. both TIN and the general identification number

**Comment by sethvanhooland** [comment]
Thank you for the detailed suggestion on how to tackle the identifier issue! We'll make sure to look into this in detail and come up with a consistent approach which would also work for identifiers to be used for other evidences. In the meantime, other people can of course also continue to provide suggestions.

**Comment by cbahim** [comment]
Thanks @thodoris for your comments. In conclusion, the [identifier we are using has different fields](https://github.com/SEMICeu/SDG-sandbox/blob/master/technical_documentation/data_types.md#identifier). It could therefore accommodate the solution you propose. Similar to your proposal it also includes a type field.
