### ISSUE TITLE
Vehicle registration certificate: addition of dates

### ISSUE THREAD

**Issue by cbahim** [SEMICeu/SDG-sandbox#73]
Following our analysis of the XSDs provided by the NL (#15), we propose to add the following dates; 

> Additional dates:
> 
> - Start and end data for both the vehicle holder and owner
> - First, start and end date for the Registration.
> 
> Definitions:
> 
> - VehicleHolder.StartDate [1..1]: Date of the registration to which the registration certificate refers, e.g. date at which the holdership starts.
> - VehicleHolder.EndDate [0..1]: Last date at which holdership is in effect. Not applicable if the holder is the current holder.
> - VehicleOwner.StartDate [1..1]: Date at which ownership starts.
> - VehicleOwner.EndDate [0..1]: Last date at which ownership is in effect. Not applicable if the owner is the current owner.
> - VehicleRegistration.FirstDate [0..1]: Date of first registration of the vehicle (somewhere in the world).
> - VehicleRegistration:StartDate [0..1]: Start date of registration in the Member State.
> - VehicleRegistration.EndDate [0..1]: End date of registration in the Member State. Is populated if the vehicle has been de-registered in the Member State.

**Comment by ibodor** [comment]
**Ingrid (FIN):** The Finnish certificate contains the following dates:

1. Registration date: the date on which the vehicle was first taken into use. This could be mapped to VehicleRegistration.FirstDate
2. Last technical inspection date (not present in the suggested data model)
3. Next technical inspection to be carried out period: date-date (so two date values separated by a hyphen).  (not present in the suggested data model)
4. Certificate issue date: which can be mapped to VehiceRegistrationCertificate.RegistrationDate attribute

One key piece of information from the usage perspective is whether or not the vehicle is actually allowed on the roads. In the Finnish certificate the above mentioned dates 2. and 3. indicate this. Should this "usage-permission" be represented in the common data model as well? 

About other suggested date attributes:
- Start and end data for both the vehicle holder and owner: not present
- First, start and end date for the Registration: First Registration date is present, Start date is not present, End date not present, instead a "Removed from traffic" checkbox indicates that the registration has ended.
- VehicleREgistrationCertificate.ValidityDate: why is this a Period type? Its definition says " the date..:"

**Comment by cbahim** [comment]
Thank you @ibodor for your comments.

> 1. Registration date: the date on which the vehicle was first taken into use. This could be mapped to VehicleRegistration.FirstDate
> 2. Last technical inspection date (not present in the suggested data model)
> 3. Next technical inspection to be carried out period: date-date (so two date values separated by a hyphen). (not present in the suggested data model)
> 4. Certificate issue date: which can be mapped to VehiceRegistrationCertificate.RegistrationDate attribute

Registration date would correspond to `VehicleRegistrationEvidence.firstDate` in our model. As for the attributes related to the inspection of the vehicle, other member states have not expressed the need to incorporate them in the model. As the for the issuing date it can be mapped to `VehicleRegistrationEvidence.startDate` 

> One key piece of information from the usage perspective is whether or not the vehicle is actually allowed on the roads. In the Finnish certificate the above mentioned dates 2. and 3. indicate this. Should this "usage-permission" be represented in the common data model as well?

Does it relate to the technical inspection? 

> Start and end data for both the vehicle holder and owner: not present
First, start and end date for the Registration: First Registration date is present, Start date is not present, End date not present, instead a "Removed from traffic" checkbox indicates that the registration has ended.
VehicleREgistrationCertificate.ValidityDate: why is this a Period type? Its definition says " the date..:"

First, start and end date for the registration have been added to the model. As for the start and end date for the vehicle holder and owner, no additional member state has expressed the need of having that attribute. Lastly, the period was removed as we included the first, start and end date for the registration.
