### ISSUE TITLE
Vehicle registration certificate: owner relation (attribute)

### ISSUE THREAD

**Issue by cbahim** [SEMICeu/SDG-sandbox#74]
Following our analysis of the issue #45, the owner is a relation (attribute) of the Vehicle not the Vehicle Registration certificate. How is it in other member states?

**Comment by ibodor** [comment]
**Ingrid (FIN):** same in Finland: all roles (owner, holder, legal user) have a relation to the vehicle, not to the certificate. In my view the certificate has no relation to anything, it has some attributes (issue date, authority, ID, status, etc) and it describes certain entities that have relations among themselves (e.g. vehicle-owner, vehicle-holder, etc)
