### ISSUE TITLE
BirthCertificate comments

### ISSUE THREAD

**Issue by henrik-se** [SEMICeu/SDG-sandbox#75]
Sweden doesn’t issue Birth Certificates, only extracts from the general Population Register so in order to provide some kind of evidence this is what we have. There are no local authorities either.
In Sweden the midwifes report a new born baby using an e-services developed by the Swedish Tax Agency and the birth get a case handling number. Therefore the following comments about the model is focused on the data extraction:

**Issuing date** – will always be the date the extract from the Register was created
**Issuing Place** – There will never be an issuing place since the general Population Register is a database. 
**Place of birth** - Will that be needed for the parents? There are cases when the parents has unknown place of birth. IE young refugees.
**Jurisdiction** - What types of codes should be here? The codes for citizenship used in the system are according to ISO 3166 except for some countries recognized by Sweden but not within the standard. Kosovo is one example.

**Comment by cbahim** [comment]
Thanks @henrik-se for your comments. We shall take them into account when revising the models. 

To answer your questions; 

> Place of birth - Will that be needed for the parents? There are cases when the parents has unknown place of birth. IE young refugees.

As presented in issue #50, IT proposes to remove the notion of birth and have a direct relation from the birth certificate to a Person and make the information about the birth attributes of the person – e.g. the date and place of birth and the relationships about the person’s parents can be modelled as attributes of the person. @henrik-se do you agree with the approach? Place of birth should then be downgraded to _optional_ 

> Jurisdiction - What types of codes should be here? The codes for citizenship used in the system are according to ISO 3166 except for some countries recognized by Sweden but not within the standard. Kosovo is one example.



The Jurisdiction class has just two properties:

- name (text) 
- id (URI)

The name is simply a string that identifies the jurisdiction, typically a country, with or without a language tag. The value for the id property is a URI for that jurisdiction
