### ISSUE TITLE
Marriage certificate attributes comments

### ISSUE THREAD

**Issue by henrik-se** [SEMICeu/SDG-sandbox#76]
Marriage Certificates are only extracts from the general Population Register. 
Therefore the following comments about the model is focused on the data extraction:

**Issuing date** – will always be the date the extract from the Register was created
**Issuing Place** – There will never be an issuing place since the general Population Register is a database.

**Certifies (Marriage)** - Is it an extract showing that two people are married to each other. In some cases a person can be registrerd as married and have more than one wife. This is because foreign marriages are usually treated as valid in Sweden if they were legal in the state in which they were issued and the parties was not related to Sweden at that time. How should this be treated in the model?

**Place of marriage** - is not recorded in Sweden. Therefore it should be an optional field.
**Marital state before marriage** - What type of codes should be valid? In Sweden we have: OG=Never been married, G=Married, Ä=Widowed, S=Divorced, RP=Registered partner, SP=Divorced partner, EP=Widowed partner 
**Capacity to marry** - What types of codes should be valid? In Sweden this is another extract issued before the marriage after an appplication from the couple that they want to get married. To copies are issued and the person (priest, judge, imam or somone with a licence to marry people) notify the Swedish Tax Agency that the couple is married and date of marriage (but not place of marriage)

**Person->Jurisdiction** - What types of codes should be here? The codes for citizenship used in the system are according to ISO 3166 except for some countries recognized by Sweden but not within the standard. Kosovo is one example.

**Comment by cbahim** [comment]
Thanks @henrik-se for your comments. We shall take your comments into account when revising the model. 

> Marital state before marriage - What type of codes should be valid? In Sweden we have: OG=Never been married, G=Married, Ä=Widowed, S=Divorced, RP=Registered partner, SP=Divorced partner, EP=Widowed partner

Marital status codes can be consulted [here](https://op.europa.eu/en/web/eu-vocabularies/th-concept/-/resource/eurovoc/4184). 

> - cohabitation
> - divorced person
> - married person
> - polygamy
> - separated person
> - single parent
> - unmarried person
> - widowed person

> Capacity to marry - What types of codes should be valid? In Sweden this is another extract issued before the marriage after an appplication from the couple that they want to get married. To copies are issued and the person (priest, judge, imam or somone with a licence to marry people) notify the Swedish Tax Agency that the couple is married and date of marriage (but not place of marriage)

Capacity to marry is defined [here](http://e-documents.semic.eu/publicdocuments/1.0/doc/#CapacityToMarry). I'll get back to you ASAP on the codes. 

> Person->Jurisdiction - What types of codes should be here? The codes for citizenship used in the system are according to ISO 3166 except for some countries recognized by Sweden but not within the standard. Kosovo is one example.

For that comment, I refer you to my answer in issue #75

**Comment by cbahim** [comment]
> Certifies (Marriage) - Is it an extract showing that two people are married to each other. In some cases a person can be registrerd as married and have more than one wife. This is because foreign marriages are usually treated as valid in Sweden if they were legal in the state in which they were issued and the parties was not related to Sweden at that time. How should this be treated in the model?

This model relates to one marriage evidence, it is therefore possible to have the same person having two marriage evidences.
