### ISSUE TITLE
Certificate of completion of secondary education attribute place of birth

### ISSUE THREAD

**Issue by henrik-se** [SEMICeu/SDG-sandbox#77]
In Sweden the place of birth is not part of the Certificate of completion of secondary education.

Shouldent we try to keep the certificates clean and only include relevant information in them. The place of birth normally comes from the birth certificates and therefore shouldnt be part of any other certificates. Since it normally is different competent 
authorities that is responsible for the the different evidences.

**Comment by cbahim** [comment]
Thanks @henrik-se for your comments. 

> Shouldent we try to keep the certificates clean and only include relevant information in them. The place of birth normally comes from the birth certificates and therefore shouldnt be part of any other certificates. Since it normally is different competent authorities that is responsible for the the different evidences.

Indeed, in line with the data minimisation principle, MS should let us know which attributes & classes are not relevant for them, so that we can either relax the cardinality or simply suppress the attribute / class for a specific model.
