### ISSUE TITLE
Income Tax Issues (PT)

### ISSUE THREAD

**Issue by ama-epse** [SEMICeu/SDG-sandbox#78]
On the Income Tax Declaration, for a given person, in a given year, one should be able to see their income and the calculated tax 

a) Nevertheless, the tax is calculated given the persons household (the person, his/her spouse, children or other dependent people).
It is possible to have income values for each person, but if there are other people in the household, the calculated tax will be influenced by those people and their respective income/charges.
Shouldn't there be information on the details of the household? And if the person is married what is the taxation regiment (separate or not)?

b) What is the type of income to include?
For example, with dependent work: is it the bulk/raw income, or the income after other contributions (e.g social security or other deductions), net income?
If for example the income is from a realestate sale, what we want is the value of the sale or the net profit from it?
Or are we talking about the collectible income? The sum of all net income in the different categories.
Considering that Income Tax is dual, it has progressive and proportional tax, it should be clear what are the types of income involved.

c) As stated in the previous issue, there is progressive and proportional taxation, therefore the basis of income should be provided for each one of them.

d) The end result of the calculated tax should also be clarified: if it is a return, a billing note, or a null value (no tax is charged and no return will be made). There is a difference between the calculated Income Tax, and the end result (a calculation from what should be paid at the end of the fiscal year, and want has been paid along every month).

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
