### ISSUE TITLE
Birth Certificate Issues (PT)

### ISSUE THREAD

**Issue by ama-epse** [SEMICeu/SDG-sandbox#79]
a) In Portugal, the authority that issues the certificate may not be the one who registered the birth. There is no national authority overseeing and issuing these certificates. There is one for each region. Registrations are done in the region of birth (e.g. Lisbon), but can be solicited in a different region (e.g. Faro). 
Therefore we need two fields for organisation. The Issuer and the Register.

b) We also include information about the clerk that wrote the certificate, and there is a stamp and a seal.

c) We do not register information on the sex of the individual (which is mandatory in the model)

d) We register information about the grandparents and the usual residence of the person being registered (not in the model at this moment).

The common model for Birth Certificate was done in accordance with the EU Regulation 2016/1191. We recommend this work should be reused in this work group.

**Comment by cbahim** [comment]
@ama-epse thanks for your comments. 

> a) In Portugal, the authority that issues the certificate may not be the one who registered the birth. There is no national authority overseeing and issuing these certificates. There is one for each region. Registrations are done in the region of birth (e.g. Lisbon), but can be solicited in a different region (e.g. Faro).
Therefore we need two fields for organisation. The Issuer and the Register.

As no other member state has expressed the need of having both the Issuer and the Register in the model, we propose to leave that as it is. Let us know if you disagree. 

> b) We also include information about the clerk that wrote the certificate, and there is a stamp and a seal.

As no other member state has expressed the need of having the clerk in the model as well as the stamp and seal, we propose to leave that as it is. Let us know if you disagree. 

> c) We do not register information on the sex of the individual (which is mandatory in the model)

We therefore propose to make `sex` optional

> d) We register information about the grandparents and the usual residence of the person being registered (not in the model at this moment).

As no other member state has expressed the need of having the grandparents in the model, we propose to leave that as it is. Let us know if you disagree.
