### ISSUE TITLE
Marriage Certificate (PT)

### ISSUE THREAD

**Issue by ama-epse** [SEMICeu/SDG-sandbox#80]
In Portugal we have some requirements that are not expressed in the model

a) we have information about the clerk (name and function) that issues the certificate;

b) our marriage date is a datetime (not a simple date format);

c) we also have information on type of marriage (civil, religious, etc.)

d) we have information on marriage regiment (prenuptial agreement)

e) we don't have a full address of the marriage, therefore if it's mandatory we will not be able to provide the information;

f) the certificate is altered by annotation/endorsement, so there can be changes in status (e.g. divorce, death), regiment, etc in an open field, that can't be shown in a simple structured manner.

The common model for Marriage Certificate was done in accordance with the EU Regulation 2016/1191. We recommend this work should be reused in this work group.

**Comment by cbahim** [comment]
Thanks @ama-epse for your comments

> a) we have information about the clerk (name and function) that issues the certificate;

As no other member state has expressed the need of  clerk (name and function) in the model, we propose to leave that as it is. Let us know if you disagree.

> b) our marriage date is a datetime (not a simple date format);

We therefore propose to change the date to datetime as the latter support dates anyway. 

> c) we also have information on type of marriage (civil, religious, etc.)

As no other member state has expressed the need of having information on the type of marriage in the model, we propose to leave that as it is. Let us know if you disagree.

> d) we have information on marriage regiment (prenuptial agreement)

As no other member state has expressed the need of having information on the marriage regiment in the model, we propose to leave that as it is. Let us know if you disagree.

> e) we don't have a full address of the marriage, therefore if it's mandatory we will not be able to provide the information;

In the latest version of the model (v0.11), the `Address` entity does not exist anymore.
