### ISSUE TITLE
Vehicle Registration Issues (PT)

### ISSUE THREAD

**Issue by ama-epse** [SEMICeu/SDG-sandbox#81]
a) In Portugal there is a Vehicle Registration and a Licence Plate Registration, there is some information in there registries that is not in the certificate;

b) The owner's name is a single string (not divided in first/last);

c) The national registry is defined by logo and name alone, and we do not have the address in the registry.

**Comment by cbahim** [comment]
Thanks @ama-epse for your comments. 

> a) In Portugal there is a Vehicle Registration and a Licence Plate Registration, there is some information in there registries that is not in the certificate;

In our model, Vehicle Registration corresponds to `Vehicle.identificationNumber` and Licence Plate Registration to `VehicleRegistrationEvidence.registrationNumber`.

>c) The national registry is defined by logo and name alone, and we do not have the address in the registry.

The `registeredLocation` has been made optional, so no problem here.
