### ISSUE TITLE
Vehicle Registration: roles in FIN (owner, holder, legal user)

### ISSUE THREAD

**Issue by ibodor** [SEMICeu/SDG-sandbox#82]
**Ingrid (FIN):** In the Finnish certificate owner is mandatory and holder is optional.
The legal user is either the owner (if there are no holders) or the holder (who in this case would be other than the owner)

Also, the owner may be an organisation. 

Data of these roles: 
- name is present (Last name, First names format in case of a person and the name of the organisation in case of organisation)
- address is present (Address + Postal code + Municipality)
- no ID is available for any of these roles (so no identifier attribute for Agent, therefore suggesting making it optional)

**Comment by cbahim** [comment]
Thanks @ibodor. Following-up on your comment we have made `VehicleRegistrationEvidence.holder` as well as `Agent.identifier` optional.
