### ISSUE TITLE
Vehicle Registration: data about vehicle type

### ISSUE THREAD

**Issue by ibodor** [SEMICeu/SDG-sandbox#83]
**Ingrid (FIN):** It is difficult to match country specific attributes to common data model without an example.
Some further explanation or sample data would be appreciated regarding these:
- Vehicle.make
- Vehicle.type
- Vehicle.typeVariant
- Vehicle.typeVersion
- Vehicle.commercialDescription

Another thought: should the plate number be (at least as an optional attribute) part of the common data model? identification number is probably a serial number or product number/ID, which uniquely identifies the vehicle throughout its lifecycle irrespective of its usage (e.g. when the plate number changes due to a lost plate or the vehicle is not in use temporarily)

**Comment by cbahim** [comment]
Thanks @ibodor for your comments. 

> It is difficult to match country specific attributes to common data model without an example.
Some further explanation or sample data would be appreciated regarding these:
>
>- Vehicle.make
>- Vehicle.type
>- Vehicle.typeVariant
>- Vehicle.typeVersion
>- Vehicle.commercialDescription

We have provided the link to the regulation in the definitions where further information is provided with regards to attributes mentioned. 

> Another thought: should the plate number be (at least as an optional attribute) part of the common data model? identification number is probably a serial number or product number/ID, which uniquely identifies the vehicle throughout its lifecycle irrespective of its usage (e.g. when the plate number changes due to a lost plate or the vehicle is not in use temporarily)

In the last version of the model we have `Vehicle.identificationNumber` attribute which would correspond to the serial number you refer to. Also, there is the `VehicleRegistrationEvidence.registrationNumber` attribute which is about the licence plate.
