### ISSUE TITLE
Additional Marriage Info class

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/SDG-sandbox#86]
In the version 0.11 of the diagram of the marriage certificate, I see a new class with additional marriage info. It seems that this class is a subclass of Person. Is that what you meant? Because it does not make so much sense to me. Could you please clarify that?

**Comment by giorgialodi** [comment]
Going back to this issue, I noticed that in the diagram the arrow seems a subClassOf arrow, while in the description of the model of Marriage evidence, it seems a property between a Person and the new class AdditionalMarriageInfo. Not sure what you mean in the diagram!

**Comment by cbahim** [comment]
Thanks for your comments @giorgialodi the entity `AdditionalMarriageInfo` is an entity on its own and has a relationship to `Person`.

**Comment by giorgialodi** [comment]
Hi @cbahim now it is fine :) Thanks!
