### ISSUE TITLE
Data minimisation: Which data do we need for Vehicle identification?

### ISSUE THREAD

**Issue by roefie64** [SEMICeu/SDG-sandbox#87]
Is see that a lot of technical data attributes are added to the Vehicle class, do we need them to identify the Vehicle? Of the current attributes I would say that only the following are needed for vehicle identification:

+ identificationNumber
+ firstRegistrationDate
+ make
+ commercialDescription

I suggest to leave out all other attributes because not all countries can provide them and we do not need them to identify the vehicle. I understand that you need more technical data to register the vehicle but that is not what the VehicleRegistrationEvidence should be used for.

**Comment by cbahim** [comment]
@roefie64 while we agree with your comment, no member state has expressed the need to narrow down the list of attributes. In any case, the four attributes you mentioned are present and mandatory while most of the remaining ones are optional.
