### ISSUE TITLE
Marriage certificate (DE)

### ISSUE THREAD

**Issue by tohahn-kosit** [SEMICeu/SDG-sandbox#88]
This table ascertains the availability of data in the Personenstandsregister (person condition register) as well as the Melderegister (registration register) to fill the fields in the current model of the marriage certificate. The fields of the person condition register can be found in [Verordnung zur Ausführung des Personenstandsgesetzes - Anlage 1](https://www.gesetze-im-internet.de/pstv/anlage_1.html), the fields of the registration register are described in [DSMeld](https://www1.osci.de/sixcms/media.php/13/DSMeld_9.pdf).

Note that this table does not judge wether the model of the marriage certificate could also be used as evidence in processes in public administration, as the different processes in different branches of the administration have different requirements. Some may only need the information that a marriage is registered, other may need number of children etc.

For the fields in the person condition register and the Melderegister I used their codes, to ease searching. In comments I used the german name.

I omitted the element "mariageCertificate", as it is the root element for every other element.
An "x" means not available, "o" means no information.

| Marriage certificate element | Person condition register | Comment | Registration register | Comment |
| --- | --- | --- | --- | --- |
| identifier.identifierIdentifier | 0010-0013 | Entries in person condition registers are identified by the combination of these four numbers | o | I don't know about the ID in registration registers. |
| identifier.identifierType | x | There is no "type" for this identifier. | o | I don't know about the ID in registration registers. |
| identifier.issuingAuthorityIdentifier | 0010 | This is the Standesamtsnummer (number), instead also the Standesamtsname (name) can be used. | o | I don't know about the ID of registration registers. |
| issuingDate | 0051 | As a register entry is not "issued" it does not have an issuing date. This is the date of first registration. | o | I don't know about the issuing date of entries in registration registers. |
| certifies.marriageDate | 2040/3040 |  | 1402 |  |
| certifies.placeOfMarriage.adress.adminUnitL1 | 2057/3057 | Only filled if not in Germany. | 1409 |  Only filled if not in Germany. |
| certifies.placeOfMarriage.adress.postName | 2050/3050 |  | 1402 |  |
| certifies.spouseOne.identifier.identifierIdentifier | x | Up to now, there is no person identifier in Germany. | x | Up to now, there is no person identifier in Germany. |
| certifies.spouseOne.identifier.identifierType | x | Up to now, there is no person identifier in Germany. | x | Up to now, there is no person identifier in Germany. |
| certifies.spouseOne.identifier.issuingAuthorityIdentifier | x | Up to now, there is no person identifier in Germany. | x | Up to now, there is no person identifier in Germany. |
| certifies.spouseOne.givenName | 2105/3105 - 2115/3115 | Before marriage/LP - in marriage/LP | 0301 |  |
| certifies.spouseOne.familyNameAfterMarriage | 2111/3111 | marriage/LP | 0101 |  |
| certifies.spouseOne.familyNameBeforeMarriage | 2101/3101 | marriage/LP | x | |
| certifies.spouseOne.maritalStatusBeforeMarriage | x |  | x |  |
| certifies.spouseOne.capacityToMarry | x |  | x |  |
| certifies.spouseOne.dateOfBirth | 2140/3140 | marriage/LP | 0601 |  |
| certifies.spouseOne.citizenship.place | 2180/3180 | only a hint, not certified data! also, this is citizenship, not state | 1001 | citizenship, not state. |
| certifies.spouseTwo.identifier.identifierIdentifier | x | Up to now, there is no person identifier in Germany. | x | Up to now, there is no person identifier in Germany. |
| certifies.spouseTwo.identifier.identifierType | x | Up to now, there is no person identifier in Germany. | x | Up to now, there is no person identifier in Germany. |
| certifies.spouseTwo.identifier.issuingAuthorityIdentifier | x | Up to now, there is no person identifier in Germany. | x | Up to now, there is no person identifier in Germany. |
| certifies.spouseTwo.givenName | 2205/3205 - 2215/3215 | Before marriage/LP - in marriage/LP | 1503/1509 | marriage/LP |
| certifies.spouseTwo.familyNameAfterMarriage | 2211/3211 | marriage/LP | 1501/1517 | marriage/LP |
| certifies.spouseTwo.familyNameBeforeMarriage | 2201/3201 | marriage/LP | x | |
| certifies.spouseTwo.maritalStatusBeforeMarriage | x |  | x |  |
| certifies.spouseTwo.capacityToMarry | x |  | x |  |
| certifies.spouseTwo.dateOfBirth | 2240/3240 | marriage/LP | 1505/1521 | marriage/LP |
| certifies.spouseTwo.citizenship.place | 2280/3280 | only a hint, not certified data! also, this is citizenship, not state | x | |
| issuingAuthorityMarriageCertificate.identifierPublicOrganisation.identifierIdentifier | 0010 | This is the Standesamtsnummer (number), instead also the Standesamtsname (name) can be used. | o | I don't know about the ID of registration registers. |
| issuingAuthorityMarriageCertificate.identifierPublicOrganisation.identifierType | x | There is no "type" for this identifier. | o | I don't know about the ID in registration registers. |
| issuingAuthorityMarriageCertificate.identifierPublicOrganisation.issuingAuthorityIdentifier | 0010 | This is the Standesamtsnummer (number), instead also the Standesamtsname (name) can be used. | o | I don't know about the ID of registration registers. |
| issuingAuthorityMarriageCertificate.prefLabel | 0001 | If this is the preferred moniker of the organisation, the Standesamtsname can be used. | o | I don't know about the ID of registration registers. |
| issuingPlace.adress.adminUnitL1 | x | Always Germany. | x | Always Germany. |
| issuingPlace.adress.postName | 0050 | | x | |

**Comment by tohahn-kosit** [comment]
[TabelleWP4.xlsx](https://github.com/SEMICeu/SDG-sandbox/files/5161199/TabelleWP4.xlsx)

**Comment by cbahim** [comment]
@tohahn-kosit thank you for providing us this analysis. We looked at the tables provided and more specifically to attributes which were not available _(x)_ nor having information _(o)_ in either one of the two columns. In conclusion, all the attributes you cannot provide are already optional, so we don't see any problem. The only issue might be the missing identifier for Person.
