### ISSUE TITLE
Birth certificate (DE)

### ISSUE THREAD

**Issue by tohahn-kosit** [SEMICeu/SDG-sandbox#89]
This table ascertains the availability of data in the Personenstandsregister (person condition register) as well as the Melderegister (registration register) to fill the fields in the current model of the birth certificate. The fields of the person condition register can be found in [Verordnung zur Ausführung des Personenstandsgesetzes - Anlage 1](https://www.gesetze-im-internet.de/pstv/anlage_1.html), the fields of the registration register are described in [DSMeld](https://www1.osci.de/sixcms/media.php/13/DSMeld_9.pdf).

Note that this table does not judge wether the model of the birth certificate could also be used as evidence in processes in public administration, as the different processes in different branches of the administration have different requirements. Some may only need the information that a birth is registered, others may need exact date of birth etc.

For the fields in the person condition register and the Melderegister I used their codes, to ease searching. In comments I used the german name.

I omitted the element "birthCertificate", as it is the root element for every other element.
An "x" means not available, "o" means no information.

| Birth certificate element | Person condition register | Comment | Registration register | Comment |
| --- | --- | --- | --- | --- |
| identifierBirthCertificate.identifierIdentifier | 0010-0013 | Entries in person condition registers are identified by the combination of these four numbers | o | I don't know about the ID in registration registers. |
| identifierBirthCertificate.identifierType | x | There is no "type" for this identifier. | o | I don't know about the ID in registration registers. |
| identifierBirthCertificate.issuingAuthorityIdentifier | 0010 | This is the Standesamtsnummer (number), instead also the Standesamtsname (name) can be used. | o | I don't know about the ID of registration registers. |
| issuingDate | 0051 | As a register entry is not "issued" it does not have an issuing date. This is the date of first registration. | o | I don't know about the issuing date of entries in registration registers. |
| certifies.child.givenName | 1105 |  | 0301 |  |
| certifies.child.familyName | 1101 |  | 0101 |  |
| certifies.child.dateOfBirth | 1040 |  | 0601 |  |
| certifies.child.gender | 1120 |  | 0701 |  |
| certifies.child.citizenship.place | x | Citizenship is not a person condition date. | 1001 | Citizenship, not state! |
| certifies.child.placeOfBirth.adress.adminUnitL1 | 1057 | only filled for births outside of Germany | 0603 |  |
| certifies.child.placeOfBirth.adress.postName | 1050 |  | 0602 |  |
| certifies.parentOne.givenName | 1205 |  | 0904 |  |
| certifies.parentOne.familyName | 1201 |  | 0902 |  |
| certifies.parentOne.dateOfBirth | 1240 | not a certified date! | x |  |
| certifies.parentOne.gender | 1220 |  | 0917 |  |
| certifies.parentOne.citizenship.place | 1280 | citizenship, not state, not a certified date! | x |  |
| certifies.parentOne.placeOfBirth.adress.adminUnitL1 | 1257 | only filled for births outside of Germany, not a certified date | x |  |
| certifies.parentOne.placeOfBirth.adress.postName | 1250 | not a certified date! | x|  |
| certifies.parentTwo.givenName | 1305 |  | 0904 |  |
| certifies.parentTwo.familyName | 1301 |  | 0902 |  |
| certifies.parentTwo.dateOfBirth | 1340 | not a certified date! | x |  |
| certifies.parentTwo.gender | 1320 |  | 0917 |  |
| certifies.parentTwo.citizenship.place | 1380 | citizenship, not state, not a certified date! | x |  |
| certifies.parentTwo.placeOfBirth.adress.adminUnitL1 | 1357 | only filled for births outside of Germany, not a certified date | x |  |
| certifies.parentTwo.placeOfBirth.adress.postName | 1350 | not a certified date! | x |  |
| issuingAuthorityBirthCertificate.identifierPublicOrganisation.identifierIdentifier | 0010 | This is the Standesamtsnummer (number), instead also the Standesamtsname (name) can be used. | o | I don't know about the ID of registration registers. |
| issuingAuthorityBirthCertificate.identifierPublicOrganisation.identifierType | x | There is no "type" for this identifier. | o | I don't know about the ID in registration registers. |
| issuingAuthorityBirthCertificate.identifierPublicOrganisation.issuingAuthorityIdentifier | 0010 | This is the Standesamtsnummer (number), instead also the Standesamtsname (name) can be used. | o | I don't know about the ID of registration registers. |
| issuingAuthorityBirthCertificate.prefLabel | 0001 | If this is the preferred moniker of the organisation, the Standesamtsname can be used. | o | I don't know about the ID of registration registers. |
| issuingPlace.adress.adminUnitL1 | x | Always Germany. | x | Always Germany. |
| issuingPlace.adress.postName | 0050 | | x | |

**Comment by tohahn-kosit** [comment]
[TabelleWP4.xlsx](https://github.com/SEMICeu/SDG-sandbox/files/5161284/TabelleWP4.xlsx)

**Comment by cbahim** [comment]
@tohahn-kosit thank you for providing us this analysis. We looked at the tables provided and more specifically to attributes which were not available _(x)_ nor having information _(o)_ in either one of the two columns. 

- `certifies.child.citizenship.place`: the attribute does not exist anymore in the [latest version of the model](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/birth_certificate/data_model/birth_certificate_diagram_v0.11.pdf). This is now Jurisdiction which has two attributes that can be populated using the [country table](https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/country/?target=Browse&uri=http://publications.europa.eu/resource/authority/country). The observation stands for other citizenship-related attributes as well. 
- `identifierBirthCertificate.identifierType`, `issuingAuthorityBirthCertificate.identifierPublicOrganisation.identifierType`: regarding to the identifier type attribute, as this attribute is not available it probably means that it is the same for all identifiers and thus can be filled automatically? 
- `issuingPlace.adress.adminUnitL1`: the attribute does not exist anymore.
