### ISSUE TITLE
Income tax declaration certificate - Danish Ministry of Taxation

### ISSUE THREAD

**Issue by KlavsHelbergJensenDKDIGST** [SEMICeu/SDG-sandbox#90]
In Denmark, income tax is primarily calculated according to national rules and the individual circumstances of the citizen. But also, on other factors, like double taxation agreements. 

Following is some examples of potential difficulties regarding the requested information in the certificate: 

-	Selected employer-paid benefits are part of the income tax calculation. It most likely varies between member states which. It makes tax calculations incomparable. In Denmark, the Church tax is also a part of the income tax calculation, if you are a member of the national Church of Denmark. On the other hand, some religions might be eligible to a tax deduction. Will another member state be able to use the income tax amount, containing this?
-	In Denmark, we have a few special schemes e.g. where sailors in some cases are exempt from paying tax. However, we calculate a fictive income tax in order to see whether the sailor is eligible to get Danish social benefits. How can it be ensured, that this fictive Income tax amount is disregarded on request through the new Once Only-system?
-	The Danish income tax per income year can be regulated over time, which means the correction could impact calculations elsewhere after data is shared. How do we ensure these corrections are shared between member states?
-	Comparability will be difficult, if not impossible, when availability of information isn’t the same timewise between member states. As an example, the Danish timetable is described here. 
-	How about the quality requirements on the information used for the calculation? Information on Danish citizens are collected from the employers, banks, government institutions (e.g. bank statements, paycheck etc.), which is then corrected by the citizen. Generally, we need an authoritative source of the information on which the calculations are based.

-	EU-citizens moving from a member state to another will likely prove some difficulties, as a citizen will be eligible to pay taxes in two member states for a time. Some member states will have different definitions regarding, when a move has occurred taxwise. Potentially the citizen could end up paying taxes twice for the same period, without it showing anywhere.

A significant amount of data is missing for us to be able to make a calculation, e.g. spouse, child(ren), church affiliation, country of origin, country/countries where the citizen is paying taxes, temporary addresses and banking information. As it stands, there is limited use of the data from other countries, received in the certificate, when the Danish income tax is calculated. The data received cannot be a base of such calculations according to Danish rules. Likewise, the Danish income tax amount might not be applicable according to other member states’ national rules and regulations.

There is a significant gap between the required data we need for the related procedures in Denmark and the presented data in these certificates. Apart from “validityPeriod” for the Vehicle registration certificate, there is a critical lack of temporal data in the data models. Temporal data is important to ensure correct handling of the same type of information, which will be applied differently between Tax Administrations, national rules and regulations in the member states. Temporal data will also become critical for the citizens, as they will be required to submit the missing data to complete the procedures.

Some critically missing attributes is electronic contact address and/or national phone number. It is important to have contact information to inform citizens about the procedure, rules, regulations and duties.

We model foreign addresses as unstructured. Some attributes need to be modeled. Both problems present minor obstacles. 

In conclusion, the most significant obstacles in the Danish Tax Administration would, at the present time, be the very limited usability of the data shared. It could potentially become an obstacle for both the Tax Administration and the citizen, which will still be required to procure missing information regardless. Some of the above was also concluded in the recent report from Deloitte (2020). At present the EU Tax Policy Strategy prevents harmonization of the attributes in the income tax declaration certificate, which could solves some of the obstacles above. 

It is unclear what the system is to be used for. There seems to be a different definition of "Income Tax Declaration Certificate". Could we get an example on the use of the certificate?

It would be beneficial to generate some cases/examples on the cross-border use of the certificates to further explore the potential consequences of the suggested data models.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
