### ISSUE TITLE
Vehicle registration certificate - The Danish Ministry of Taxation

### ISSUE THREAD

**Issue by KlavsHelbergJensenDKDIGST** [SEMICeu/SDG-sandbox#91]
The Danish Motor Register (DMR) contains information on vehicle owner according to the EU-directive 1999/37. It means that we distinguish information about vehicle “holder”, “legal user” and “owner”. An attribute called “vehicle owner” is not available. 

Some of the requested vehicle information are optional entries for registration in DMR, e.g. the attribute “engine capacity”, which is available only when the information is specified at the time of a vehicles first registration. Used cars/Rebuild cars won’t have the information, or the information may not be valid.

The information about the attribute “power to weight ratio” does not exist in DMR, but could probably be calculated, if information about horsepower was specified at the time of initial registration (which is not always the case).
There is a significant gap between the required data we need for the related procedures in Denmark and the presented data in these certificates. Apart from “validityPeriod” for the Vehicle registration certificate, there is a critical lack of temporal data in the data models. Temporal data is important to ensure correct handling of the same type of information, which will be applied differently between Tax Administrations, national rules and regulations in the member states. Temporal data will also become critical for the citizens, as they will be required to submit the missing data to complete the procedures.

Some critically missing attributes is electronic contact address and/or national phone number. It is important to have contact information to inform citizens about the procedure, rules, regulations and duties.

We model foreign addresses as unstructured. Some attributes need to be modeled. Both problems present minor obstacles. 

In conclusion, the most significant obstacles in the Danish Tax Administration would, at the present time, be the very limited usability of the data shared. It could potentially become an obstacle for both the Tax Administration and the citizen, which will still be required to procure missing information regardless. Some of the above was also concluded in the recent report from Deloitte (2020). At present the EU Tax Policy Strategy prevents harmonization of the attributes in the income tax declaration certificate, which could solves some of the obstacles above. 

It is unclear what the system is to be used for. There seems to be a different definition of "Income Tax Declaration Certificate". Could we get an example on the use of the certificate?

It would be beneficial to generate some cases/examples on the cross-border use of the certificates to further explore the potential consequences of the suggested data models.

**Comment by cbahim** [comment]
> The Danish Motor Register (DMR) contains information on vehicle owner according to the EU-directive 1999/37. It means that we distinguish information about vehicle “holder”, “legal user” and “owner”. An attribute called “vehicle owner” is not available.

In our last version of the model, we have the three different attributes your refer to. 

> Some of the requested vehicle information are optional entries for registration in DMR, e.g. the attribute “engine capacity”, which is available only when the information is specified at the time of a vehicles first registration. Used cars/Rebuild cars won’t have the information, or the information may not be valid.

`Vehicle.engineCapacity` is currently optional in our model, so no problem here. 

> The information about the attribute “power to weight ratio” does not exist in DMR, but could probably be calculated, if information about horsepower was specified at the time of initial registration (which is not always the case).
There is a significant gap between the required data we need for the related procedures in Denmark and the presented data in these certificates. Apart from “validityPeriod” for the Vehicle registration certificate, there is a critical lack of temporal data in the data models. Temporal data is important to ensure correct handling of the same type of information, which will be applied differently between Tax Administrations, national rules and regulations in the member states. Temporal data will also become critical for the citizens, as they will be required to submit the missing data to complete the procedures.

First of all, the `Vehicle.powerToWeightRatio` is optional in our model. Second of all, we have added the following dates to our model; 

- VehicleRegistrationEvidence.firstRegistrationDate [0..1]: Date of first registration of the vehicle (somewhere in the world).

- VehicleRegistrationEvidence.startRegistrationDate [1..1]: Start date of registration in the Member State.

- VehicleRegistrationEvidence.endRegistrationDate [0..1]: End date of registration in the Member State. Is populated if the vehicle has been de-registered in the Member State.

Do you see any other temporal data? 

> Some critically missing attributes is electronic contact address and/or national phone number. It is important to have contact information to inform citizens about the procedure, rules, regulations and duties.

> We model foreign addresses as unstructured. Some attributes need to be modeled. Both problems present minor obstacles

Currently, no other member state has expressed the need to have the above mentioned attributes incorporated in the model. We therefore propose not to add them.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
