### ISSUE TITLE
Secondary Education - data model diagram arrow

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#93]
Minor issue in the 0.11 pdf of the data model diagram: the arrowhead/triangle on the arrow pointing from PublicOrganisation to Location seems to suggest that PublicOrganisation is a Location.

It should be an open arrowhead + the name of the relation should be mentioned (e.g. hasLocation)

**Comment by cbahim** [comment]
Thanks @barthanssens, we have made the correction, new version of the model [here](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/certificate_of_completion_of_secondary_education/data_model/certificate_of_completion_of_secondary_education_diagram_v0.12.pdf).
