### ISSUE TITLE
Secondary Education - consistency in identifier names

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#94]
(feedback from BE experts)

Different names are used in the model.
E.g `identifier` for Person and PublicOrganisation, `geographic identifier` for Location and `student ID number` for Student
Is there a reason not to always use `identifier` ?

(my assumption)

The naming for identifiers is aligned with existing models / ontologies (e.g. LOCN), and the distinction for Student is needed because a Student is also has a Person (and thus, a Person ID).

**Comment by cbahim** [comment]
@barthanssens thanks for you comment. Your assumption is correct, different names are used to make distinctions. 

Besides, it was requested to have more clarity amongst the identifier names https://github.com/SEMICeu/SDG-sandbox/issues/40#issuecomment-664339574
