### ISSUE TITLE
Secondary education - ISCED level 2 / 3

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#95]
(feedback from BE experts)

In ISCED, secondary may refer to level 2 (lower) and 3 (upper secondary). Is this evidence only about level 3 ? 
If not, it would be useful add an optional `level` field, so this model can be used to provide evidence for both (or even all) levels of education.

**Comment by SebastianSklarss** [comment]
If other education certificates are planned one should start with a generic model "educational evidences" 
with generic properties on issuer and issuing institution and the learner and the learning achievements.
Then the secondary education specificities and tertiary specificities should be derived.
I will create an own ticket for the proposed heritage structure.


Regarding ISCED the general educational evidence model should have the field
ISCED-2011-Level ranging from level 0 to level ISCED 8 (doctoral or equivalent)


the model on higher education institution diploma should than have a field
ISCED-2012-F telling about the field of studies

See here the possible values for ISCED-2011-level for the national educational systems
https://eacea.ec.europa.eu/national-policies/eurydice/

e.g. for the German system:
![image](https://user-images.githubusercontent.com/70315945/93062774-a9499600-f675-11ea-98ed-2f493be69318.png)

**Comment by cbahim** [comment]
As this evidence relates to the following three procedures:

- Submitting an initial application for admission to public tertiary education institution;
- Requesting academic recognition of diplomas, certificates or other proof of studies or courses;
- Recognition of professional qualifications of tourist guides.

We can conclude that this relates to ISCED 2011 level 3. The definition will be specified.
