### ISSUE TITLE
Secondary Education - link with / aligment DE4A 

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#96]
(feedback from BE experts)

DE4A D4.1  use case definition 1.0 is about "studying abroad", is this model aligned with the DE4A `table 5 UC #1 – Common Mandatory and Optional Academic Data for Procedure - Completion of Secondary Education`

Name | Description | Example value | Mandatory / Optional
-- | -- | -- | --
Country | Country of completed secondary  education; code list | Belgium | M
Degree | Degree previously  obtained | General upper secondary education | M
Name of school | Name of a secondary school that a person finished | International school | M
Name of programme | Name of a secondary school programme that a person successfully finished | General secondary   programme | M

**Comment by SebastianSklarss** [comment]
the given model
https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/certificate_of_completion_of_secondary_education/data_model/certificate_of_completion_of_secondary_education_diagram_v0.10.pdf

Seems to map to the given mandatory fields.
However other important fields should be mandatory too like the language and ID of the course or the credits achieved or the county of the organisation.

**Comment by cbahim** [comment]
With regards to the attributes from `DE4A table 5 UC #1`:

- Country = Location.geographicName
- Degree = ISCED Level 3 (see issue #95)
- Name of school = EducationInstitution.prefLabel
- Name of programme: the attribute programmeName has been added

With regards to the addition from @SebastianSklarss 
- No other member states have expressed this need.
