### ISSUE TITLE
Birth certificate (CZ)

### ISSUE THREAD

**Issue by psiotwo** [SEMICeu/SDG-sandbox#98]
Birth certificate issues
1. In the Czech Republic, gender is not registered on the birth certificate, it is the biological sex that is registered. It is important to add that at the moment of birth or shortly after (when registration of birth usually takes place), it is almost impossible to register someone’s gender. Later change to someone’s sex (due to surgical interventions) are registered in the birth registry and lead to the issuing of a new birth certificate.
2. Parent one and parent two are referred to as mother and father in the Czech birth certificate, therefore gender is not mentioned.
3. Citizenship is not mentioned on the Czech birth certificate.

**Comment by cbahim** [comment]
Thanks @psiotwo for your comments

> In the Czech Republic, gender is not registered on the birth certificate, it is the biological sex that is registered. It is important to add that at the moment of birth or shortly after (when registration of birth usually takes place), it is almost impossible to register someone’s gender. Later change to someone’s sex (due to surgical interventions) are registered in the birth registry and lead to the issuing of a new birth certificate.

That is a valid observation, besides our definition uses the word "sex" and the code list associated with the attribute is named [human sex](https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/human-sex/?target=Browse&uri=http://publications.europa.eu/resource/authority/human-sex), we therefore propose to change the name of the attribute to `sex`

> Parent one and parent two are referred to as mother and father in the Czech birth certificate, therefore gender is not mentioned.

If we understand correctly, the sex from the parent can be derived from the used relationship (e.g. mother:female, father:male) and thus can be automatically filled? 

> Citizenship is not mentioned on the Czech birth certificate.

This does not pose a problem as citizenship is not mandatory.
